// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.BuiltinAudioDecoderFactoryFactory

#ifndef org_webrtc_BuiltinAudioDecoderFactoryFactory_JNI
#define org_webrtc_BuiltinAudioDecoderFactoryFactory_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "BuiltinAudioDecoderFactoryFactory_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static int64_t JNI_BuiltinAudioDecoderFactoryFactory_CreateBuiltinAudioDecoderFactory(
//     JNIEnv* env);
//

// Triggers a compiler warning if DEFINE_JNI(BuiltinAudioDecoderFactoryFactory) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_BuiltinAudioDecoderFactoryFactory() {}

// Java to native functions
#define DEFINE_JNI_FOR_BuiltinAudioDecoderFactoryFactory()                                         \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT int64_t Java_J_N_MqPFZLwc(JNIEnv* env, jclass jcaller) {                \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_BuiltinAudioDecoderFactoryFactory();                           \
                                                                                                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_BuiltinAudioDecoderFactoryFactory_CreateBuiltinAudioDecoderFactory(std::forward<decltype(args)>(args)...)) { \
        return JNI_BuiltinAudioDecoderFactoryFactory_CreateBuiltinAudioDecoderFactory(std::forward<decltype(args)>(args)...); \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env); }) {                                             \
        return func_wrapper(env);                                                                  \
      } else if constexpr (requires { func_wrapper(); }) {                                         \
        return func_wrapper();                                                                     \
      } else {                                                                                     \
        static_assert(false, "JNI_BuiltinAudioDecoderFactoryFactory_CreateBuiltinAudioDecoderFactory() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: ()\nSee gen/jni_headers/sdk/android/generated_builtin_audio_codecs_jni/BuiltinAudioDecoderFactoryFactory_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

namespace webrtc::jni {


}  // namespace webrtc::jni
#pragma clang diagnostic pop
#endif  // org_webrtc_BuiltinAudioDecoderFactoryFactory_JNI
