# The modules/audio_coding/ sources of the gn targets libjingle_peerconnection_so
# depends on.
add_library(webrtc_modules_audio_coding OBJECT
  acm2/acm_remixing.cc
  acm2/acm_resampler.cc
  acm2/audio_coding_module.cc
  acm2/call_statistics.cc
  audio_network_adaptor/audio_network_adaptor_config.cc
  audio_network_adaptor/audio_network_adaptor_impl.cc
  audio_network_adaptor/bitrate_controller.cc
  audio_network_adaptor/channel_controller.cc
  audio_network_adaptor/controller.cc
  audio_network_adaptor/controller_manager.cc
  audio_network_adaptor/debug_dump_writer.cc
  audio_network_adaptor/dtx_controller.cc
  audio_network_adaptor/event_log_writer.cc
  audio_network_adaptor/fec_controller_plr_based.cc
  audio_network_adaptor/frame_length_controller.cc
  audio_network_adaptor/frame_length_controller_v2.cc
  codecs/cng/audio_encoder_cng.cc
  codecs/cng/webrtc_cng.cc
  codecs/g711/audio_decoder_pcm.cc
  codecs/g711/audio_encoder_pcm.cc
  codecs/g711/g711_interface.c
  codecs/g722/audio_decoder_g722.cc
  codecs/g722/audio_encoder_g722.cc
  codecs/g722/g722_interface.c
  codecs/isac/main/source/filter_functions.c
  codecs/isac/main/source/isac_vad.c
  codecs/isac/main/source/pitch_estimator.c
  codecs/isac/main/source/pitch_filter.c
  codecs/legacy_encoded_audio_frame.cc
  codecs/opus/audio_coder_opus_common.cc
  codecs/opus/audio_decoder_multi_channel_opus_impl.cc
  codecs/opus/audio_decoder_opus.cc
  codecs/opus/audio_encoder_multi_channel_opus_impl.cc
  codecs/opus/audio_encoder_opus.cc
  codecs/opus/opus_interface.cc
  codecs/pcm16b/audio_decoder_pcm16b.cc
  codecs/pcm16b/audio_encoder_pcm16b.cc
  codecs/pcm16b/pcm16b.c
  codecs/pcm16b/pcm16b_common.cc
  codecs/red/audio_encoder_copy_red.cc
  neteq/accelerate.cc
  neteq/audio_multi_vector.cc
  neteq/audio_vector.cc
  neteq/background_noise.cc
  neteq/buffer_level_filter.cc
  neteq/comfort_noise.cc
  neteq/cross_correlation.cc
  neteq/decision_logic.cc
  neteq/decoder_database.cc
  neteq/delay_constraints.cc
  neteq/delay_manager.cc
  neteq/dsp_helper.cc
  neteq/dtmf_buffer.cc
  neteq/dtmf_tone_generator.cc
  neteq/expand.cc
  neteq/expand_uma_logger.cc
  neteq/histogram.cc
  neteq/merge.cc
  neteq/neteq_impl.cc
  neteq/normal.cc
  neteq/packet.cc
  neteq/packet_arrival_history.cc
  neteq/packet_buffer.cc
  neteq/preemptive_expand.cc
  neteq/random_vector.cc
  neteq/red_payload_splitter.cc
  neteq/reorder_optimizer.cc
  neteq/statistics_calculator.cc
  neteq/sync_buffer.cc
  neteq/time_stretch.cc
  neteq/timestamp_scaler.cc
  neteq/underrun_optimizer.cc
)
target_link_libraries(webrtc_modules_audio_coding PRIVATE webrtc_config opus)
