//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc.audio;

import android.content.Context;
import android.media.AudioManager;
import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;
import org.webrtc.audio.WebRtcAudioRecord;
import org.webrtc.audio.WebRtcAudioTrack;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class JavaAudioDeviceModuleJni implements JavaAudioDeviceModule.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static JavaAudioDeviceModule.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (JavaAudioDeviceModule.Natives) holder.value;
    }
    return new JavaAudioDeviceModuleJni();
  }

  public static void setInstanceForTesting(JavaAudioDeviceModule.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public long createAudioDeviceModule(Context context, AudioManager audioManager, WebRtcAudioRecord audioInput, WebRtcAudioTrack audioOutput, long webrtcEnvRef, int inputSampleRate, int outputSampleRate, boolean useStereoInput, boolean useStereoOutput) {
    return (long) GEN_JNI.org_webrtc_audio_JavaAudioDeviceModule_createAudioDeviceModule(
        context,
        audioManager,
        audioInput,
        audioOutput,
        webrtcEnvRef,
        inputSampleRate,
        outputSampleRate,
        useStereoInput,
        useStereoOutput);
  }
}
