// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.audio.WebRtcAudioTrack

#ifndef org_webrtc_audio_WebRtcAudioTrack_JNI
#define org_webrtc_audio_WebRtcAudioTrack_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "WebRtcAudioTrack_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// void AudioTrackJni::CacheDirectBufferAddress(
//     JNIEnv* env,
//     const jni_zero::JavaRef<::java::nio::JByteBuffer>& byteBuffer);
//
// void AudioTrackJni::GetPlayoutData(JNIEnv* env, int32_t bytes);
//

// Triggers a compiler warning if DEFINE_JNI(WebRtcAudioTrack) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_WebRtcAudioTrack() {}

// Java to native functions
#define DEFINE_JNI_FOR_WebRtcAudioTrack()                                                          \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_MVoHeMKY(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t nativeAudioTrackJni,                                                                 \
      jobject byteBuffer) {                                                                        \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_WebRtcAudioTrack();                                            \
                                                                                                   \
    auto byteBuffer_ref = jni_zero::JavaRef<::java::nio::JByteBuffer>::CreateLeaky(env,            \
        static_cast<::java::nio::JByteBuffer>(byteBuffer));                                        \
    AudioTrackJni* _ptr = reinterpret_cast<AudioTrackJni*>(nativeAudioTrackJni);                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(_ptr->CacheDirectBufferAddress(std::forward<decltype(args)>(args)...)) {            \
        return _ptr->CacheDirectBufferAddress(std::forward<decltype(args)>(args)...);              \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, byteBuffer_ref); }) {                             \
        return func_wrapper(env, byteBuffer_ref);                                                  \
      } else if constexpr (requires { func_wrapper(byteBuffer_ref); }) {                           \
        return func_wrapper(byteBuffer_ref);                                                       \
      } else {                                                                                     \
        static_assert(false, "AudioTrackJni::CacheDirectBufferAddress() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (const jni_zero::JavaRef<JByteBuffer>&)\nSee gen/jni_headers/sdk/android/generated_java_audio_device_module_native_jni/WebRtcAudioTrack_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_MsGvGVCS(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t nativeAudioTrackJni,                                                                 \
      int32_t bytes) {                                                                             \
    AudioTrackJni* _ptr = reinterpret_cast<AudioTrackJni*>(nativeAudioTrackJni);                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(_ptr->GetPlayoutData(std::forward<decltype(args)>(args)...)) {                      \
        return _ptr->GetPlayoutData(std::forward<decltype(args)>(args)...);                        \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, bytes); }) {                                      \
        return func_wrapper(env, bytes);                                                           \
      } else if constexpr (requires { func_wrapper(bytes); }) {                                    \
        return func_wrapper(bytes);                                                                \
      } else {                                                                                     \
        static_assert(false, "AudioTrackJni::GetPlayoutData() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int32_t)\nSee gen/jni_headers/sdk/android/generated_java_audio_device_module_native_jni/WebRtcAudioTrack_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

// Class Accessors
#ifndef org_webrtc_audio_WebRtcAudioTrack_clazz_defined
#define org_webrtc_audio_WebRtcAudioTrack_clazz_defined
inline jclass org_webrtc_audio_WebRtcAudioTrack_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.audio.WebRtcAudioTrack";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_WebRtcAudioTrack_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& context,
    const ::jni_zero::JavaRef<jobject>& audioManager) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Landroid/content/Context;Landroid/media/AudioManager;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), context.obj(), audioManager.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static int32_t Java_WebRtcAudioTrack_GetPlayoutUnderrunCount(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "GetPlayoutUnderrunCount",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_WebRtcAudioTrack_getBufferSizeInFrames(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getBufferSizeInFrames",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_WebRtcAudioTrack_getInitialBufferSizeInFrames(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getInitialBufferSizeInFrames",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_WebRtcAudioTrack_getStreamMaxVolume(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getStreamMaxVolume",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_WebRtcAudioTrack_getStreamVolume(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getStreamVolume",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_WebRtcAudioTrack_initPlayout(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper sampleRate,
    JniIntWrapper channels,
    double bufferSizeFactor) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "initPlayout",
      "(IID)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(
      obj.obj(),
      call_context.method_id(),
      as_jint(sampleRate),
      as_jint(channels),
      bufferSizeFactor);
  return _ret;
}

static void Java_WebRtcAudioTrack_setNativeAudioTrack(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t nativeAudioTrack) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setNativeAudioTrack",
      "(J)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), nativeAudioTrack);
}

static bool Java_WebRtcAudioTrack_setStreamVolume(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper volume) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setStreamVolume",
      "(I)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), as_jint(volume));
  return _ret;
}

static bool Java_WebRtcAudioTrack_startPlayout(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "startPlayout",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static bool Java_WebRtcAudioTrack_stopPlayout(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "stopPlayout",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::audio::JWebRtcAudioTrack> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::audio::JWebRtcAudioTrack> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::android::content::JContext>& context,
      const ::jni_zero::JavaRef<::android::media::JAudioManager>& audioManager) {
    return Java_WebRtcAudioTrack_Constructor(env, context, audioManager)
        .As<::org::webrtc::audio::JWebRtcAudioTrack>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::audio::JWebRtcAudioTrack> {
  public:
  int32_t GetPlayoutUnderrunCount(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_GetPlayoutUnderrunCount(env, *this_obj);
  }

  int32_t getBufferSizeInFrames(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_getBufferSizeInFrames(env, *this_obj);
  }

  int32_t getInitialBufferSizeInFrames(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_getInitialBufferSizeInFrames(env, *this_obj);
  }

  int32_t getStreamMaxVolume(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_getStreamMaxVolume(env, *this_obj);
  }

  int32_t getStreamVolume(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_getStreamVolume(env, *this_obj);
  }

  int32_t initPlayout(
      JNIEnv* env,
      JniIntWrapper sampleRate,
      JniIntWrapper channels,
      double bufferSizeFactor) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_initPlayout(
        env,
        *this_obj,
        sampleRate,
        channels,
        bufferSizeFactor);
  }

  void setNativeAudioTrack(JNIEnv* env, int64_t nativeAudioTrack) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    Java_WebRtcAudioTrack_setNativeAudioTrack(env, *this_obj, nativeAudioTrack);
  }

  bool setStreamVolume(JNIEnv* env, JniIntWrapper volume) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_setStreamVolume(env, *this_obj, volume);
  }

  bool startPlayout(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_startPlayout(env, *this_obj);
  }

  bool stopPlayout(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>*>(this);
    return Java_WebRtcAudioTrack_stopPlayout(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc::audio {
using WebRtcAudioTrackJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::audio::JWebRtcAudioTrack>;
}
#ifndef _JNI_ZERO_WebRtcAudioTrackJni_DEFINED
#define _JNI_ZERO_WebRtcAudioTrackJni_DEFINED
using ::org::webrtc::audio::WebRtcAudioTrackJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_audio_WebRtcAudioTrack_JNI
