// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.ApplicationContextProvider

#ifndef org_webrtc_ApplicationContextProvider_JNI
#define org_webrtc_ApplicationContextProvider_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "ApplicationContextProvider_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_ApplicationContextProvider()

// Class Accessors
#ifndef org_webrtc_ApplicationContextProvider_clazz_defined
#define org_webrtc_ApplicationContextProvider_clazz_defined
inline jclass org_webrtc_ApplicationContextProvider_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.ApplicationContextProvider";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ApplicationContextProvider_getApplicationContext(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_ApplicationContextProvider_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getApplicationContext",
      "()Landroid/content/Context;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JApplicationContextProvider> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::android::content::JContext> getApplicationContext(
      JNIEnv* env) {
    return Java_ApplicationContextProvider_getApplicationContext(env)
        .As<::android::content::JContext>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using ApplicationContextProviderJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JApplicationContextProvider>;
}
#ifndef _JNI_ZERO_ApplicationContextProviderJni_DEFINED
#define _JNI_ZERO_ApplicationContextProviderJni_DEFINED
using ::org::webrtc::ApplicationContextProviderJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_ApplicationContextProvider_JNI
