//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class BuiltinAudioEncoderFactoryFactoryJni implements BuiltinAudioEncoderFactoryFactory.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static BuiltinAudioEncoderFactoryFactory.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (BuiltinAudioEncoderFactoryFactory.Natives) holder.value;
    }
    return new BuiltinAudioEncoderFactoryFactoryJni();
  }

  public static void setInstanceForTesting(BuiltinAudioEncoderFactoryFactory.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public long createBuiltinAudioEncoderFactory() {
    return (long) GEN_JNI.org_webrtc_BuiltinAudioEncoderFactoryFactory_createBuiltinAudioEncoderFactory();
  }
}
