//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class DtmfSenderJni implements DtmfSender.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static DtmfSender.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (DtmfSender.Natives) holder.value;
    }
    return new DtmfSenderJni();
  }

  public static void setInstanceForTesting(DtmfSender.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public boolean canInsertDtmf(long dtmfSender) {
    return (boolean) GEN_JNI.org_webrtc_DtmfSender_canInsertDtmf(dtmfSender);
  }

  @Override
  public int duration(long dtmfSender) {
    return (int) GEN_JNI.org_webrtc_DtmfSender_duration(dtmfSender);
  }

  @Override
  public boolean insertDtmf(long dtmfSender, String tones, int duration, int interToneGap) {
    return (boolean) GEN_JNI.org_webrtc_DtmfSender_insertDtmf(
        dtmfSender,
        tones,
        duration,
        interToneGap);
  }

  @Override
  public int interToneGap(long dtmfSender) {
    return (int) GEN_JNI.org_webrtc_DtmfSender_interToneGap(dtmfSender);
  }

  @Override
  public String tones(long dtmfSender) {
    return (String) GEN_JNI.org_webrtc_DtmfSender_tones(dtmfSender);
  }
}
