//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class EnvironmentJni implements Environment.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static Environment.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (Environment.Natives) holder.value;
    }
    return new EnvironmentJni();
  }

  public static void setInstanceForTesting(Environment.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public long create(String fieldTrials) {
    return (long) GEN_JNI.org_webrtc_Environment_create(fieldTrials);
  }

  @Override
  public long currentTimeNanos(long webrtcEnv) {
    return (long) GEN_JNI.org_webrtc_Environment_currentTimeNanos(webrtcEnv);
  }

  @Override
  public void free(long webrtcEnv) {
    GEN_JNI.org_webrtc_Environment_free(webrtcEnv);
  }
}
