//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class HistogramJni implements Histogram.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static Histogram.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (Histogram.Natives) holder.value;
    }
    return new HistogramJni();
  }

  public static void setInstanceForTesting(Histogram.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void addSample(long handle, int sample) {
    GEN_JNI.org_webrtc_Histogram_addSample(handle, sample);
  }

  @Override
  public long createCounts(String name, int min, int max, int bucketCount) {
    return (long) GEN_JNI.org_webrtc_Histogram_createCounts(name, min, max, bucketCount);
  }

  @Override
  public long createEnumeration(String name, int max) {
    return (long) GEN_JNI.org_webrtc_Histogram_createEnumeration(name, max);
  }
}
