//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;
import org.webrtc.MediaStreamTrack;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class MediaStreamTrackJni implements MediaStreamTrack.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static MediaStreamTrack.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (MediaStreamTrack.Natives) holder.value;
    }
    return new MediaStreamTrackJni();
  }

  public static void setInstanceForTesting(MediaStreamTrack.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public boolean getEnabled(long track) {
    return (boolean) GEN_JNI.org_webrtc_MediaStreamTrack_getEnabled(track);
  }

  @Override
  public String getId(long track) {
    return (String) GEN_JNI.org_webrtc_MediaStreamTrack_getId(track);
  }

  @Override
  public String getKind(long track) {
    return (String) GEN_JNI.org_webrtc_MediaStreamTrack_getKind(track);
  }

  @Override
  public MediaStreamTrack.State getState(long track) {
    return (MediaStreamTrack.State) GEN_JNI.org_webrtc_MediaStreamTrack_getState(track);
  }

  @Override
  public boolean setEnabled(long track, boolean enabled) {
    return (boolean) GEN_JNI.org_webrtc_MediaStreamTrack_setEnabled(track, enabled);
  }
}
