//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;
import org.webrtc.Metrics;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class MetricsJni implements Metrics.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static Metrics.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (Metrics.Natives) holder.value;
    }
    return new MetricsJni();
  }

  public static void setInstanceForTesting(Metrics.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void enable() {
    GEN_JNI.org_webrtc_Metrics_enable();
  }

  @Override
  public Metrics getAndReset() {
    return (Metrics) GEN_JNI.org_webrtc_Metrics_getAndReset();
  }
}
