//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import java.nio.ByteBuffer;
import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class NV12BufferJni implements NV12Buffer.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static NV12Buffer.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (NV12Buffer.Natives) holder.value;
    }
    return new NV12BufferJni();
  }

  public static void setInstanceForTesting(NV12Buffer.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void cropAndScale(int cropX, int cropY, int cropWidth, int cropHeight, int scaleWidth, int scaleHeight, ByteBuffer src, int srcWidth, int srcHeight, int srcStride, int srcSliceHeight, ByteBuffer dstY, int dstStrideY, ByteBuffer dstU, int dstStrideU, ByteBuffer dstV, int dstStrideV) {
    GEN_JNI.org_webrtc_NV12Buffer_cropAndScale(
        cropX,
        cropY,
        cropWidth,
        cropHeight,
        scaleWidth,
        scaleHeight,
        src,
        srcWidth,
        srcHeight,
        srcStride,
        srcSliceHeight,
        dstY,
        dstStrideY,
        dstU,
        dstStrideU,
        dstV,
        dstStrideV);
  }
}
