//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import java.util.List;
import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;
import org.webrtc.VideoCodecInfo;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class SoftwareVideoDecoderFactoryJni implements SoftwareVideoDecoderFactory.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static SoftwareVideoDecoderFactory.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (SoftwareVideoDecoderFactory.Natives) holder.value;
    }
    return new SoftwareVideoDecoderFactoryJni();
  }

  public static void setInstanceForTesting(SoftwareVideoDecoderFactory.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public long create(long factory, long webrtcEnvRef, VideoCodecInfo info) {
    return (long) GEN_JNI.org_webrtc_SoftwareVideoDecoderFactory_create(
        factory,
        webrtcEnvRef,
        info);
  }

  @Override
  public long createFactory() {
    return (long) GEN_JNI.org_webrtc_SoftwareVideoDecoderFactory_createFactory();
  }

  @Override
  public List getSupportedCodecs(long factory) {
    return (List) GEN_JNI.org_webrtc_SoftwareVideoDecoderFactory_getSupportedCodecs(factory);
  }

  @Override
  public boolean isSupported(long factory, VideoCodecInfo info) {
    return (boolean) GEN_JNI.org_webrtc_SoftwareVideoDecoderFactory_isSupported(factory, info);
  }
}
