//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class TurnCustomizerJni implements TurnCustomizer.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static TurnCustomizer.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (TurnCustomizer.Natives) holder.value;
    }
    return new TurnCustomizerJni();
  }

  public static void setInstanceForTesting(TurnCustomizer.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void freeTurnCustomizer(long turnCustomizer) {
    GEN_JNI.org_webrtc_TurnCustomizer_freeTurnCustomizer(turnCustomizer);
  }
}
