//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;
import org.webrtc.EncodedImage;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class VideoEncoderWrapperJni implements VideoEncoderWrapper.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static VideoEncoderWrapper.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (VideoEncoderWrapper.Natives) holder.value;
    }
    return new VideoEncoderWrapperJni();
  }

  public static void setInstanceForTesting(VideoEncoderWrapper.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void onEncodedFrame(long nativeVideoEncoderWrapper, EncodedImage frame) {
    assert nativeVideoEncoderWrapper != 0;
    GEN_JNI.org_webrtc_VideoEncoderWrapper_onEncodedFrame(nativeVideoEncoderWrapper, frame);
  }
}
