//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;
import org.webrtc.VideoEncoder;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class VideoEncoderFallbackJni implements VideoEncoderFallback.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static VideoEncoderFallback.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (VideoEncoderFallback.Natives) holder.value;
    }
    return new VideoEncoderFallbackJni();
  }

  public static void setInstanceForTesting(VideoEncoderFallback.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public long create(long webrtcEnvRef, VideoEncoder fallback, VideoEncoder primary) {
    return (long) GEN_JNI.org_webrtc_VideoEncoderFallback_create(webrtcEnvRef, fallback, primary);
  }
}
