//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;
import org.webrtc.VideoFrame;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class VideoDecoderWrapperJni implements VideoDecoderWrapper.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static VideoDecoderWrapper.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (VideoDecoderWrapper.Natives) holder.value;
    }
    return new VideoDecoderWrapperJni();
  }

  public static void setInstanceForTesting(VideoDecoderWrapper.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void onDecodedFrame(long nativeVideoDecoderWrapper, VideoFrame frame, Integer decodeTimeMs, Integer qp) {
    assert nativeVideoDecoderWrapper != 0;
    GEN_JNI.org_webrtc_VideoDecoderWrapper_onDecodedFrame(
        nativeVideoDecoderWrapper,
        frame,
        decodeTimeMs,
        qp);
  }
}
