//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.webrtc;

import java.nio.ByteBuffer;
import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class YuvHelperJni implements YuvHelper.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static YuvHelper.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (YuvHelper.Natives) holder.value;
    }
    return new YuvHelperJni();
  }

  public static void setInstanceForTesting(YuvHelper.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void abgrToI420(ByteBuffer src, int srcStride, ByteBuffer dstY, int dstStrideY, ByteBuffer dstU, int dstStrideU, ByteBuffer dstV, int dstStrideV, int width, int height) {
    GEN_JNI.org_webrtc_YuvHelper_abgrToI420(
        src,
        srcStride,
        dstY,
        dstStrideY,
        dstU,
        dstStrideU,
        dstV,
        dstStrideV,
        width,
        height);
  }

  @Override
  public void copyPlane(ByteBuffer src, int srcStride, ByteBuffer dst, int dstStride, int width, int height) {
    GEN_JNI.org_webrtc_YuvHelper_copyPlane(src, srcStride, dst, dstStride, width, height);
  }

  @Override
  public void i420Copy(ByteBuffer srcY, int srcStrideY, ByteBuffer srcU, int srcStrideU, ByteBuffer srcV, int srcStrideV, ByteBuffer dstY, int dstStrideY, ByteBuffer dstU, int dstStrideU, ByteBuffer dstV, int dstStrideV, int width, int height) {
    GEN_JNI.org_webrtc_YuvHelper_i420Copy(
        srcY,
        srcStrideY,
        srcU,
        srcStrideU,
        srcV,
        srcStrideV,
        dstY,
        dstStrideY,
        dstU,
        dstStrideU,
        dstV,
        dstStrideV,
        width,
        height);
  }

  @Override
  public void i420Rotate(ByteBuffer srcY, int srcStrideY, ByteBuffer srcU, int srcStrideU, ByteBuffer srcV, int srcStrideV, ByteBuffer dstY, int dstStrideY, ByteBuffer dstU, int dstStrideU, ByteBuffer dstV, int dstStrideV, int srcWidth, int srcHeight, int rotationMode) {
    GEN_JNI.org_webrtc_YuvHelper_i420Rotate(
        srcY,
        srcStrideY,
        srcU,
        srcStrideU,
        srcV,
        srcStrideV,
        dstY,
        dstStrideY,
        dstU,
        dstStrideU,
        dstV,
        dstStrideV,
        srcWidth,
        srcHeight,
        rotationMode);
  }

  @Override
  public void i420ToNV12(ByteBuffer srcY, int srcStrideY, ByteBuffer srcU, int srcStrideU, ByteBuffer srcV, int srcStrideV, ByteBuffer dstY, int dstStrideY, ByteBuffer dstUV, int dstStrideUV, int width, int height) {
    GEN_JNI.org_webrtc_YuvHelper_i420ToNV12(
        srcY,
        srcStrideY,
        srcU,
        srcStrideU,
        srcV,
        srcStrideV,
        dstY,
        dstStrideY,
        dstUV,
        dstStrideUV,
        width,
        height);
  }
}
