// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.Environment

#ifndef org_webrtc_Environment_JNI
#define org_webrtc_Environment_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Environment_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static int64_t JNI_Environment_Create(
//     JNIEnv* env,
//     const jni_zero::JavaRef<jstring>& fieldTrials);
//
// static int64_t JNI_Environment_CurrentTimeNanos(JNIEnv* env, int64_t webrtcEnv);
//
// static void JNI_Environment_Free(JNIEnv* env, int64_t webrtcEnv);
//

// Triggers a compiler warning if DEFINE_JNI(Environment) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_Environment() {}

// Java to native functions
#define DEFINE_JNI_FOR_Environment()                                                               \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT int64_t Java_J_N_M4R0A5nM(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      jobject fieldTrials) {                                                                       \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_Environment();                                                 \
                                                                                                   \
    auto fieldTrials_ref = jni_zero::JavaRef<jstring>::CreateLeaky(env,                            \
        static_cast<jstring>(fieldTrials));                                                        \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_Environment_Create(std::forward<decltype(args)>(args)...)) {                    \
        return JNI_Environment_Create(std::forward<decltype(args)>(args)...);                      \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, fieldTrials_ref); }) {                            \
        return func_wrapper(env, fieldTrials_ref);                                                 \
      } else if constexpr (requires { func_wrapper(fieldTrials_ref); }) {                          \
        return func_wrapper(fieldTrials_ref);                                                      \
      } else {                                                                                     \
        static_assert(false, "JNI_Environment_Create() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (const jni_zero::JavaRef<jstring>&)\nSee gen/jni_headers/sdk/android/generated_environment_jni/Environment_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT int64_t Java_J_N_M_1YMMZf6(                                             \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t webrtcEnv) {                                                                         \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_Environment_CurrentTimeNanos(std::forward<decltype(args)>(args)...)) {          \
        return JNI_Environment_CurrentTimeNanos(std::forward<decltype(args)>(args)...);            \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, webrtcEnv); }) {                                  \
        return func_wrapper(env, webrtcEnv);                                                       \
      } else if constexpr (requires { func_wrapper(webrtcEnv); }) {                                \
        return func_wrapper(webrtcEnv);                                                            \
      } else {                                                                                     \
        static_assert(false, "JNI_Environment_CurrentTimeNanos() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_environment_jni/Environment_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_MlqxOSjz(JNIEnv* env, jclass jcaller, int64_t webrtcEnv) { \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_Environment_Free(std::forward<decltype(args)>(args)...)) {                      \
        return JNI_Environment_Free(std::forward<decltype(args)>(args)...);                        \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, webrtcEnv); }) {                                  \
        return func_wrapper(env, webrtcEnv);                                                       \
      } else if constexpr (requires { func_wrapper(webrtcEnv); }) {                                \
        return func_wrapper(webrtcEnv);                                                            \
      } else {                                                                                     \
        static_assert(false, "JNI_Environment_Free() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_environment_jni/Environment_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

namespace webrtc::jni {


}  // namespace webrtc::jni
#pragma clang diagnostic pop
#endif  // org_webrtc_Environment_JNI
