// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.audio.JavaAudioDeviceModule

#ifndef org_webrtc_audio_JavaAudioDeviceModule_JNI
#define org_webrtc_audio_JavaAudioDeviceModule_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "JavaAudioDeviceModule_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static int64_t JNI_JavaAudioDeviceModule_CreateAudioDeviceModule(
//     JNIEnv* env,
//     const jni_zero::JavaRef<::android::content::JContext>& context,
//     const jni_zero::JavaRef<::android::media::JAudioManager>& audioManager,
//     const jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioRecord>& audioInput,
//     const jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>& audioOutput,
//     int64_t webrtcEnvRef,
//     int32_t inputSampleRate,
//     int32_t outputSampleRate,
//     bool useStereoInput,
//     bool useStereoOutput);
//

// Triggers a compiler warning if DEFINE_JNI(JavaAudioDeviceModule) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_JavaAudioDeviceModule() {}

// Java to native functions
#define DEFINE_JNI_FOR_JavaAudioDeviceModule()                                                     \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT int64_t Java_J_N_M3mJB0tB(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      jobject context,                                                                             \
      jobject audioManager,                                                                        \
      jobject audioInput,                                                                          \
      jobject audioOutput,                                                                         \
      int64_t webrtcEnvRef,                                                                        \
      int32_t inputSampleRate,                                                                     \
      int32_t outputSampleRate,                                                                    \
      bool useStereoInput,                                                                         \
      bool useStereoOutput) {                                                                      \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_JavaAudioDeviceModule();                                       \
                                                                                                   \
    auto context_ref = jni_zero::JavaRef<::android::content::JContext>::CreateLeaky(env,           \
        static_cast<::android::content::JContext>(context));                                       \
    auto audioManager_ref = jni_zero::JavaRef<::android::media::JAudioManager>::CreateLeaky(env,   \
        static_cast<::android::media::JAudioManager>(audioManager));                               \
    auto audioInput_ref = jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioRecord>::CreateLeaky(env, \
        static_cast<::org::webrtc::audio::JWebRtcAudioRecord>(audioInput));                        \
    auto audioOutput_ref = jni_zero::JavaRef<::org::webrtc::audio::JWebRtcAudioTrack>::CreateLeaky(env, \
        static_cast<::org::webrtc::audio::JWebRtcAudioTrack>(audioOutput));                        \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_JavaAudioDeviceModule_CreateAudioDeviceModule(std::forward<decltype(args)>(args)...)) { \
        return JNI_JavaAudioDeviceModule_CreateAudioDeviceModule(std::forward<decltype(args)>(args)...); \
      };                                                                                           \
      if constexpr (requires { func_wrapper(                                                       \
          env,                                                                                     \
          context_ref,                                                                             \
          audioManager_ref,                                                                        \
          audioInput_ref,                                                                          \
          audioOutput_ref,                                                                         \
          webrtcEnvRef,                                                                            \
          inputSampleRate,                                                                         \
          outputSampleRate,                                                                        \
          useStereoInput,                                                                          \
          useStereoOutput); }) {                                                                   \
        return func_wrapper(                                                                       \
            env,                                                                                   \
            context_ref,                                                                           \
            audioManager_ref,                                                                      \
            audioInput_ref,                                                                        \
            audioOutput_ref,                                                                       \
            webrtcEnvRef,                                                                          \
            inputSampleRate,                                                                       \
            outputSampleRate,                                                                      \
            useStereoInput,                                                                        \
            useStereoOutput);                                                                      \
      } else if constexpr (requires { func_wrapper(                                                \
          context_ref,                                                                             \
          audioManager_ref,                                                                        \
          audioInput_ref,                                                                          \
          audioOutput_ref,                                                                         \
          webrtcEnvRef,                                                                            \
          inputSampleRate,                                                                         \
          outputSampleRate,                                                                        \
          useStereoInput,                                                                          \
          useStereoOutput); }) {                                                                   \
        return func_wrapper(                                                                       \
            context_ref,                                                                           \
            audioManager_ref,                                                                      \
            audioInput_ref,                                                                        \
            audioOutput_ref,                                                                       \
            webrtcEnvRef,                                                                          \
            inputSampleRate,                                                                       \
            outputSampleRate,                                                                      \
            useStereoInput,                                                                        \
            useStereoOutput);                                                                      \
      } else {                                                                                     \
        static_assert(false, "JNI_JavaAudioDeviceModule_CreateAudioDeviceModule() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (const jni_zero::JavaRef<JContext>&, const jni_zero::JavaRef<JAudioManager>&, const jni_zero::JavaRef<JWebRtcAudioRecord>&, const jni_zero::JavaRef<JWebRtcAudioTrack>&, int64_t, int32_t, int32_t, bool, bool)\nSee gen/jni_headers/sdk/android/generated_java_audio_jni/JavaAudioDeviceModule_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

namespace webrtc::jni {


}  // namespace webrtc::jni
#pragma clang diagnostic pop
#endif  // org_webrtc_audio_JavaAudioDeviceModule_JNI
