// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.audio.JavaAudioDeviceModule

#ifndef org_webrtc_audio_JavaAudioDeviceModule_SHARED_JNI
#define org_webrtc_audio_JavaAudioDeviceModule_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_android_content_JContext_DEFINED
#define _JNI_ZERO_android_content_JContext_DEFINED
namespace android::content {
class _JContext : public _jobject {};
using JContext = _JContext*;
}
#endif

#ifndef _JNI_ZERO_JContext_DEFINED
#define _JNI_ZERO_JContext_DEFINED
using ::android::content::JContext;
#endif

#ifndef _JNI_ZERO_android_media_JAudioManager_DEFINED
#define _JNI_ZERO_android_media_JAudioManager_DEFINED
namespace android::media {
class _JAudioManager : public _jobject {};
using JAudioManager = _JAudioManager*;
}
#endif

#ifndef _JNI_ZERO_JAudioManager_DEFINED
#define _JNI_ZERO_JAudioManager_DEFINED
using ::android::media::JAudioManager;
#endif

#ifndef _JNI_ZERO_org_webrtc_audio_JWebRtcAudioRecord_DEFINED
#define _JNI_ZERO_org_webrtc_audio_JWebRtcAudioRecord_DEFINED
namespace org::webrtc::audio {
class _JWebRtcAudioRecord : public _jobject {};
using JWebRtcAudioRecord = _JWebRtcAudioRecord*;
}
#endif

#ifndef _JNI_ZERO_JWebRtcAudioRecord_DEFINED
#define _JNI_ZERO_JWebRtcAudioRecord_DEFINED
using ::org::webrtc::audio::JWebRtcAudioRecord;
#endif

#ifndef _JNI_ZERO_org_webrtc_audio_JWebRtcAudioTrack_DEFINED
#define _JNI_ZERO_org_webrtc_audio_JWebRtcAudioTrack_DEFINED
namespace org::webrtc::audio {
class _JWebRtcAudioTrack : public _jobject {};
using JWebRtcAudioTrack = _JWebRtcAudioTrack*;
}
#endif

#ifndef _JNI_ZERO_JWebRtcAudioTrack_DEFINED
#define _JNI_ZERO_JWebRtcAudioTrack_DEFINED
using ::org::webrtc::audio::JWebRtcAudioTrack;
#endif


#endif  // org_webrtc_audio_JavaAudioDeviceModule_SHARED_JNI
