// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.audio.WebRtcAudioManager

#ifndef org_webrtc_audio_WebRtcAudioManager_JNI
#define org_webrtc_audio_WebRtcAudioManager_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "WebRtcAudioManager_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_WebRtcAudioManager()

// Class Accessors
#ifndef org_webrtc_audio_WebRtcAudioManager_clazz_defined
#define org_webrtc_audio_WebRtcAudioManager_clazz_defined
inline jclass org_webrtc_audio_WebRtcAudioManager_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.audio.WebRtcAudioManager";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_WebRtcAudioManager_getAudioManager(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& context) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getAudioManager",
      "(Landroid/content/Context;)Landroid/media/AudioManager;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), context.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static int32_t Java_WebRtcAudioManager_getInputBufferSize(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& context,
    const ::jni_zero::JavaRef<jobject>& audioManager,
    JniIntWrapper sampleRate,
    JniIntWrapper numberOfInputChannels) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getInputBufferSize",
      "(Landroid/content/Context;Landroid/media/AudioManager;II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(
      clazz,
      call_context.method_id(),
      context.obj(),
      audioManager.obj(),
      as_jint(sampleRate),
      as_jint(numberOfInputChannels));
  return _ret;
}

static int32_t Java_WebRtcAudioManager_getOutputBufferSize(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& context,
    const ::jni_zero::JavaRef<jobject>& audioManager,
    JniIntWrapper sampleRate,
    JniIntWrapper numberOfOutputChannels) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getOutputBufferSize",
      "(Landroid/content/Context;Landroid/media/AudioManager;II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(
      clazz,
      call_context.method_id(),
      context.obj(),
      audioManager.obj(),
      as_jint(sampleRate),
      as_jint(numberOfOutputChannels));
  return _ret;
}

static int32_t Java_WebRtcAudioManager_getSampleRate(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& audioManager) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getSampleRate",
      "(Landroid/media/AudioManager;)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), audioManager.obj());
  return _ret;
}

static bool Java_WebRtcAudioManager_isLowLatencyInputSupported(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& context) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isLowLatencyInputSupported",
      "(Landroid/content/Context;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), context.obj());
  return _ret;
}

static bool Java_WebRtcAudioManager_isLowLatencyOutputSupported(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& context) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isLowLatencyOutputSupported",
      "(Landroid/content/Context;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), context.obj());
  return _ret;
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::audio::JWebRtcAudioManager> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::android::media::JAudioManager> getAudioManager(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::android::content::JContext>& context) {
    return Java_WebRtcAudioManager_getAudioManager(env, context)
        .As<::android::media::JAudioManager>();
  }

  static int32_t getInputBufferSize(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::android::content::JContext>& context,
      const ::jni_zero::JavaRef<::android::media::JAudioManager>& audioManager,
      JniIntWrapper sampleRate,
      JniIntWrapper numberOfInputChannels) {
    return Java_WebRtcAudioManager_getInputBufferSize(
        env,
        context,
        audioManager,
        sampleRate,
        numberOfInputChannels);
  }

  static int32_t getOutputBufferSize(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::android::content::JContext>& context,
      const ::jni_zero::JavaRef<::android::media::JAudioManager>& audioManager,
      JniIntWrapper sampleRate,
      JniIntWrapper numberOfOutputChannels) {
    return Java_WebRtcAudioManager_getOutputBufferSize(
        env,
        context,
        audioManager,
        sampleRate,
        numberOfOutputChannels);
  }

  static int32_t getSampleRate(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::android::media::JAudioManager>& audioManager) {
    return Java_WebRtcAudioManager_getSampleRate(env, audioManager);
  }

  static bool isLowLatencyInputSupported(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::android::content::JContext>& context) {
    return Java_WebRtcAudioManager_isLowLatencyInputSupported(env, context);
  }

  static bool isLowLatencyOutputSupported(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::android::content::JContext>& context) {
    return Java_WebRtcAudioManager_isLowLatencyOutputSupported(env, context);
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc::audio {
using WebRtcAudioManagerJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::audio::JWebRtcAudioManager>;
}
#ifndef _JNI_ZERO_WebRtcAudioManagerJni_DEFINED
#define _JNI_ZERO_WebRtcAudioManagerJni_DEFINED
using ::org::webrtc::audio::WebRtcAudioManagerJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_audio_WebRtcAudioManager_JNI
