// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.audio.WebRtcAudioManager

#ifndef org_webrtc_audio_WebRtcAudioManager_SHARED_JNI
#define org_webrtc_audio_WebRtcAudioManager_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_android_content_JContext_DEFINED
#define _JNI_ZERO_android_content_JContext_DEFINED
namespace android::content {
class _JContext : public _jobject {};
using JContext = _JContext*;
}
#endif

#ifndef _JNI_ZERO_JContext_DEFINED
#define _JNI_ZERO_JContext_DEFINED
using ::android::content::JContext;
#endif

#ifndef _JNI_ZERO_android_media_JAudioManager_DEFINED
#define _JNI_ZERO_android_media_JAudioManager_DEFINED
namespace android::media {
class _JAudioManager : public _jobject {};
using JAudioManager = _JAudioManager*;
}
#endif

#ifndef _JNI_ZERO_JAudioManager_DEFINED
#define _JNI_ZERO_JAudioManager_DEFINED
using ::android::media::JAudioManager;
#endif

#ifndef _JNI_ZERO_org_webrtc_audio_JWebRtcAudioManager_DEFINED
#define _JNI_ZERO_org_webrtc_audio_JWebRtcAudioManager_DEFINED
namespace org::webrtc::audio {
class _JWebRtcAudioManager : public _jobject {};
using JWebRtcAudioManager = _JWebRtcAudioManager*;
}
#endif

#ifndef _JNI_ZERO_JWebRtcAudioManager_DEFINED
#define _JNI_ZERO_JWebRtcAudioManager_DEFINED
using ::org::webrtc::audio::JWebRtcAudioManager;
#endif


#endif  // org_webrtc_audio_WebRtcAudioManager_SHARED_JNI
