# The video/ sources of the gn targets libjingle_peerconnection_so
# depends on.
add_library(webrtc_video ${WEBRTC_LIBRARY_TYPE}
  adaptation/balanced_constraint.cc
  adaptation/bandwidth_quality_scaler_resource.cc
  adaptation/bitrate_constraint.cc
  adaptation/encode_usage_resource.cc
  adaptation/overuse_frame_detector.cc
  adaptation/pixel_limit_resource.cc
  adaptation/quality_scaler_resource.cc
  adaptation/video_stream_encoder_resource.cc
  adaptation/video_stream_encoder_resource_manager.cc
  alignment_adjuster.cc
  buffered_frame_decryptor.cc
  call_stats2.cc
  config/encoder_stream_factory.cc
  config/simulcast.cc
  config/video_encoder_config.cc
  corruption_detection/corruption_classifier.cc
  corruption_detection/frame_instrumentation_generator_impl.cc
  corruption_detection/frame_selector.cc
  corruption_detection/generic_mapping_functions.cc
  corruption_detection/halton_frame_sampler.cc
  corruption_detection/halton_sequence.cc
  corruption_detection/utils.cc
  corruption_detection/video_frame_sampler.cc
  decode_synchronizer.cc
  encoder_bitrate_adjuster.cc
  encoder_overshoot_detector.cc
  encoder_rtcp_feedback.cc
  frame_cadence_adapter.cc
  frame_decode_timing.cc
  frame_dumping_decoder.cc
  frame_dumping_encoder.cc
  frame_encode_metadata_writer.cc
  null_video_decoder.cc
  quality_convergence_controller.cc
  quality_convergence_monitor.cc
  quality_limitation_reason_tracker.cc
  rate_utilization_tracker.cc
  receive_statistics_proxy.cc
  render/incoming_video_stream.cc
  render/video_render_frames.cc
  report_block_stats.cc
  rtp_streams_synchronizer2.cc
  rtp_video_stream_receiver2.cc
  send_delay_stats.cc
  send_statistics_proxy.cc
  stats_counter.cc
  stream_synchronization.cc
  task_queue_frame_decode_scheduler.cc
  timing/default_video_jitter_timing.cc
  timing/frame_delay_variation_kalman_filter.cc
  timing/inter_frame_delay_variation_calculator.cc
  timing/jitter_estimator.cc
  timing/rtt_filter.cc
  timing/timestamp_extrapolator.cc
  transport_adapter.cc
  unique_timestamp_counter.cc
  video_quality_observer2.cc
  video_receive_stream2.cc
  video_receive_stream_timeout_tracker.cc
  video_send_stream_impl.cc
  video_source_sink_controller.cc
  video_stream_buffer_controller.cc
  video_stream_decoder2.cc
  video_stream_encoder.cc
)
target_link_libraries(webrtc_video PRIVATE webrtc_config)
