// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.Logging

#ifndef org_webrtc_Logging_SHARED_JNI
#define org_webrtc_Logging_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:

#endif  // org_webrtc_Logging_SHARED_JNI
