// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.NetworkChangeDetector

#ifndef org_webrtc_NetworkChangeDetector_SHARED_JNI
#define org_webrtc_NetworkChangeDetector_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JNetworkChangeDetector_ConnectionType_DEFINED
#define _JNI_ZERO_org_webrtc_JNetworkChangeDetector_ConnectionType_DEFINED
namespace org::webrtc {
class _JNetworkChangeDetector_ConnectionType : public _jobject {};
using JNetworkChangeDetector_ConnectionType = _JNetworkChangeDetector_ConnectionType*;
}
#endif

#ifndef _JNI_ZERO_JNetworkChangeDetector_ConnectionType_DEFINED
#define _JNI_ZERO_JNetworkChangeDetector_ConnectionType_DEFINED
using ::org::webrtc::JNetworkChangeDetector_ConnectionType;
#endif

#ifndef _JNI_ZERO_org_webrtc_JNetworkChangeDetector_IPAddress_DEFINED
#define _JNI_ZERO_org_webrtc_JNetworkChangeDetector_IPAddress_DEFINED
namespace org::webrtc {
class _JNetworkChangeDetector_IPAddress : public _jobject {};
using JNetworkChangeDetector_IPAddress = _JNetworkChangeDetector_IPAddress*;
}
#endif

#ifndef _JNI_ZERO_JNetworkChangeDetector_IPAddress_DEFINED
#define _JNI_ZERO_JNetworkChangeDetector_IPAddress_DEFINED
using ::org::webrtc::JNetworkChangeDetector_IPAddress;
#endif

#ifndef _JNI_ZERO_org_webrtc_JNetworkChangeDetector_NetworkInformation_DEFINED
#define _JNI_ZERO_org_webrtc_JNetworkChangeDetector_NetworkInformation_DEFINED
namespace org::webrtc {
class _JNetworkChangeDetector_NetworkInformation : public _jobject {};
using JNetworkChangeDetector_NetworkInformation = _JNetworkChangeDetector_NetworkInformation*;
}
#endif

#ifndef _JNI_ZERO_JNetworkChangeDetector_NetworkInformation_DEFINED
#define _JNI_ZERO_JNetworkChangeDetector_NetworkInformation_DEFINED
using ::org::webrtc::JNetworkChangeDetector_NetworkInformation;
#endif


#endif  // org_webrtc_NetworkChangeDetector_SHARED_JNI
