// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.NetworkMonitor

#ifndef org_webrtc_NetworkMonitor_SHARED_JNI
#define org_webrtc_NetworkMonitor_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_android_content_JContext_DEFINED
#define _JNI_ZERO_android_content_JContext_DEFINED
namespace android::content {
class _JContext : public _jobject {};
using JContext = _JContext*;
}
#endif

#ifndef _JNI_ZERO_JContext_DEFINED
#define _JNI_ZERO_JContext_DEFINED
using ::android::content::JContext;
#endif

#ifndef _JNI_ZERO_org_webrtc_JNetworkChangeDetector_ConnectionType_DEFINED
#define _JNI_ZERO_org_webrtc_JNetworkChangeDetector_ConnectionType_DEFINED
namespace org::webrtc {
class _JNetworkChangeDetector_ConnectionType : public _jobject {};
using JNetworkChangeDetector_ConnectionType = _JNetworkChangeDetector_ConnectionType*;
}
#endif

#ifndef _JNI_ZERO_JNetworkChangeDetector_ConnectionType_DEFINED
#define _JNI_ZERO_JNetworkChangeDetector_ConnectionType_DEFINED
using ::org::webrtc::JNetworkChangeDetector_ConnectionType;
#endif

#ifndef _JNI_ZERO_org_webrtc_JNetworkMonitor_DEFINED
#define _JNI_ZERO_org_webrtc_JNetworkMonitor_DEFINED
namespace org::webrtc {
class _JNetworkMonitor : public _jobject {};
using JNetworkMonitor = _JNetworkMonitor*;
}
#endif

#ifndef _JNI_ZERO_JNetworkMonitor_DEFINED
#define _JNI_ZERO_JNetworkMonitor_DEFINED
using ::org::webrtc::JNetworkMonitor;
#endif

#ifndef _JNI_ZERO_org_webrtc_JNetworkChangeDetector_NetworkInformation_DEFINED
#define _JNI_ZERO_org_webrtc_JNetworkChangeDetector_NetworkInformation_DEFINED
namespace org::webrtc {
class _JNetworkChangeDetector_NetworkInformation : public _jobject {};
using JNetworkChangeDetector_NetworkInformation = _JNetworkChangeDetector_NetworkInformation*;
}
#endif

#ifndef _JNI_ZERO_JNetworkChangeDetector_NetworkInformation_DEFINED
#define _JNI_ZERO_JNetworkChangeDetector_NetworkInformation_DEFINED
using ::org::webrtc::JNetworkChangeDetector_NetworkInformation;
#endif


#endif  // org_webrtc_NetworkMonitor_SHARED_JNI
