// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RefCounted

#ifndef org_webrtc_RefCounted_SHARED_JNI
#define org_webrtc_RefCounted_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JRefCounted_DEFINED
#define _JNI_ZERO_org_webrtc_JRefCounted_DEFINED
namespace org::webrtc {
class _JRefCounted : public _jobject {};
using JRefCounted = _JRefCounted*;
}
#endif

#ifndef _JNI_ZERO_JRefCounted_DEFINED
#define _JNI_ZERO_JRefCounted_DEFINED
using ::org::webrtc::JRefCounted;
#endif


#endif  // org_webrtc_RefCounted_SHARED_JNI
