// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RtcError

#ifndef org_webrtc_RtcError_JNI
#define org_webrtc_RtcError_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "RtcError_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_RtcError()

// Class Accessors
#ifndef org_webrtc_RtcError_clazz_defined
#define org_webrtc_RtcError_clazz_defined
inline jclass org_webrtc_RtcError_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.RtcError";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_RtcError_error(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& error) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtcError_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "error",
      "(Ljava/lang/String;)Lorg/webrtc/RtcError;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), error.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_RtcError_success(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtcError_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "success",
      "()Lorg/webrtc/RtcError;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JRtcError> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JRtcError> error(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& error) {
    return Java_RtcError_error(env, error)
        .As<::org::webrtc::JRtcError>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JRtcError> success(JNIEnv* env) {
    return Java_RtcError_success(env)
        .As<::org::webrtc::JRtcError>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using RtcErrorJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JRtcError>;
}
#ifndef _JNI_ZERO_RtcErrorJni_DEFINED
#define _JNI_ZERO_RtcErrorJni_DEFINED
using ::org::webrtc::RtcErrorJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_RtcError_JNI
