# The pc/ sources of the gn targets libjingle_peerconnection_so
# depends on.
add_library(webrtc_pc ${WEBRTC_LIBRARY_TYPE}
  audio_rtp_receiver.cc
  audio_track.cc
  channel.cc
  codec_vendor.cc
  connection_context.cc
  data_channel_controller.cc
  data_channel_utils.cc
  dtls_srtp_transport.cc
  dtls_transport.cc
  dtmf_sender.cc
  encoded_audio_frame_injector.cc
  encoded_video_frame_injector.cc
  ice_server_parsing.cc
  ice_transport.cc
  jitter_buffer_delay.cc
  jsep_transport.cc
  jsep_transport_collection.cc
  jsep_transport_controller.cc
  legacy_stats_collector.cc
  local_audio_source.cc
  media_options.cc
  media_protocol_names.cc
  media_session.cc
  media_stream.cc
  media_stream_observer.cc
  peer_connection.cc
  peer_connection_factory.cc
  peer_connection_message_handler.cc
  remote_audio_source.cc
  rtc_stats_collector.cc
  rtc_stats_traversal.cc
  rtcp_mux_filter.cc
  rtp_media_utils.cc
  rtp_parameters_conversion.cc
  rtp_receiver.cc
  rtp_sender.cc
  rtp_transceiver.cc
  rtp_transmission_manager.cc
  rtp_transport.cc
  scoped_operations_batcher.cc
  sctp_data_channel.cc
  sctp_transport.cc
  sctp_utils.cc
  sdp_munging_detector.cc
  sdp_offer_answer.cc
  sdp_payload_type_suggester.cc
  session_description.cc
  simulcast_description.cc
  simulcast_sdp_serializer.cc
  srtp_session.cc
  srtp_transport.cc
  track_media_info_map.cc
  transceiver_list.cc
  transport_stats.cc
  typed_codec_vendor.cc
  usage_pattern.cc
  video_rtp_receiver.cc
  video_rtp_track_source.cc
  video_track.cc
  video_track_source.cc
  video_track_source_proxy.cc
  webrtc_session_description_factory.cc
)
target_link_libraries(webrtc_pc PRIVATE webrtc_config libsrtp)
