// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.AddIceObserver

#ifndef org_webrtc_AddIceObserver_SHARED_JNI
#define org_webrtc_AddIceObserver_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JAddIceObserver_DEFINED
#define _JNI_ZERO_org_webrtc_JAddIceObserver_DEFINED
namespace org::webrtc {
class _JAddIceObserver : public _jobject {};
using JAddIceObserver = _JAddIceObserver*;
}
#endif

#ifndef _JNI_ZERO_JAddIceObserver_DEFINED
#define _JNI_ZERO_JAddIceObserver_DEFINED
using ::org::webrtc::JAddIceObserver;
#endif


#endif  // org_webrtc_AddIceObserver_SHARED_JNI
