// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.CandidatePairChangeEvent

#ifndef org_webrtc_CandidatePairChangeEvent_JNI
#define org_webrtc_CandidatePairChangeEvent_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "CandidatePairChangeEvent_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_CandidatePairChangeEvent()

// Class Accessors
#ifndef org_webrtc_CandidatePairChangeEvent_clazz_defined
#define org_webrtc_CandidatePairChangeEvent_clazz_defined
inline jclass org_webrtc_CandidatePairChangeEvent_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.CandidatePairChangeEvent";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_CandidatePairChangeEvent_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& local,
    const ::jni_zero::JavaRef<jobject>& remote,
    JniIntWrapper lastDataReceivedMs,
    const ::jni_zero::JavaRef<jstring>& reason,
    JniIntWrapper estimatedDisconnectedTimeMs) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CandidatePairChangeEvent_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Lorg/webrtc/IceCandidate;Lorg/webrtc/IceCandidate;ILjava/lang/String;I)V",
      &cached_method_id);
  auto _ret = env->NewObject(
      clazz,
      call_context.method_id(),
      local.obj(),
      remote.obj(),
      as_jint(lastDataReceivedMs),
      reason.obj(),
      as_jint(estimatedDisconnectedTimeMs));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JCandidatePairChangeEvent> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JCandidatePairChangeEvent> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JIceCandidate>& local,
      const ::jni_zero::JavaRef<::org::webrtc::JIceCandidate>& remote,
      JniIntWrapper lastDataReceivedMs,
      const ::jni_zero::JavaRef<jstring>& reason,
      JniIntWrapper estimatedDisconnectedTimeMs) {
    return Java_CandidatePairChangeEvent_Constructor(
        env,
        local,
        remote,
        lastDataReceivedMs,
        reason,
        estimatedDisconnectedTimeMs)
        .As<::org::webrtc::JCandidatePairChangeEvent>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using CandidatePairChangeEventJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JCandidatePairChangeEvent>;
}
#ifndef _JNI_ZERO_CandidatePairChangeEventJni_DEFINED
#define _JNI_ZERO_CandidatePairChangeEventJni_DEFINED
using ::org::webrtc::CandidatePairChangeEventJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_CandidatePairChangeEvent_JNI
