// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.CryptoOptions

#ifndef org_webrtc_CryptoOptions_SHARED_JNI
#define org_webrtc_CryptoOptions_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JCryptoOptions_DEFINED
#define _JNI_ZERO_org_webrtc_JCryptoOptions_DEFINED
namespace org::webrtc {
class _JCryptoOptions : public _jobject {};
using JCryptoOptions = _JCryptoOptions*;
}
#endif

#ifndef _JNI_ZERO_JCryptoOptions_DEFINED
#define _JNI_ZERO_JCryptoOptions_DEFINED
using ::org::webrtc::JCryptoOptions;
#endif

#ifndef _JNI_ZERO_org_webrtc_JCryptoOptions_SFrame_DEFINED
#define _JNI_ZERO_org_webrtc_JCryptoOptions_SFrame_DEFINED
namespace org::webrtc {
class _JCryptoOptions_SFrame : public _jobject {};
using JCryptoOptions_SFrame = _JCryptoOptions_SFrame*;
}
#endif

#ifndef _JNI_ZERO_JCryptoOptions_SFrame_DEFINED
#define _JNI_ZERO_JCryptoOptions_SFrame_DEFINED
using ::org::webrtc::JCryptoOptions_SFrame;
#endif

#ifndef _JNI_ZERO_org_webrtc_JCryptoOptions_Srtp_DEFINED
#define _JNI_ZERO_org_webrtc_JCryptoOptions_Srtp_DEFINED
namespace org::webrtc {
class _JCryptoOptions_Srtp : public _jobject {};
using JCryptoOptions_Srtp = _JCryptoOptions_Srtp*;
}
#endif

#ifndef _JNI_ZERO_JCryptoOptions_Srtp_DEFINED
#define _JNI_ZERO_JCryptoOptions_Srtp_DEFINED
using ::org::webrtc::JCryptoOptions_Srtp;
#endif


#endif  // org_webrtc_CryptoOptions_SHARED_JNI
