// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.CryptoOptions

#ifndef org_webrtc_CryptoOptions_JNI
#define org_webrtc_CryptoOptions_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "CryptoOptions_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_CryptoOptions()

// Class Accessors
#ifndef org_webrtc_CryptoOptions_clazz_defined
#define org_webrtc_CryptoOptions_clazz_defined
inline jclass org_webrtc_CryptoOptions_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.CryptoOptions";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_CryptoOptions_00024SFrame_clazz_defined
#define org_webrtc_CryptoOptions_00024SFrame_clazz_defined
inline jclass org_webrtc_CryptoOptions_00024SFrame_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.CryptoOptions$SFrame";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_CryptoOptions_00024Srtp_clazz_defined
#define org_webrtc_CryptoOptions_00024Srtp_clazz_defined
inline jclass org_webrtc_CryptoOptions_00024Srtp_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.CryptoOptions$Srtp";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_CryptoOptions_getSFrame(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CryptoOptions_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getSFrame",
      "()Lorg/webrtc/CryptoOptions$SFrame;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_CryptoOptions_getSrtp(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CryptoOptions_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getSrtp",
      "()Lorg/webrtc/CryptoOptions$Srtp;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static bool Java_SFrame_getRequireFrameEncryption(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CryptoOptions_00024SFrame_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getRequireFrameEncryption",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static bool Java_Srtp_getEnableAes128Sha1_32CryptoCipher(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CryptoOptions_00024Srtp_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getEnableAes128Sha1_32CryptoCipher",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static bool Java_Srtp_getEnableAes128Sha1_80CryptoCipher(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CryptoOptions_00024Srtp_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getEnableAes128Sha1_80CryptoCipher",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static bool Java_Srtp_getEnableEncryptedRtpHeaderExtensions(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CryptoOptions_00024Srtp_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getEnableEncryptedRtpHeaderExtensions",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static bool Java_Srtp_getEnableGcmCryptoSuites(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CryptoOptions_00024Srtp_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getEnableGcmCryptoSuites",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static bool Java_Srtp_getPreferGcmCryptoSuites(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_CryptoOptions_00024Srtp_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getPreferGcmCryptoSuites",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNatives<::org::webrtc::JCryptoOptions> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JCryptoOptions_SFrame> getSFrame(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JCryptoOptions>*>(this);
    return Java_CryptoOptions_getSFrame(env, *this_obj)
        .As<::org::webrtc::JCryptoOptions_SFrame>();
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JCryptoOptions_Srtp> getSrtp(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JCryptoOptions>*>(this);
    return Java_CryptoOptions_getSrtp(env, *this_obj)
        .As<::org::webrtc::JCryptoOptions_Srtp>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JCryptoOptions_SFrame> {
  public:
  bool getRequireFrameEncryption(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JCryptoOptions_SFrame>*>(this);
    return Java_SFrame_getRequireFrameEncryption(env, *this_obj);
  }

};

template<>
class _CalledByNatives<::org::webrtc::JCryptoOptions_Srtp> {
  public:
  bool getEnableAes128Sha1_32CryptoCipher(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JCryptoOptions_Srtp>*>(this);
    return Java_Srtp_getEnableAes128Sha1_32CryptoCipher(env, *this_obj);
  }

  bool getEnableAes128Sha1_80CryptoCipher(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JCryptoOptions_Srtp>*>(this);
    return Java_Srtp_getEnableAes128Sha1_80CryptoCipher(env, *this_obj);
  }

  bool getEnableEncryptedRtpHeaderExtensions(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JCryptoOptions_Srtp>*>(this);
    return Java_Srtp_getEnableEncryptedRtpHeaderExtensions(env, *this_obj);
  }

  bool getEnableGcmCryptoSuites(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JCryptoOptions_Srtp>*>(this);
    return Java_Srtp_getEnableGcmCryptoSuites(env, *this_obj);
  }

  bool getPreferGcmCryptoSuites(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JCryptoOptions_Srtp>*>(this);
    return Java_Srtp_getPreferGcmCryptoSuites(env, *this_obj);
  }

};


}  // namespace jni_zero_internal


#pragma clang diagnostic pop
#endif  // org_webrtc_CryptoOptions_JNI
