// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.DataChannel

#ifndef org_webrtc_DataChannel_SHARED_JNI
#define org_webrtc_DataChannel_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_nio_JByteBuffer_DEFINED
#define _JNI_ZERO_java_nio_JByteBuffer_DEFINED
namespace java::nio {
class _JByteBuffer : public _jobject {};
using JByteBuffer = _JByteBuffer*;
}
#endif

#ifndef _JNI_ZERO_JByteBuffer_DEFINED
#define _JNI_ZERO_JByteBuffer_DEFINED
using ::java::nio::JByteBuffer;
#endif

#ifndef _JNI_ZERO_org_webrtc_JDataChannel_DEFINED
#define _JNI_ZERO_org_webrtc_JDataChannel_DEFINED
namespace org::webrtc {
class _JDataChannel : public _jobject {};
using JDataChannel = _JDataChannel*;
}
#endif

#ifndef _JNI_ZERO_JDataChannel_DEFINED
#define _JNI_ZERO_JDataChannel_DEFINED
using ::org::webrtc::JDataChannel;
#endif

#ifndef _JNI_ZERO_org_webrtc_JDataChannel_Buffer_DEFINED
#define _JNI_ZERO_org_webrtc_JDataChannel_Buffer_DEFINED
namespace org::webrtc {
class _JDataChannel_Buffer : public _jobject {};
using JDataChannel_Buffer = _JDataChannel_Buffer*;
}
#endif

#ifndef _JNI_ZERO_JDataChannel_Buffer_DEFINED
#define _JNI_ZERO_JDataChannel_Buffer_DEFINED
using ::org::webrtc::JDataChannel_Buffer;
#endif

#ifndef _JNI_ZERO_org_webrtc_JDataChannel_Init_DEFINED
#define _JNI_ZERO_org_webrtc_JDataChannel_Init_DEFINED
namespace org::webrtc {
class _JDataChannel_Init : public _jobject {};
using JDataChannel_Init = _JDataChannel_Init*;
}
#endif

#ifndef _JNI_ZERO_JDataChannel_Init_DEFINED
#define _JNI_ZERO_JDataChannel_Init_DEFINED
using ::org::webrtc::JDataChannel_Init;
#endif

#ifndef _JNI_ZERO_org_webrtc_JDataChannel_Observer_DEFINED
#define _JNI_ZERO_org_webrtc_JDataChannel_Observer_DEFINED
namespace org::webrtc {
class _JDataChannel_Observer : public _jobject {};
using JDataChannel_Observer = _JDataChannel_Observer*;
}
#endif

#ifndef _JNI_ZERO_JDataChannel_Observer_DEFINED
#define _JNI_ZERO_JDataChannel_Observer_DEFINED
using ::org::webrtc::JDataChannel_Observer;
#endif

#ifndef _JNI_ZERO_org_webrtc_JDataChannel_State_DEFINED
#define _JNI_ZERO_org_webrtc_JDataChannel_State_DEFINED
namespace org::webrtc {
class _JDataChannel_State : public _jobject {};
using JDataChannel_State = _JDataChannel_State*;
}
#endif

#ifndef _JNI_ZERO_JDataChannel_State_DEFINED
#define _JNI_ZERO_JDataChannel_State_DEFINED
using ::org::webrtc::JDataChannel_State;
#endif


#endif  // org_webrtc_DataChannel_SHARED_JNI
