// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.DtlsFingerprint

#ifndef org_webrtc_DtlsFingerprint_SHARED_JNI
#define org_webrtc_DtlsFingerprint_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JDtlsFingerprint_DEFINED
#define _JNI_ZERO_org_webrtc_JDtlsFingerprint_DEFINED
namespace org::webrtc {
class _JDtlsFingerprint : public _jobject {};
using JDtlsFingerprint = _JDtlsFingerprint*;
}
#endif

#ifndef _JNI_ZERO_JDtlsFingerprint_DEFINED
#define _JNI_ZERO_JDtlsFingerprint_DEFINED
using ::org::webrtc::JDtlsFingerprint;
#endif


#endif  // org_webrtc_DtlsFingerprint_SHARED_JNI
