// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.DtmfSender

#ifndef org_webrtc_DtmfSender_JNI
#define org_webrtc_DtmfSender_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "DtmfSender_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static bool JNI_DtmfSender_CanInsertDtmf(JNIEnv* env, int64_t dtmfSender);
//
// static int32_t JNI_DtmfSender_Duration(JNIEnv* env, int64_t dtmfSender);
//
// static bool JNI_DtmfSender_InsertDtmf(
//     JNIEnv* env,
//     int64_t dtmfSender,
//     const jni_zero::JavaRef<jstring>& tones,
//     int32_t duration,
//     int32_t interToneGap);
//
// static int32_t JNI_DtmfSender_InterToneGap(JNIEnv* env, int64_t dtmfSender);
//
// static jni_zero::ScopedJavaLocalRef<jstring> JNI_DtmfSender_Tones(
//     JNIEnv* env,
//     int64_t dtmfSender);
//

// Triggers a compiler warning if DEFINE_JNI(DtmfSender) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_DtmfSender() {}

// Java to native functions
#define DEFINE_JNI_FOR_DtmfSender()                                                                \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_M4qex4PR(JNIEnv* env, jclass jcaller, int64_t dtmfSender) { \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_DtmfSender();                                                  \
                                                                                                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_DtmfSender_CanInsertDtmf(std::forward<decltype(args)>(args)...)) {              \
        return JNI_DtmfSender_CanInsertDtmf(std::forward<decltype(args)>(args)...);                \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, dtmfSender); }) {                                 \
        return func_wrapper(env, dtmfSender);                                                      \
      } else if constexpr (requires { func_wrapper(dtmfSender); }) {                               \
        return func_wrapper(dtmfSender);                                                           \
      } else {                                                                                     \
        static_assert(false, "JNI_DtmfSender_CanInsertDtmf() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/DtmfSender_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT int32_t Java_J_N_MzwErI5a(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t dtmfSender) {                                                                        \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_DtmfSender_Duration(std::forward<decltype(args)>(args)...)) {                   \
        return JNI_DtmfSender_Duration(std::forward<decltype(args)>(args)...);                     \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, dtmfSender); }) {                                 \
        return func_wrapper(env, dtmfSender);                                                      \
      } else if constexpr (requires { func_wrapper(dtmfSender); }) {                               \
        return func_wrapper(dtmfSender);                                                           \
      } else {                                                                                     \
        static_assert(false, "JNI_DtmfSender_Duration() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/DtmfSender_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_MudP3V4Q(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t dtmfSender,                                                                          \
      jobject tones,                                                                               \
      int32_t duration,                                                                            \
      int32_t interToneGap) {                                                                      \
    auto tones_ref = jni_zero::JavaRef<jstring>::CreateLeaky(env,                                  \
        static_cast<jstring>(tones));                                                              \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_DtmfSender_InsertDtmf(std::forward<decltype(args)>(args)...)) {                 \
        return JNI_DtmfSender_InsertDtmf(std::forward<decltype(args)>(args)...);                   \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, dtmfSender, tones_ref, duration, interToneGap); }) { \
        return func_wrapper(env, dtmfSender, tones_ref, duration, interToneGap);                   \
      } else if constexpr (requires { func_wrapper(dtmfSender, tones_ref, duration, interToneGap); }) { \
        return func_wrapper(dtmfSender, tones_ref, duration, interToneGap);                        \
      } else {                                                                                     \
        static_assert(false, "JNI_DtmfSender_InsertDtmf() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, const jni_zero::JavaRef<jstring>&, int32_t, int32_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/DtmfSender_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT int32_t Java_J_N_M7dLuSbu(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t dtmfSender) {                                                                        \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_DtmfSender_InterToneGap(std::forward<decltype(args)>(args)...)) {               \
        return JNI_DtmfSender_InterToneGap(std::forward<decltype(args)>(args)...);                 \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, dtmfSender); }) {                                 \
        return func_wrapper(env, dtmfSender);                                                      \
      } else if constexpr (requires { func_wrapper(dtmfSender); }) {                               \
        return func_wrapper(dtmfSender);                                                           \
      } else {                                                                                     \
        static_assert(false, "JNI_DtmfSender_InterToneGap() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/DtmfSender_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT jobject Java_J_N_MIt25MoG(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t dtmfSender) {                                                                        \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_DtmfSender_Tones(std::forward<decltype(args)>(args)...)) {                      \
        return JNI_DtmfSender_Tones(std::forward<decltype(args)>(args)...);                        \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, dtmfSender); }) {                                 \
        return func_wrapper(env, dtmfSender);                                                      \
      } else if constexpr (requires { func_wrapper(dtmfSender); }) {                               \
        return func_wrapper(dtmfSender);                                                           \
      } else {                                                                                     \
        static_assert(false, "JNI_DtmfSender_Tones() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/DtmfSender_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value.ReleaseLocal();                                                            \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

namespace webrtc::jni {


}  // namespace webrtc::jni
#pragma clang diagnostic pop
#endif  // org_webrtc_DtmfSender_JNI
