// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.IceCandidateErrorEvent

#ifndef org_webrtc_IceCandidateErrorEvent_SHARED_JNI
#define org_webrtc_IceCandidateErrorEvent_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JIceCandidateErrorEvent_DEFINED
#define _JNI_ZERO_org_webrtc_JIceCandidateErrorEvent_DEFINED
namespace org::webrtc {
class _JIceCandidateErrorEvent : public _jobject {};
using JIceCandidateErrorEvent = _JIceCandidateErrorEvent*;
}
#endif

#ifndef _JNI_ZERO_JIceCandidateErrorEvent_DEFINED
#define _JNI_ZERO_JIceCandidateErrorEvent_DEFINED
using ::org::webrtc::JIceCandidateErrorEvent;
#endif


#endif  // org_webrtc_IceCandidateErrorEvent_SHARED_JNI
