// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.MediaStream

#ifndef org_webrtc_MediaStream_JNI
#define org_webrtc_MediaStream_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "MediaStream_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static bool JNI_MediaStream_AddAudioTrackToNativeStream(
//     JNIEnv* env,
//     int64_t stream,
//     int64_t nativeAudioTrack);
//
// static bool JNI_MediaStream_AddVideoTrackToNativeStream(
//     JNIEnv* env,
//     int64_t stream,
//     int64_t nativeVideoTrack);
//
// static jni_zero::ScopedJavaLocalRef<jstring> JNI_MediaStream_GetId(JNIEnv* env, int64_t stream);
//
// static bool JNI_MediaStream_RemoveAudioTrack(
//     JNIEnv* env,
//     int64_t stream,
//     int64_t nativeAudioTrack);
//
// static bool JNI_MediaStream_RemoveVideoTrack(
//     JNIEnv* env,
//     int64_t stream,
//     int64_t nativeVideoTrack);
//

// Triggers a compiler warning if DEFINE_JNI(MediaStream) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_MediaStream() {}

// Java to native functions
#define DEFINE_JNI_FOR_MediaStream()                                                               \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_MolrzZC3(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t stream,                                                                              \
      int64_t nativeAudioTrack) {                                                                  \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_MediaStream();                                                 \
                                                                                                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStream_AddAudioTrackToNativeStream(std::forward<decltype(args)>(args)...)) { \
        return JNI_MediaStream_AddAudioTrackToNativeStream(std::forward<decltype(args)>(args)...); \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, stream, nativeAudioTrack); }) {                   \
        return func_wrapper(env, stream, nativeAudioTrack);                                        \
      } else if constexpr (requires { func_wrapper(stream, nativeAudioTrack); }) {                 \
        return func_wrapper(stream, nativeAudioTrack);                                             \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStream_AddAudioTrackToNativeStream() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStream_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_MYJvq54P(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t stream,                                                                              \
      int64_t nativeVideoTrack) {                                                                  \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStream_AddVideoTrackToNativeStream(std::forward<decltype(args)>(args)...)) { \
        return JNI_MediaStream_AddVideoTrackToNativeStream(std::forward<decltype(args)>(args)...); \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, stream, nativeVideoTrack); }) {                   \
        return func_wrapper(env, stream, nativeVideoTrack);                                        \
      } else if constexpr (requires { func_wrapper(stream, nativeVideoTrack); }) {                 \
        return func_wrapper(stream, nativeVideoTrack);                                             \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStream_AddVideoTrackToNativeStream() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStream_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT jobject Java_J_N_Mt_18l5fS(JNIEnv* env, jclass jcaller, int64_t stream) { \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStream_GetId(std::forward<decltype(args)>(args)...)) {                     \
        return JNI_MediaStream_GetId(std::forward<decltype(args)>(args)...);                       \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, stream); }) {                                     \
        return func_wrapper(env, stream);                                                          \
      } else if constexpr (requires { func_wrapper(stream); }) {                                   \
        return func_wrapper(stream);                                                               \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStream_GetId() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStream_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value.ReleaseLocal();                                                            \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_Mwp_00024naK3(                                            \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t stream,                                                                              \
      int64_t nativeAudioTrack) {                                                                  \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStream_RemoveAudioTrack(std::forward<decltype(args)>(args)...)) {          \
        return JNI_MediaStream_RemoveAudioTrack(std::forward<decltype(args)>(args)...);            \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, stream, nativeAudioTrack); }) {                   \
        return func_wrapper(env, stream, nativeAudioTrack);                                        \
      } else if constexpr (requires { func_wrapper(stream, nativeAudioTrack); }) {                 \
        return func_wrapper(stream, nativeAudioTrack);                                             \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStream_RemoveAudioTrack() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStream_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_MtuWJk48(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t stream,                                                                              \
      int64_t nativeVideoTrack) {                                                                  \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStream_RemoveVideoTrack(std::forward<decltype(args)>(args)...)) {          \
        return JNI_MediaStream_RemoveVideoTrack(std::forward<decltype(args)>(args)...);            \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, stream, nativeVideoTrack); }) {                   \
        return func_wrapper(env, stream, nativeVideoTrack);                                        \
      } else if constexpr (requires { func_wrapper(stream, nativeVideoTrack); }) {                 \
        return func_wrapper(stream, nativeVideoTrack);                                             \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStream_RemoveVideoTrack() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStream_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

// Class Accessors
#ifndef org_webrtc_MediaStream_clazz_defined
#define org_webrtc_MediaStream_clazz_defined
inline jclass org_webrtc_MediaStream_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.MediaStream";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_MediaStream_Constructor(
    JNIEnv* env,
    int64_t nativeStream) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStream_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(J)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), nativeStream);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static void Java_MediaStream_addNativeAudioTrack(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t nativeTrack) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStream_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "addNativeAudioTrack",
      "(J)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), nativeTrack);
}

static void Java_MediaStream_addNativeVideoTrack(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t nativeTrack) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStream_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "addNativeVideoTrack",
      "(J)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), nativeTrack);
}

static void Java_MediaStream_dispose(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStream_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "dispose",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

static void Java_MediaStream_removeAudioTrack(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t nativeTrack) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStream_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "removeAudioTrack",
      "(J)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), nativeTrack);
}

static void Java_MediaStream_removeVideoTrack(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t nativeTrack) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStream_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "removeVideoTrack",
      "(J)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), nativeTrack);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JMediaStream> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JMediaStream> New(
      JNIEnv* env,
      int64_t nativeStream) {
    return Java_MediaStream_Constructor(env, nativeStream)
        .As<::org::webrtc::JMediaStream>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JMediaStream> {
  public:
  void addNativeAudioTrack(JNIEnv* env, int64_t nativeTrack) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JMediaStream>*>(this);
    Java_MediaStream_addNativeAudioTrack(env, *this_obj, nativeTrack);
  }

  void addNativeVideoTrack(JNIEnv* env, int64_t nativeTrack) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JMediaStream>*>(this);
    Java_MediaStream_addNativeVideoTrack(env, *this_obj, nativeTrack);
  }

  void dispose(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JMediaStream>*>(this);
    Java_MediaStream_dispose(env, *this_obj);
  }

  void removeAudioTrack(JNIEnv* env, int64_t nativeTrack) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JMediaStream>*>(this);
    Java_MediaStream_removeAudioTrack(env, *this_obj, nativeTrack);
  }

  void removeVideoTrack(JNIEnv* env, int64_t nativeTrack) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JMediaStream>*>(this);
    Java_MediaStream_removeVideoTrack(env, *this_obj, nativeTrack);
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using MediaStreamJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JMediaStream>;
}
#ifndef _JNI_ZERO_MediaStreamJni_DEFINED
#define _JNI_ZERO_MediaStreamJni_DEFINED
using ::org::webrtc::MediaStreamJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_MediaStream_JNI
