// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.MediaStream

#ifndef org_webrtc_MediaStream_SHARED_JNI
#define org_webrtc_MediaStream_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JMediaStream_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaStream_DEFINED
namespace org::webrtc {
class _JMediaStream : public _jobject {};
using JMediaStream = _JMediaStream*;
}
#endif

#ifndef _JNI_ZERO_JMediaStream_DEFINED
#define _JNI_ZERO_JMediaStream_DEFINED
using ::org::webrtc::JMediaStream;
#endif


#endif  // org_webrtc_MediaStream_SHARED_JNI
