// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.MediaStreamTrack

#ifndef org_webrtc_MediaStreamTrack_JNI
#define org_webrtc_MediaStreamTrack_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "MediaStreamTrack_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static bool JNI_MediaStreamTrack_GetEnabled(JNIEnv* env, int64_t track);
//
// static jni_zero::ScopedJavaLocalRef<jstring> JNI_MediaStreamTrack_GetId(
//     JNIEnv* env,
//     int64_t track);
//
// static jni_zero::ScopedJavaLocalRef<jstring> JNI_MediaStreamTrack_GetKind(
//     JNIEnv* env,
//     int64_t track);
//
// static jni_zero::ScopedJavaLocalRef<::org::webrtc::JMediaStreamTrack_State> JNI_MediaStreamTrack_GetState(
//     JNIEnv* env,
//     int64_t track);
//
// static bool JNI_MediaStreamTrack_SetEnabled(JNIEnv* env, int64_t track, bool enabled);
//

// Triggers a compiler warning if DEFINE_JNI(MediaStreamTrack) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_MediaStreamTrack() {}

// Java to native functions
#define DEFINE_JNI_FOR_MediaStreamTrack()                                                          \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_MYSN7kq0(JNIEnv* env, jclass jcaller, int64_t track) {    \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_MediaStreamTrack();                                            \
                                                                                                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStreamTrack_GetEnabled(std::forward<decltype(args)>(args)...)) {           \
        return JNI_MediaStreamTrack_GetEnabled(std::forward<decltype(args)>(args)...);             \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, track); }) {                                      \
        return func_wrapper(env, track);                                                           \
      } else if constexpr (requires { func_wrapper(track); }) {                                    \
        return func_wrapper(track);                                                                \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStreamTrack_GetEnabled() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStreamTrack_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT jobject Java_J_N_M0wsxYTj(JNIEnv* env, jclass jcaller, int64_t track) { \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStreamTrack_GetId(std::forward<decltype(args)>(args)...)) {                \
        return JNI_MediaStreamTrack_GetId(std::forward<decltype(args)>(args)...);                  \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, track); }) {                                      \
        return func_wrapper(env, track);                                                           \
      } else if constexpr (requires { func_wrapper(track); }) {                                    \
        return func_wrapper(track);                                                                \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStreamTrack_GetId() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStreamTrack_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value.ReleaseLocal();                                                            \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT jobject Java_J_N_McnM5t8_1(JNIEnv* env, jclass jcaller, int64_t track) { \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStreamTrack_GetKind(std::forward<decltype(args)>(args)...)) {              \
        return JNI_MediaStreamTrack_GetKind(std::forward<decltype(args)>(args)...);                \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, track); }) {                                      \
        return func_wrapper(env, track);                                                           \
      } else if constexpr (requires { func_wrapper(track); }) {                                    \
        return func_wrapper(track);                                                                \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStreamTrack_GetKind() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStreamTrack_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value.ReleaseLocal();                                                            \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT jobject Java_J_N_MR7dbZmC(JNIEnv* env, jclass jcaller, int64_t track) { \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStreamTrack_GetState(std::forward<decltype(args)>(args)...)) {             \
        return JNI_MediaStreamTrack_GetState(std::forward<decltype(args)>(args)...);               \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, track); }) {                                      \
        return func_wrapper(env, track);                                                           \
      } else if constexpr (requires { func_wrapper(track); }) {                                    \
        return func_wrapper(track);                                                                \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStreamTrack_GetState() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStreamTrack_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value.ReleaseLocal();                                                            \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_MqYTGc3U(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t track,                                                                               \
      bool enabled) {                                                                              \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaStreamTrack_SetEnabled(std::forward<decltype(args)>(args)...)) {           \
        return JNI_MediaStreamTrack_SetEnabled(std::forward<decltype(args)>(args)...);             \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, track, enabled); }) {                             \
        return func_wrapper(env, track, enabled);                                                  \
      } else if constexpr (requires { func_wrapper(track, enabled); }) {                           \
        return func_wrapper(track, enabled);                                                       \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaStreamTrack_SetEnabled() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, bool)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaStreamTrack_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

// Class Accessors
#ifndef org_webrtc_MediaStreamTrack_00024MediaType_clazz_defined
#define org_webrtc_MediaStreamTrack_00024MediaType_clazz_defined
inline jclass org_webrtc_MediaStreamTrack_00024MediaType_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.MediaStreamTrack$MediaType";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_MediaStreamTrack_00024State_clazz_defined
#define org_webrtc_MediaStreamTrack_00024State_clazz_defined
inline jclass org_webrtc_MediaStreamTrack_00024State_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.MediaStreamTrack$State";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static int32_t Java_MediaType_getNative(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStreamTrack_00024MediaType_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getNative",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_MediaType_fromNativeIndex(
    JNIEnv* env,
    JniIntWrapper nativeIndex) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStreamTrack_00024MediaType_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "fromNativeIndex",
      "(I)Lorg/webrtc/MediaStreamTrack$MediaType;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(nativeIndex));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_State_fromNativeIndex(
    JNIEnv* env,
    JniIntWrapper nativeIndex) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaStreamTrack_00024State_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "fromNativeIndex",
      "(I)Lorg/webrtc/MediaStreamTrack$State;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(nativeIndex));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JMediaStreamTrack_MediaType> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JMediaStreamTrack_MediaType> fromNativeIndex(
      JNIEnv* env,
      JniIntWrapper nativeIndex) {
    return Java_MediaType_fromNativeIndex(env, nativeIndex)
        .As<::org::webrtc::JMediaStreamTrack_MediaType>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JMediaStreamTrack_MediaType> {
  public:
  int32_t getNative(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JMediaStreamTrack_MediaType>*>(this);
    return Java_MediaType_getNative(env, *this_obj);
  }

};

template<>
class _CalledByNativesStatics<::org::webrtc::JMediaStreamTrack_State> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JMediaStreamTrack_State> fromNativeIndex(
      JNIEnv* env,
      JniIntWrapper nativeIndex) {
    return Java_State_fromNativeIndex(env, nativeIndex)
        .As<::org::webrtc::JMediaStreamTrack_State>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using MediaStreamTrack_MediaTypeJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JMediaStreamTrack_MediaType>;
}
#ifndef _JNI_ZERO_MediaStreamTrack_MediaTypeJni_DEFINED
#define _JNI_ZERO_MediaStreamTrack_MediaTypeJni_DEFINED
using ::org::webrtc::MediaStreamTrack_MediaTypeJni;
#endif

namespace org::webrtc {
using MediaStreamTrack_StateJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JMediaStreamTrack_State>;
}
#ifndef _JNI_ZERO_MediaStreamTrack_StateJni_DEFINED
#define _JNI_ZERO_MediaStreamTrack_StateJni_DEFINED
using ::org::webrtc::MediaStreamTrack_StateJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_MediaStreamTrack_JNI
