// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.MediaSource

#ifndef org_webrtc_MediaSource_JNI
#define org_webrtc_MediaSource_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "MediaSource_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static jni_zero::ScopedJavaLocalRef<::org::webrtc::JMediaSource_State> JNI_MediaSource_GetState(
//     JNIEnv* env,
//     int64_t pointer);
//

// Triggers a compiler warning if DEFINE_JNI(MediaSource) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_MediaSource() {}

// Java to native functions
#define DEFINE_JNI_FOR_MediaSource()                                                               \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT jobject Java_J_N_MKSPR50A(JNIEnv* env, jclass jcaller, int64_t pointer) { \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_MediaSource();                                                 \
                                                                                                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_MediaSource_GetState(std::forward<decltype(args)>(args)...)) {                  \
        return JNI_MediaSource_GetState(std::forward<decltype(args)>(args)...);                    \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, pointer); }) {                                    \
        return func_wrapper(env, pointer);                                                         \
      } else if constexpr (requires { func_wrapper(pointer); }) {                                  \
        return func_wrapper(pointer);                                                              \
      } else {                                                                                     \
        static_assert(false, "JNI_MediaSource_GetState() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/MediaSource_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value.ReleaseLocal();                                                            \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

// Class Accessors
#ifndef org_webrtc_MediaSource_00024State_clazz_defined
#define org_webrtc_MediaSource_00024State_clazz_defined
inline jclass org_webrtc_MediaSource_00024State_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.MediaSource$State";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_State_fromNativeIndex(
    JNIEnv* env,
    JniIntWrapper nativeIndex) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_MediaSource_00024State_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "fromNativeIndex",
      "(I)Lorg/webrtc/MediaSource$State;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(nativeIndex));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JMediaSource_State> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JMediaSource_State> fromNativeIndex(
      JNIEnv* env,
      JniIntWrapper nativeIndex) {
    return Java_State_fromNativeIndex(env, nativeIndex)
        .As<::org::webrtc::JMediaSource_State>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using MediaSource_StateJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JMediaSource_State>;
}
#ifndef _JNI_ZERO_MediaSource_StateJni_DEFINED
#define _JNI_ZERO_MediaSource_StateJni_DEFINED
using ::org::webrtc::MediaSource_StateJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_MediaSource_JNI
