// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.MediaSource

#ifndef org_webrtc_MediaSource_SHARED_JNI
#define org_webrtc_MediaSource_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JMediaSource_State_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaSource_State_DEFINED
namespace org::webrtc {
class _JMediaSource_State : public _jobject {};
using JMediaSource_State = _JMediaSource_State*;
}
#endif

#ifndef _JNI_ZERO_JMediaSource_State_DEFINED
#define _JNI_ZERO_JMediaSource_State_DEFINED
using ::org::webrtc::JMediaSource_State;
#endif


#endif  // org_webrtc_MediaSource_SHARED_JNI
