// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.MediaConstraints

#ifndef org_webrtc_MediaConstraints_SHARED_JNI
#define org_webrtc_MediaConstraints_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_util_JList_DEFINED
#define _JNI_ZERO_java_util_JList_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JList : public _jobject {};
template <typename T>
using JList = _JList<T>*;
}
#endif

#ifndef _JNI_ZERO_JList_DEFINED
#define _JNI_ZERO_JList_DEFINED
using ::java::util::JList;
#endif

#ifndef _JNI_ZERO_org_webrtc_JMediaConstraints_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaConstraints_DEFINED
namespace org::webrtc {
class _JMediaConstraints : public _jobject {};
using JMediaConstraints = _JMediaConstraints*;
}
#endif

#ifndef _JNI_ZERO_JMediaConstraints_DEFINED
#define _JNI_ZERO_JMediaConstraints_DEFINED
using ::org::webrtc::JMediaConstraints;
#endif

#ifndef _JNI_ZERO_org_webrtc_JMediaConstraints_KeyValuePair_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaConstraints_KeyValuePair_DEFINED
namespace org::webrtc {
class _JMediaConstraints_KeyValuePair : public _jobject {};
using JMediaConstraints_KeyValuePair = _JMediaConstraints_KeyValuePair*;
}
#endif

#ifndef _JNI_ZERO_JMediaConstraints_KeyValuePair_DEFINED
#define _JNI_ZERO_JMediaConstraints_KeyValuePair_DEFINED
using ::org::webrtc::JMediaConstraints_KeyValuePair;
#endif


#endif  // org_webrtc_MediaConstraints_SHARED_JNI
