// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.PeerConnection

#ifndef org_webrtc_PeerConnection_SHARED_JNI
#define org_webrtc_PeerConnection_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JInteger_DEFINED
#define _JNI_ZERO_java_lang_JInteger_DEFINED
namespace java::lang {
class _JInteger : public _jobject {};
using JInteger = _JInteger*;
}
#endif

#ifndef _JNI_ZERO_JInteger_DEFINED
#define _JNI_ZERO_JInteger_DEFINED
using ::java::lang::JInteger;
#endif

#ifndef _JNI_ZERO_java_util_JList_DEFINED
#define _JNI_ZERO_java_util_JList_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JList : public _jobject {};
template <typename T>
using JList = _JList<T>*;
}
#endif

#ifndef _JNI_ZERO_JList_DEFINED
#define _JNI_ZERO_JList_DEFINED
using ::java::util::JList;
#endif

#ifndef _JNI_ZERO_org_webrtc_JAddIceObserver_DEFINED
#define _JNI_ZERO_org_webrtc_JAddIceObserver_DEFINED
namespace org::webrtc {
class _JAddIceObserver : public _jobject {};
using JAddIceObserver = _JAddIceObserver*;
}
#endif

#ifndef _JNI_ZERO_JAddIceObserver_DEFINED
#define _JNI_ZERO_JAddIceObserver_DEFINED
using ::org::webrtc::JAddIceObserver;
#endif

#ifndef _JNI_ZERO_org_webrtc_JCandidatePairChangeEvent_DEFINED
#define _JNI_ZERO_org_webrtc_JCandidatePairChangeEvent_DEFINED
namespace org::webrtc {
class _JCandidatePairChangeEvent : public _jobject {};
using JCandidatePairChangeEvent = _JCandidatePairChangeEvent*;
}
#endif

#ifndef _JNI_ZERO_JCandidatePairChangeEvent_DEFINED
#define _JNI_ZERO_JCandidatePairChangeEvent_DEFINED
using ::org::webrtc::JCandidatePairChangeEvent;
#endif

#ifndef _JNI_ZERO_org_webrtc_JCryptoOptions_DEFINED
#define _JNI_ZERO_org_webrtc_JCryptoOptions_DEFINED
namespace org::webrtc {
class _JCryptoOptions : public _jobject {};
using JCryptoOptions = _JCryptoOptions*;
}
#endif

#ifndef _JNI_ZERO_JCryptoOptions_DEFINED
#define _JNI_ZERO_JCryptoOptions_DEFINED
using ::org::webrtc::JCryptoOptions;
#endif

#ifndef _JNI_ZERO_org_webrtc_JDataChannel_DEFINED
#define _JNI_ZERO_org_webrtc_JDataChannel_DEFINED
namespace org::webrtc {
class _JDataChannel : public _jobject {};
using JDataChannel = _JDataChannel*;
}
#endif

#ifndef _JNI_ZERO_JDataChannel_DEFINED
#define _JNI_ZERO_JDataChannel_DEFINED
using ::org::webrtc::JDataChannel;
#endif

#ifndef _JNI_ZERO_org_webrtc_JDataChannel_Init_DEFINED
#define _JNI_ZERO_org_webrtc_JDataChannel_Init_DEFINED
namespace org::webrtc {
class _JDataChannel_Init : public _jobject {};
using JDataChannel_Init = _JDataChannel_Init*;
}
#endif

#ifndef _JNI_ZERO_JDataChannel_Init_DEFINED
#define _JNI_ZERO_JDataChannel_Init_DEFINED
using ::org::webrtc::JDataChannel_Init;
#endif

#ifndef _JNI_ZERO_org_webrtc_JIceCandidate_DEFINED
#define _JNI_ZERO_org_webrtc_JIceCandidate_DEFINED
namespace org::webrtc {
class _JIceCandidate : public _jobject {};
using JIceCandidate = _JIceCandidate*;
}
#endif

#ifndef _JNI_ZERO_JIceCandidate_DEFINED
#define _JNI_ZERO_JIceCandidate_DEFINED
using ::org::webrtc::JIceCandidate;
#endif

#ifndef _JNI_ZERO_org_webrtc_JIceCandidateErrorEvent_DEFINED
#define _JNI_ZERO_org_webrtc_JIceCandidateErrorEvent_DEFINED
namespace org::webrtc {
class _JIceCandidateErrorEvent : public _jobject {};
using JIceCandidateErrorEvent = _JIceCandidateErrorEvent*;
}
#endif

#ifndef _JNI_ZERO_JIceCandidateErrorEvent_DEFINED
#define _JNI_ZERO_JIceCandidateErrorEvent_DEFINED
using ::org::webrtc::JIceCandidateErrorEvent;
#endif

#ifndef _JNI_ZERO_org_webrtc_JMediaConstraints_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaConstraints_DEFINED
namespace org::webrtc {
class _JMediaConstraints : public _jobject {};
using JMediaConstraints = _JMediaConstraints*;
}
#endif

#ifndef _JNI_ZERO_JMediaConstraints_DEFINED
#define _JNI_ZERO_JMediaConstraints_DEFINED
using ::org::webrtc::JMediaConstraints;
#endif

#ifndef _JNI_ZERO_org_webrtc_JMediaStream_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaStream_DEFINED
namespace org::webrtc {
class _JMediaStream : public _jobject {};
using JMediaStream = _JMediaStream*;
}
#endif

#ifndef _JNI_ZERO_JMediaStream_DEFINED
#define _JNI_ZERO_JMediaStream_DEFINED
using ::org::webrtc::JMediaStream;
#endif

#ifndef _JNI_ZERO_org_webrtc_JMediaStreamTrack_MediaType_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaStreamTrack_MediaType_DEFINED
namespace org::webrtc {
class _JMediaStreamTrack_MediaType : public _jobject {};
using JMediaStreamTrack_MediaType = _JMediaStreamTrack_MediaType*;
}
#endif

#ifndef _JNI_ZERO_JMediaStreamTrack_MediaType_DEFINED
#define _JNI_ZERO_JMediaStreamTrack_MediaType_DEFINED
using ::org::webrtc::JMediaStreamTrack_MediaType;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_DEFINED
namespace org::webrtc {
class _JPeerConnection : public _jobject {};
using JPeerConnection = _JPeerConnection*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_DEFINED
#define _JNI_ZERO_JPeerConnection_DEFINED
using ::org::webrtc::JPeerConnection;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_AdapterType_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_AdapterType_DEFINED
namespace org::webrtc {
class _JPeerConnection_AdapterType : public _jobject {};
using JPeerConnection_AdapterType = _JPeerConnection_AdapterType*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_AdapterType_DEFINED
#define _JNI_ZERO_JPeerConnection_AdapterType_DEFINED
using ::org::webrtc::JPeerConnection_AdapterType;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_BundlePolicy_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_BundlePolicy_DEFINED
namespace org::webrtc {
class _JPeerConnection_BundlePolicy : public _jobject {};
using JPeerConnection_BundlePolicy = _JPeerConnection_BundlePolicy*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_BundlePolicy_DEFINED
#define _JNI_ZERO_JPeerConnection_BundlePolicy_DEFINED
using ::org::webrtc::JPeerConnection_BundlePolicy;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_CandidateNetworkPolicy_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_CandidateNetworkPolicy_DEFINED
namespace org::webrtc {
class _JPeerConnection_CandidateNetworkPolicy : public _jobject {};
using JPeerConnection_CandidateNetworkPolicy = _JPeerConnection_CandidateNetworkPolicy*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_CandidateNetworkPolicy_DEFINED
#define _JNI_ZERO_JPeerConnection_CandidateNetworkPolicy_DEFINED
using ::org::webrtc::JPeerConnection_CandidateNetworkPolicy;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_ContinualGatheringPolicy_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_ContinualGatheringPolicy_DEFINED
namespace org::webrtc {
class _JPeerConnection_ContinualGatheringPolicy : public _jobject {};
using JPeerConnection_ContinualGatheringPolicy = _JPeerConnection_ContinualGatheringPolicy*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_ContinualGatheringPolicy_DEFINED
#define _JNI_ZERO_JPeerConnection_ContinualGatheringPolicy_DEFINED
using ::org::webrtc::JPeerConnection_ContinualGatheringPolicy;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_IceConnectionState_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_IceConnectionState_DEFINED
namespace org::webrtc {
class _JPeerConnection_IceConnectionState : public _jobject {};
using JPeerConnection_IceConnectionState = _JPeerConnection_IceConnectionState*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_IceConnectionState_DEFINED
#define _JNI_ZERO_JPeerConnection_IceConnectionState_DEFINED
using ::org::webrtc::JPeerConnection_IceConnectionState;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_IceGatheringState_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_IceGatheringState_DEFINED
namespace org::webrtc {
class _JPeerConnection_IceGatheringState : public _jobject {};
using JPeerConnection_IceGatheringState = _JPeerConnection_IceGatheringState*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_IceGatheringState_DEFINED
#define _JNI_ZERO_JPeerConnection_IceGatheringState_DEFINED
using ::org::webrtc::JPeerConnection_IceGatheringState;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_IceServer_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_IceServer_DEFINED
namespace org::webrtc {
class _JPeerConnection_IceServer : public _jobject {};
using JPeerConnection_IceServer = _JPeerConnection_IceServer*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_IceServer_DEFINED
#define _JNI_ZERO_JPeerConnection_IceServer_DEFINED
using ::org::webrtc::JPeerConnection_IceServer;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_IceTransportsType_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_IceTransportsType_DEFINED
namespace org::webrtc {
class _JPeerConnection_IceTransportsType : public _jobject {};
using JPeerConnection_IceTransportsType = _JPeerConnection_IceTransportsType*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_IceTransportsType_DEFINED
#define _JNI_ZERO_JPeerConnection_IceTransportsType_DEFINED
using ::org::webrtc::JPeerConnection_IceTransportsType;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_KeyType_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_KeyType_DEFINED
namespace org::webrtc {
class _JPeerConnection_KeyType : public _jobject {};
using JPeerConnection_KeyType = _JPeerConnection_KeyType*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_KeyType_DEFINED
#define _JNI_ZERO_JPeerConnection_KeyType_DEFINED
using ::org::webrtc::JPeerConnection_KeyType;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_Observer_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_Observer_DEFINED
namespace org::webrtc {
class _JPeerConnection_Observer : public _jobject {};
using JPeerConnection_Observer = _JPeerConnection_Observer*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_Observer_DEFINED
#define _JNI_ZERO_JPeerConnection_Observer_DEFINED
using ::org::webrtc::JPeerConnection_Observer;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_PeerConnectionState_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_PeerConnectionState_DEFINED
namespace org::webrtc {
class _JPeerConnection_PeerConnectionState : public _jobject {};
using JPeerConnection_PeerConnectionState = _JPeerConnection_PeerConnectionState*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_PeerConnectionState_DEFINED
#define _JNI_ZERO_JPeerConnection_PeerConnectionState_DEFINED
using ::org::webrtc::JPeerConnection_PeerConnectionState;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_PortPrunePolicy_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_PortPrunePolicy_DEFINED
namespace org::webrtc {
class _JPeerConnection_PortPrunePolicy : public _jobject {};
using JPeerConnection_PortPrunePolicy = _JPeerConnection_PortPrunePolicy*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_PortPrunePolicy_DEFINED
#define _JNI_ZERO_JPeerConnection_PortPrunePolicy_DEFINED
using ::org::webrtc::JPeerConnection_PortPrunePolicy;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_RTCConfiguration_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_RTCConfiguration_DEFINED
namespace org::webrtc {
class _JPeerConnection_RTCConfiguration : public _jobject {};
using JPeerConnection_RTCConfiguration = _JPeerConnection_RTCConfiguration*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_RTCConfiguration_DEFINED
#define _JNI_ZERO_JPeerConnection_RTCConfiguration_DEFINED
using ::org::webrtc::JPeerConnection_RTCConfiguration;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_RtcpMuxPolicy_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_RtcpMuxPolicy_DEFINED
namespace org::webrtc {
class _JPeerConnection_RtcpMuxPolicy : public _jobject {};
using JPeerConnection_RtcpMuxPolicy = _JPeerConnection_RtcpMuxPolicy*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_RtcpMuxPolicy_DEFINED
#define _JNI_ZERO_JPeerConnection_RtcpMuxPolicy_DEFINED
using ::org::webrtc::JPeerConnection_RtcpMuxPolicy;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_SdpSemantics_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_SdpSemantics_DEFINED
namespace org::webrtc {
class _JPeerConnection_SdpSemantics : public _jobject {};
using JPeerConnection_SdpSemantics = _JPeerConnection_SdpSemantics*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_SdpSemantics_DEFINED
#define _JNI_ZERO_JPeerConnection_SdpSemantics_DEFINED
using ::org::webrtc::JPeerConnection_SdpSemantics;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_SignalingState_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_SignalingState_DEFINED
namespace org::webrtc {
class _JPeerConnection_SignalingState : public _jobject {};
using JPeerConnection_SignalingState = _JPeerConnection_SignalingState*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_SignalingState_DEFINED
#define _JNI_ZERO_JPeerConnection_SignalingState_DEFINED
using ::org::webrtc::JPeerConnection_SignalingState;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_TcpCandidatePolicy_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_TcpCandidatePolicy_DEFINED
namespace org::webrtc {
class _JPeerConnection_TcpCandidatePolicy : public _jobject {};
using JPeerConnection_TcpCandidatePolicy = _JPeerConnection_TcpCandidatePolicy*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_TcpCandidatePolicy_DEFINED
#define _JNI_ZERO_JPeerConnection_TcpCandidatePolicy_DEFINED
using ::org::webrtc::JPeerConnection_TcpCandidatePolicy;
#endif

#ifndef _JNI_ZERO_org_webrtc_JPeerConnection_TlsCertPolicy_DEFINED
#define _JNI_ZERO_org_webrtc_JPeerConnection_TlsCertPolicy_DEFINED
namespace org::webrtc {
class _JPeerConnection_TlsCertPolicy : public _jobject {};
using JPeerConnection_TlsCertPolicy = _JPeerConnection_TlsCertPolicy*;
}
#endif

#ifndef _JNI_ZERO_JPeerConnection_TlsCertPolicy_DEFINED
#define _JNI_ZERO_JPeerConnection_TlsCertPolicy_DEFINED
using ::org::webrtc::JPeerConnection_TlsCertPolicy;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRTCStatsCollectorCallback_DEFINED
#define _JNI_ZERO_org_webrtc_JRTCStatsCollectorCallback_DEFINED
namespace org::webrtc {
class _JRTCStatsCollectorCallback : public _jobject {};
using JRTCStatsCollectorCallback = _JRTCStatsCollectorCallback*;
}
#endif

#ifndef _JNI_ZERO_JRTCStatsCollectorCallback_DEFINED
#define _JNI_ZERO_JRTCStatsCollectorCallback_DEFINED
using ::org::webrtc::JRTCStatsCollectorCallback;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtcCertificatePem_DEFINED
#define _JNI_ZERO_org_webrtc_JRtcCertificatePem_DEFINED
namespace org::webrtc {
class _JRtcCertificatePem : public _jobject {};
using JRtcCertificatePem = _JRtcCertificatePem*;
}
#endif

#ifndef _JNI_ZERO_JRtcCertificatePem_DEFINED
#define _JNI_ZERO_JRtcCertificatePem_DEFINED
using ::org::webrtc::JRtcCertificatePem;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpReceiver_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpReceiver_DEFINED
namespace org::webrtc {
class _JRtpReceiver : public _jobject {};
using JRtpReceiver = _JRtpReceiver*;
}
#endif

#ifndef _JNI_ZERO_JRtpReceiver_DEFINED
#define _JNI_ZERO_JRtpReceiver_DEFINED
using ::org::webrtc::JRtpReceiver;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpSender_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpSender_DEFINED
namespace org::webrtc {
class _JRtpSender : public _jobject {};
using JRtpSender = _JRtpSender*;
}
#endif

#ifndef _JNI_ZERO_JRtpSender_DEFINED
#define _JNI_ZERO_JRtpSender_DEFINED
using ::org::webrtc::JRtpSender;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpTransceiver_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpTransceiver_DEFINED
namespace org::webrtc {
class _JRtpTransceiver : public _jobject {};
using JRtpTransceiver = _JRtpTransceiver*;
}
#endif

#ifndef _JNI_ZERO_JRtpTransceiver_DEFINED
#define _JNI_ZERO_JRtpTransceiver_DEFINED
using ::org::webrtc::JRtpTransceiver;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpTransceiver_RtpTransceiverInit_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpTransceiver_RtpTransceiverInit_DEFINED
namespace org::webrtc {
class _JRtpTransceiver_RtpTransceiverInit : public _jobject {};
using JRtpTransceiver_RtpTransceiverInit = _JRtpTransceiver_RtpTransceiverInit*;
}
#endif

#ifndef _JNI_ZERO_JRtpTransceiver_RtpTransceiverInit_DEFINED
#define _JNI_ZERO_JRtpTransceiver_RtpTransceiverInit_DEFINED
using ::org::webrtc::JRtpTransceiver_RtpTransceiverInit;
#endif

#ifndef _JNI_ZERO_org_webrtc_JSdpObserver_DEFINED
#define _JNI_ZERO_org_webrtc_JSdpObserver_DEFINED
namespace org::webrtc {
class _JSdpObserver : public _jobject {};
using JSdpObserver = _JSdpObserver*;
}
#endif

#ifndef _JNI_ZERO_JSdpObserver_DEFINED
#define _JNI_ZERO_JSdpObserver_DEFINED
using ::org::webrtc::JSdpObserver;
#endif

#ifndef _JNI_ZERO_org_webrtc_JSessionDescription_DEFINED
#define _JNI_ZERO_org_webrtc_JSessionDescription_DEFINED
namespace org::webrtc {
class _JSessionDescription : public _jobject {};
using JSessionDescription = _JSessionDescription*;
}
#endif

#ifndef _JNI_ZERO_JSessionDescription_DEFINED
#define _JNI_ZERO_JSessionDescription_DEFINED
using ::org::webrtc::JSessionDescription;
#endif

#ifndef _JNI_ZERO_org_webrtc_JStatsObserver_DEFINED
#define _JNI_ZERO_org_webrtc_JStatsObserver_DEFINED
namespace org::webrtc {
class _JStatsObserver : public _jobject {};
using JStatsObserver = _JStatsObserver*;
}
#endif

#ifndef _JNI_ZERO_JStatsObserver_DEFINED
#define _JNI_ZERO_JStatsObserver_DEFINED
using ::org::webrtc::JStatsObserver;
#endif

#ifndef _JNI_ZERO_org_webrtc_JTurnCustomizer_DEFINED
#define _JNI_ZERO_org_webrtc_JTurnCustomizer_DEFINED
namespace org::webrtc {
class _JTurnCustomizer : public _jobject {};
using JTurnCustomizer = _JTurnCustomizer*;
}
#endif

#ifndef _JNI_ZERO_JTurnCustomizer_DEFINED
#define _JNI_ZERO_JTurnCustomizer_DEFINED
using ::org::webrtc::JTurnCustomizer;
#endif


#endif  // org_webrtc_PeerConnection_SHARED_JNI
