// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RTCStatsReport

#ifndef org_webrtc_RTCStatsReport_JNI
#define org_webrtc_RTCStatsReport_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "RTCStatsReport_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_RTCStatsReport()

// Class Accessors
#ifndef org_webrtc_RTCStatsReport_clazz_defined
#define org_webrtc_RTCStatsReport_clazz_defined
inline jclass org_webrtc_RTCStatsReport_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.RTCStatsReport";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_RTCStatsReport_create(
    JNIEnv* env,
    int64_t timestampUs,
    const ::jni_zero::JavaRef<jobject>& stats) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RTCStatsReport_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "create",
      "(JLjava/util/Map;)Lorg/webrtc/RTCStatsReport;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      timestampUs,
      stats.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JRTCStatsReport> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JRTCStatsReport> create(
      JNIEnv* env,
      int64_t timestampUs,
      const ::jni_zero::JavaRef<::java::util::JMap>& stats) {
    return Java_RTCStatsReport_create(env, timestampUs, stats)
        .As<::org::webrtc::JRTCStatsReport>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using RTCStatsReportJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JRTCStatsReport>;
}
#ifndef _JNI_ZERO_RTCStatsReportJni_DEFINED
#define _JNI_ZERO_RTCStatsReportJni_DEFINED
using ::org::webrtc::RTCStatsReportJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_RTCStatsReport_JNI
