// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RTCStats

#ifndef org_webrtc_RTCStats_SHARED_JNI
#define org_webrtc_RTCStats_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_util_JMap_DEFINED
#define _JNI_ZERO_java_util_JMap_DEFINED
namespace java::util {
class _JMap : public _jobject {};
using JMap = _JMap*;
}
#endif

#ifndef _JNI_ZERO_JMap_DEFINED
#define _JNI_ZERO_JMap_DEFINED
using ::java::util::JMap;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRTCStats_DEFINED
#define _JNI_ZERO_org_webrtc_JRTCStats_DEFINED
namespace org::webrtc {
class _JRTCStats : public _jobject {};
using JRTCStats = _JRTCStats*;
}
#endif

#ifndef _JNI_ZERO_JRTCStats_DEFINED
#define _JNI_ZERO_JRTCStats_DEFINED
using ::org::webrtc::JRTCStats;
#endif


#endif  // org_webrtc_RTCStats_SHARED_JNI
