// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RtpCapabilities

#ifndef org_webrtc_RtpCapabilities_SHARED_JNI
#define org_webrtc_RtpCapabilities_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JInteger_DEFINED
#define _JNI_ZERO_java_lang_JInteger_DEFINED
namespace java::lang {
class _JInteger : public _jobject {};
using JInteger = _JInteger*;
}
#endif

#ifndef _JNI_ZERO_JInteger_DEFINED
#define _JNI_ZERO_JInteger_DEFINED
using ::java::lang::JInteger;
#endif

#ifndef _JNI_ZERO_java_util_JList_DEFINED
#define _JNI_ZERO_java_util_JList_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JList : public _jobject {};
template <typename T>
using JList = _JList<T>*;
}
#endif

#ifndef _JNI_ZERO_JList_DEFINED
#define _JNI_ZERO_JList_DEFINED
using ::java::util::JList;
#endif

#ifndef _JNI_ZERO_java_util_JMap_DEFINED
#define _JNI_ZERO_java_util_JMap_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2>
class _JMap : public _jobject {};
template <typename T1, typename T2>
using JMap = _JMap<T1, T2>*;
}
#endif

#ifndef _JNI_ZERO_JMap_DEFINED
#define _JNI_ZERO_JMap_DEFINED
using ::java::util::JMap;
#endif

#ifndef _JNI_ZERO_org_webrtc_JMediaStreamTrack_MediaType_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaStreamTrack_MediaType_DEFINED
namespace org::webrtc {
class _JMediaStreamTrack_MediaType : public _jobject {};
using JMediaStreamTrack_MediaType = _JMediaStreamTrack_MediaType*;
}
#endif

#ifndef _JNI_ZERO_JMediaStreamTrack_MediaType_DEFINED
#define _JNI_ZERO_JMediaStreamTrack_MediaType_DEFINED
using ::org::webrtc::JMediaStreamTrack_MediaType;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpCapabilities_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpCapabilities_DEFINED
namespace org::webrtc {
class _JRtpCapabilities : public _jobject {};
using JRtpCapabilities = _JRtpCapabilities*;
}
#endif

#ifndef _JNI_ZERO_JRtpCapabilities_DEFINED
#define _JNI_ZERO_JRtpCapabilities_DEFINED
using ::org::webrtc::JRtpCapabilities;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpCapabilities_CodecCapability_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpCapabilities_CodecCapability_DEFINED
namespace org::webrtc {
class _JRtpCapabilities_CodecCapability : public _jobject {};
using JRtpCapabilities_CodecCapability = _JRtpCapabilities_CodecCapability*;
}
#endif

#ifndef _JNI_ZERO_JRtpCapabilities_CodecCapability_DEFINED
#define _JNI_ZERO_JRtpCapabilities_CodecCapability_DEFINED
using ::org::webrtc::JRtpCapabilities_CodecCapability;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpCapabilities_HeaderExtensionCapability_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpCapabilities_HeaderExtensionCapability_DEFINED
namespace org::webrtc {
class _JRtpCapabilities_HeaderExtensionCapability : public _jobject {};
using JRtpCapabilities_HeaderExtensionCapability = _JRtpCapabilities_HeaderExtensionCapability*;
}
#endif

#ifndef _JNI_ZERO_JRtpCapabilities_HeaderExtensionCapability_DEFINED
#define _JNI_ZERO_JRtpCapabilities_HeaderExtensionCapability_DEFINED
using ::org::webrtc::JRtpCapabilities_HeaderExtensionCapability;
#endif


#endif  // org_webrtc_RtpCapabilities_SHARED_JNI
