// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RtpCapabilities

#ifndef org_webrtc_RtpCapabilities_JNI
#define org_webrtc_RtpCapabilities_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "RtpCapabilities_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_RtpCapabilities()

// Class Accessors
#ifndef org_webrtc_RtpCapabilities_clazz_defined
#define org_webrtc_RtpCapabilities_clazz_defined
inline jclass org_webrtc_RtpCapabilities_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.RtpCapabilities";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_RtpCapabilities_00024CodecCapability_clazz_defined
#define org_webrtc_RtpCapabilities_00024CodecCapability_clazz_defined
inline jclass org_webrtc_RtpCapabilities_00024CodecCapability_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.RtpCapabilities$CodecCapability";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_RtpCapabilities_00024HeaderExtensionCapability_clazz_defined
#define org_webrtc_RtpCapabilities_00024HeaderExtensionCapability_clazz_defined
inline jclass org_webrtc_RtpCapabilities_00024HeaderExtensionCapability_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.RtpCapabilities$HeaderExtensionCapability";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_RtpCapabilities_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& codecs,
    const ::jni_zero::JavaRef<jobject>& headerExtensions) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/util/List;Ljava/util/List;)V",
      &cached_method_id);
  auto _ret = env->NewObject(
      clazz,
      call_context.method_id(),
      codecs.obj(),
      headerExtensions.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_RtpCapabilities_getCodecs(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getCodecs",
      "()Ljava/util/List;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_RtpCapabilities_getHeaderExtensions(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getHeaderExtensions",
      "()Ljava/util/List;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_CodecCapability_Constructor(
    JNIEnv* env,
    JniIntWrapper preferredPayloadType,
    const ::jni_zero::JavaRef<jstring>& name,
    const ::jni_zero::JavaRef<jobject>& kind,
    const ::jni_zero::JavaRef<jobject>& clockRate,
    const ::jni_zero::JavaRef<jobject>& numChannels,
    const ::jni_zero::JavaRef<jstring>& mimeType,
    const ::jni_zero::JavaRef<jobject>& parameters) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024CodecCapability_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(ILjava/lang/String;Lorg/webrtc/MediaStreamTrack$MediaType;Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/String;Ljava/util/Map;)V",
      &cached_method_id);
  auto _ret = env->NewObject(
      clazz,
      call_context.method_id(),
      as_jint(preferredPayloadType),
      name.obj(),
      kind.obj(),
      clockRate.obj(),
      numChannels.obj(),
      mimeType.obj(),
      parameters.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_CodecCapability_getClockRate(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024CodecCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getClockRate",
      "()Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_CodecCapability_getKind(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024CodecCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getKind",
      "()Lorg/webrtc/MediaStreamTrack$MediaType;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jstring> Java_CodecCapability_getName(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024CodecCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getName",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_CodecCapability_getNumChannels(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024CodecCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getNumChannels",
      "()Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_CodecCapability_getParameters(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024CodecCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getParameters",
      "()Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static int32_t Java_CodecCapability_getPreferredPayloadType(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024CodecCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getPreferredPayloadType",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_HeaderExtensionCapability_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& uri,
    JniIntWrapper preferredId,
    bool preferredEncrypted) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024HeaderExtensionCapability_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;IZ)V",
      &cached_method_id);
  auto _ret = env->NewObject(
      clazz,
      call_context.method_id(),
      uri.obj(),
      as_jint(preferredId),
      preferredEncrypted);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static bool Java_HeaderExtensionCapability_getPreferredEncrypted(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024HeaderExtensionCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getPreferredEncrypted",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_HeaderExtensionCapability_getPreferredId(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024HeaderExtensionCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getPreferredId",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static ::jni_zero::ScopedJavaLocalRef<jstring> Java_HeaderExtensionCapability_getUri(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpCapabilities_00024HeaderExtensionCapability_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getUri",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JRtpCapabilities> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JRtpCapabilities> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::JList<::org::webrtc::JRtpCapabilities_CodecCapability>>& codecs,
      const ::jni_zero::JavaRef<::java::util::JList<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability>>& headerExtensions) {
    return Java_RtpCapabilities_Constructor(env, codecs, headerExtensions)
        .As<::org::webrtc::JRtpCapabilities>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JRtpCapabilities> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::java::util::JList<::org::webrtc::JRtpCapabilities_CodecCapability>> getCodecs(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities>*>(this);
    return Java_RtpCapabilities_getCodecs(env, *this_obj)
        .As<::java::util::JList<::org::webrtc::JRtpCapabilities_CodecCapability>>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JList<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability>> getHeaderExtensions(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities>*>(this);
    return Java_RtpCapabilities_getHeaderExtensions(env, *this_obj)
        .As<::java::util::JList<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability>>();
  }

};

template<>
class _CalledByNativesStatics<::org::webrtc::JRtpCapabilities_CodecCapability> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JRtpCapabilities_CodecCapability> New(
      JNIEnv* env,
      JniIntWrapper preferredPayloadType,
      const ::jni_zero::JavaRef<jstring>& name,
      const ::jni_zero::JavaRef<::org::webrtc::JMediaStreamTrack_MediaType>& kind,
      const ::jni_zero::JavaRef<::java::lang::JInteger>& clockRate,
      const ::jni_zero::JavaRef<::java::lang::JInteger>& numChannels,
      const ::jni_zero::JavaRef<jstring>& mimeType,
      const ::jni_zero::JavaRef<::java::util::JMap<jstring, jstring>>& parameters) {
    return Java_CodecCapability_Constructor(
        env,
        preferredPayloadType,
        name,
        kind,
        clockRate,
        numChannels,
        mimeType,
        parameters)
        .As<::org::webrtc::JRtpCapabilities_CodecCapability>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JRtpCapabilities_CodecCapability> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> getClockRate(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_CodecCapability>*>(this);
    return Java_CodecCapability_getClockRate(env, *this_obj)
        .As<::java::lang::JInteger>();
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JMediaStreamTrack_MediaType> getKind(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_CodecCapability>*>(this);
    return Java_CodecCapability_getKind(env, *this_obj)
        .As<::org::webrtc::JMediaStreamTrack_MediaType>();
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> getName(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_CodecCapability>*>(this);
    return Java_CodecCapability_getName(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> getNumChannels(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_CodecCapability>*>(this);
    return Java_CodecCapability_getNumChannels(env, *this_obj)
        .As<::java::lang::JInteger>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<jstring, jstring>> getParameters(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_CodecCapability>*>(this);
    return Java_CodecCapability_getParameters(env, *this_obj)
        .As<::java::util::JMap<jstring, jstring>>();
  }

  int32_t getPreferredPayloadType(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_CodecCapability>*>(this);
    return Java_CodecCapability_getPreferredPayloadType(env, *this_obj);
  }

};

template<>
class _CalledByNativesStatics<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& uri,
      JniIntWrapper preferredId,
      bool preferredEncrypted) {
    return Java_HeaderExtensionCapability_Constructor(env, uri, preferredId, preferredEncrypted)
        .As<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability> {
  public:
  bool getPreferredEncrypted(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability>*>(this);
    return Java_HeaderExtensionCapability_getPreferredEncrypted(env, *this_obj);
  }

  int32_t getPreferredId(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability>*>(this);
    return Java_HeaderExtensionCapability_getPreferredId(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> getUri(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability>*>(this);
    return Java_HeaderExtensionCapability_getUri(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using RtpCapabilitiesJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JRtpCapabilities>;
}
#ifndef _JNI_ZERO_RtpCapabilitiesJni_DEFINED
#define _JNI_ZERO_RtpCapabilitiesJni_DEFINED
using ::org::webrtc::RtpCapabilitiesJni;
#endif

namespace org::webrtc {
using RtpCapabilities_CodecCapabilityJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JRtpCapabilities_CodecCapability>;
}
#ifndef _JNI_ZERO_RtpCapabilities_CodecCapabilityJni_DEFINED
#define _JNI_ZERO_RtpCapabilities_CodecCapabilityJni_DEFINED
using ::org::webrtc::RtpCapabilities_CodecCapabilityJni;
#endif

namespace org::webrtc {
using RtpCapabilities_HeaderExtensionCapabilityJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JRtpCapabilities_HeaderExtensionCapability>;
}
#ifndef _JNI_ZERO_RtpCapabilities_HeaderExtensionCapabilityJni_DEFINED
#define _JNI_ZERO_RtpCapabilities_HeaderExtensionCapabilityJni_DEFINED
using ::org::webrtc::RtpCapabilities_HeaderExtensionCapabilityJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_RtpCapabilities_JNI
