// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RtpParameters

#ifndef org_webrtc_RtpParameters_SHARED_JNI
#define org_webrtc_RtpParameters_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JDouble_DEFINED
#define _JNI_ZERO_java_lang_JDouble_DEFINED
namespace java::lang {
class _JDouble : public _jobject {};
using JDouble = _JDouble*;
}
#endif

#ifndef _JNI_ZERO_JDouble_DEFINED
#define _JNI_ZERO_JDouble_DEFINED
using ::java::lang::JDouble;
#endif

#ifndef _JNI_ZERO_java_lang_JInteger_DEFINED
#define _JNI_ZERO_java_lang_JInteger_DEFINED
namespace java::lang {
class _JInteger : public _jobject {};
using JInteger = _JInteger*;
}
#endif

#ifndef _JNI_ZERO_JInteger_DEFINED
#define _JNI_ZERO_JInteger_DEFINED
using ::java::lang::JInteger;
#endif

#ifndef _JNI_ZERO_java_lang_JLong_DEFINED
#define _JNI_ZERO_java_lang_JLong_DEFINED
namespace java::lang {
class _JLong : public _jobject {};
using JLong = _JLong*;
}
#endif

#ifndef _JNI_ZERO_JLong_DEFINED
#define _JNI_ZERO_JLong_DEFINED
using ::java::lang::JLong;
#endif

#ifndef _JNI_ZERO_java_util_JList_DEFINED
#define _JNI_ZERO_java_util_JList_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JList : public _jobject {};
template <typename T>
using JList = _JList<T>*;
}
#endif

#ifndef _JNI_ZERO_JList_DEFINED
#define _JNI_ZERO_JList_DEFINED
using ::java::util::JList;
#endif

#ifndef _JNI_ZERO_java_util_JMap_DEFINED
#define _JNI_ZERO_java_util_JMap_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2>
class _JMap : public _jobject {};
template <typename T1, typename T2>
using JMap = _JMap<T1, T2>*;
}
#endif

#ifndef _JNI_ZERO_JMap_DEFINED
#define _JNI_ZERO_JMap_DEFINED
using ::java::util::JMap;
#endif

#ifndef _JNI_ZERO_org_webrtc_JMediaStreamTrack_MediaType_DEFINED
#define _JNI_ZERO_org_webrtc_JMediaStreamTrack_MediaType_DEFINED
namespace org::webrtc {
class _JMediaStreamTrack_MediaType : public _jobject {};
using JMediaStreamTrack_MediaType = _JMediaStreamTrack_MediaType*;
}
#endif

#ifndef _JNI_ZERO_JMediaStreamTrack_MediaType_DEFINED
#define _JNI_ZERO_JMediaStreamTrack_MediaType_DEFINED
using ::org::webrtc::JMediaStreamTrack_MediaType;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpParameters_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpParameters_DEFINED
namespace org::webrtc {
class _JRtpParameters : public _jobject {};
using JRtpParameters = _JRtpParameters*;
}
#endif

#ifndef _JNI_ZERO_JRtpParameters_DEFINED
#define _JNI_ZERO_JRtpParameters_DEFINED
using ::org::webrtc::JRtpParameters;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpParameters_Codec_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpParameters_Codec_DEFINED
namespace org::webrtc {
class _JRtpParameters_Codec : public _jobject {};
using JRtpParameters_Codec = _JRtpParameters_Codec*;
}
#endif

#ifndef _JNI_ZERO_JRtpParameters_Codec_DEFINED
#define _JNI_ZERO_JRtpParameters_Codec_DEFINED
using ::org::webrtc::JRtpParameters_Codec;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpParameters_DegradationPreference_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpParameters_DegradationPreference_DEFINED
namespace org::webrtc {
class _JRtpParameters_DegradationPreference : public _jobject {};
using JRtpParameters_DegradationPreference = _JRtpParameters_DegradationPreference*;
}
#endif

#ifndef _JNI_ZERO_JRtpParameters_DegradationPreference_DEFINED
#define _JNI_ZERO_JRtpParameters_DegradationPreference_DEFINED
using ::org::webrtc::JRtpParameters_DegradationPreference;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpParameters_Encoding_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpParameters_Encoding_DEFINED
namespace org::webrtc {
class _JRtpParameters_Encoding : public _jobject {};
using JRtpParameters_Encoding = _JRtpParameters_Encoding*;
}
#endif

#ifndef _JNI_ZERO_JRtpParameters_Encoding_DEFINED
#define _JNI_ZERO_JRtpParameters_Encoding_DEFINED
using ::org::webrtc::JRtpParameters_Encoding;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpParameters_HeaderExtension_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpParameters_HeaderExtension_DEFINED
namespace org::webrtc {
class _JRtpParameters_HeaderExtension : public _jobject {};
using JRtpParameters_HeaderExtension = _JRtpParameters_HeaderExtension*;
}
#endif

#ifndef _JNI_ZERO_JRtpParameters_HeaderExtension_DEFINED
#define _JNI_ZERO_JRtpParameters_HeaderExtension_DEFINED
using ::org::webrtc::JRtpParameters_HeaderExtension;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpParameters_Rtcp_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpParameters_Rtcp_DEFINED
namespace org::webrtc {
class _JRtpParameters_Rtcp : public _jobject {};
using JRtpParameters_Rtcp = _JRtpParameters_Rtcp*;
}
#endif

#ifndef _JNI_ZERO_JRtpParameters_Rtcp_DEFINED
#define _JNI_ZERO_JRtpParameters_Rtcp_DEFINED
using ::org::webrtc::JRtpParameters_Rtcp;
#endif


#endif  // org_webrtc_RtpParameters_SHARED_JNI
