// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RtpReceiver

#ifndef org_webrtc_RtpReceiver_JNI
#define org_webrtc_RtpReceiver_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "RtpReceiver_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static jni_zero::ScopedJavaLocalRef<jstring> JNI_RtpReceiver_GetId(
//     JNIEnv* env,
//     int64_t rtpReceiver);
//
// static jni_zero::ScopedJavaLocalRef<::org::webrtc::JRtpParameters> JNI_RtpReceiver_GetParameters(
//     JNIEnv* env,
//     int64_t rtpReceiver);
//
// static int64_t JNI_RtpReceiver_GetTrack(JNIEnv* env, int64_t rtpReceiver);
//
// static void JNI_RtpReceiver_SetFrameDecryptor(
//     JNIEnv* env,
//     int64_t rtpReceiver,
//     int64_t nativeFrameDecryptor);
//
// static int64_t JNI_RtpReceiver_SetObserver(
//     JNIEnv* env,
//     int64_t rtpReceiver,
//     const jni_zero::JavaRef<::org::webrtc::JRtpReceiver_Observer>& observer);
//
// static void JNI_RtpReceiver_UnsetObserver(
//     JNIEnv* env,
//     int64_t rtpReceiver,
//     int64_t nativeObserver);
//

// Triggers a compiler warning if DEFINE_JNI(RtpReceiver) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_RtpReceiver() {}

// Java to native functions
#define DEFINE_JNI_FOR_RtpReceiver()                                                               \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT jobject Java_J_N_M7739WsR(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t rtpReceiver) {                                                                       \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_RtpReceiver();                                                 \
                                                                                                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_RtpReceiver_GetId(std::forward<decltype(args)>(args)...)) {                     \
        return JNI_RtpReceiver_GetId(std::forward<decltype(args)>(args)...);                       \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, rtpReceiver); }) {                                \
        return func_wrapper(env, rtpReceiver);                                                     \
      } else if constexpr (requires { func_wrapper(rtpReceiver); }) {                              \
        return func_wrapper(rtpReceiver);                                                          \
      } else {                                                                                     \
        static_assert(false, "JNI_RtpReceiver_GetId() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/RtpReceiver_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value.ReleaseLocal();                                                            \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT jobject Java_J_N_M5LU7owI(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t rtpReceiver) {                                                                       \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_RtpReceiver_GetParameters(std::forward<decltype(args)>(args)...)) {             \
        return JNI_RtpReceiver_GetParameters(std::forward<decltype(args)>(args)...);               \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, rtpReceiver); }) {                                \
        return func_wrapper(env, rtpReceiver);                                                     \
      } else if constexpr (requires { func_wrapper(rtpReceiver); }) {                              \
        return func_wrapper(rtpReceiver);                                                          \
      } else {                                                                                     \
        static_assert(false, "JNI_RtpReceiver_GetParameters() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/RtpReceiver_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value.ReleaseLocal();                                                            \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT int64_t Java_J_N_MvKLRSA0(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t rtpReceiver) {                                                                       \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_RtpReceiver_GetTrack(std::forward<decltype(args)>(args)...)) {                  \
        return JNI_RtpReceiver_GetTrack(std::forward<decltype(args)>(args)...);                    \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, rtpReceiver); }) {                                \
        return func_wrapper(env, rtpReceiver);                                                     \
      } else if constexpr (requires { func_wrapper(rtpReceiver); }) {                              \
        return func_wrapper(rtpReceiver);                                                          \
      } else {                                                                                     \
        static_assert(false, "JNI_RtpReceiver_GetTrack() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/RtpReceiver_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_MUS8_1Wc2(                                                \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t rtpReceiver,                                                                         \
      int64_t nativeFrameDecryptor) {                                                              \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_RtpReceiver_SetFrameDecryptor(std::forward<decltype(args)>(args)...)) {         \
        return JNI_RtpReceiver_SetFrameDecryptor(std::forward<decltype(args)>(args)...);           \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, rtpReceiver, nativeFrameDecryptor); }) {          \
        return func_wrapper(env, rtpReceiver, nativeFrameDecryptor);                               \
      } else if constexpr (requires { func_wrapper(rtpReceiver, nativeFrameDecryptor); }) {        \
        return func_wrapper(rtpReceiver, nativeFrameDecryptor);                                    \
      } else {                                                                                     \
        static_assert(false, "JNI_RtpReceiver_SetFrameDecryptor() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/RtpReceiver_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT int64_t Java_J_N_Mc1yUPoU(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t rtpReceiver,                                                                         \
      jobject observer) {                                                                          \
    auto observer_ref = jni_zero::JavaRef<::org::webrtc::JRtpReceiver_Observer>::CreateLeaky(env,  \
        static_cast<::org::webrtc::JRtpReceiver_Observer>(observer));                              \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_RtpReceiver_SetObserver(std::forward<decltype(args)>(args)...)) {               \
        return JNI_RtpReceiver_SetObserver(std::forward<decltype(args)>(args)...);                 \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, rtpReceiver, observer_ref); }) {                  \
        return func_wrapper(env, rtpReceiver, observer_ref);                                       \
      } else if constexpr (requires { func_wrapper(rtpReceiver, observer_ref); }) {                \
        return func_wrapper(rtpReceiver, observer_ref);                                            \
      } else {                                                                                     \
        static_assert(false, "JNI_RtpReceiver_SetObserver() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, const jni_zero::JavaRef<JRtpReceiver_Observer>&)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/RtpReceiver_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_M8reqV0J(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t rtpReceiver,                                                                         \
      int64_t nativeObserver) {                                                                    \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_RtpReceiver_UnsetObserver(std::forward<decltype(args)>(args)...)) {             \
        return JNI_RtpReceiver_UnsetObserver(std::forward<decltype(args)>(args)...);               \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, rtpReceiver, nativeObserver); }) {                \
        return func_wrapper(env, rtpReceiver, nativeObserver);                                     \
      } else if constexpr (requires { func_wrapper(rtpReceiver, nativeObserver); }) {              \
        return func_wrapper(rtpReceiver, nativeObserver);                                          \
      } else {                                                                                     \
        static_assert(false, "JNI_RtpReceiver_UnsetObserver() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, int64_t)\nSee gen/jni_headers/sdk/android/generated_peerconnection_jni/RtpReceiver_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

// Class Accessors
#ifndef org_webrtc_RtpReceiver_clazz_defined
#define org_webrtc_RtpReceiver_clazz_defined
inline jclass org_webrtc_RtpReceiver_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.RtpReceiver";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_RtpReceiver_00024Observer_clazz_defined
#define org_webrtc_RtpReceiver_00024Observer_clazz_defined
inline jclass org_webrtc_RtpReceiver_00024Observer_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.RtpReceiver$Observer";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_RtpReceiver_Constructor(
    JNIEnv* env,
    int64_t nativeRtpReceiver) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpReceiver_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(J)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), nativeRtpReceiver);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static void Java_RtpReceiver_dispose(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpReceiver_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "dispose",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

static void Java_Observer_onFirstPacketReceived(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& media_type) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpReceiver_00024Observer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onFirstPacketReceived",
      "(Lorg/webrtc/MediaStreamTrack$MediaType;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), media_type.obj());
}

static void Java_Observer_onFirstPacketReceivedAfterReceptiveChange(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& media_type) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_RtpReceiver_00024Observer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onFirstPacketReceivedAfterReceptiveChange",
      "(Lorg/webrtc/MediaStreamTrack$MediaType;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), media_type.obj());
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JRtpReceiver> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JRtpReceiver> New(
      JNIEnv* env,
      int64_t nativeRtpReceiver) {
    return Java_RtpReceiver_Constructor(env, nativeRtpReceiver)
        .As<::org::webrtc::JRtpReceiver>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JRtpReceiver> {
  public:
  void dispose(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpReceiver>*>(this);
    Java_RtpReceiver_dispose(env, *this_obj);
  }

};

template<>
class _CalledByNatives<::org::webrtc::JRtpReceiver_Observer> {
  public:
  void onFirstPacketReceived(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JMediaStreamTrack_MediaType>& media_type) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpReceiver_Observer>*>(this);
    Java_Observer_onFirstPacketReceived(env, *this_obj, media_type);
  }

  void onFirstPacketReceivedAfterReceptiveChange(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JMediaStreamTrack_MediaType>& media_type) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JRtpReceiver_Observer>*>(this);
    Java_Observer_onFirstPacketReceivedAfterReceptiveChange(env, *this_obj, media_type);
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using RtpReceiverJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JRtpReceiver>;
}
#ifndef _JNI_ZERO_RtpReceiverJni_DEFINED
#define _JNI_ZERO_RtpReceiverJni_DEFINED
using ::org::webrtc::RtpReceiverJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_RtpReceiver_JNI
