// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.RtpSender

#ifndef org_webrtc_RtpSender_SHARED_JNI
#define org_webrtc_RtpSender_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_util_JList_DEFINED
#define _JNI_ZERO_java_util_JList_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JList : public _jobject {};
template <typename T>
using JList = _JList<T>*;
}
#endif

#ifndef _JNI_ZERO_JList_DEFINED
#define _JNI_ZERO_JList_DEFINED
using ::java::util::JList;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpParameters_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpParameters_DEFINED
namespace org::webrtc {
class _JRtpParameters : public _jobject {};
using JRtpParameters = _JRtpParameters*;
}
#endif

#ifndef _JNI_ZERO_JRtpParameters_DEFINED
#define _JNI_ZERO_JRtpParameters_DEFINED
using ::org::webrtc::JRtpParameters;
#endif

#ifndef _JNI_ZERO_org_webrtc_JRtpSender_DEFINED
#define _JNI_ZERO_org_webrtc_JRtpSender_DEFINED
namespace org::webrtc {
class _JRtpSender : public _jobject {};
using JRtpSender = _JRtpSender*;
}
#endif

#ifndef _JNI_ZERO_JRtpSender_DEFINED
#define _JNI_ZERO_JRtpSender_DEFINED
using ::org::webrtc::JRtpSender;
#endif


#endif  // org_webrtc_RtpSender_SHARED_JNI
