// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.SdpObserver

#ifndef org_webrtc_SdpObserver_SHARED_JNI
#define org_webrtc_SdpObserver_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JSdpObserver_DEFINED
#define _JNI_ZERO_org_webrtc_JSdpObserver_DEFINED
namespace org::webrtc {
class _JSdpObserver : public _jobject {};
using JSdpObserver = _JSdpObserver*;
}
#endif

#ifndef _JNI_ZERO_JSdpObserver_DEFINED
#define _JNI_ZERO_JSdpObserver_DEFINED
using ::org::webrtc::JSdpObserver;
#endif

#ifndef _JNI_ZERO_org_webrtc_JSessionDescription_DEFINED
#define _JNI_ZERO_org_webrtc_JSessionDescription_DEFINED
namespace org::webrtc {
class _JSessionDescription : public _jobject {};
using JSessionDescription = _JSessionDescription*;
}
#endif

#ifndef _JNI_ZERO_JSessionDescription_DEFINED
#define _JNI_ZERO_JSessionDescription_DEFINED
using ::org::webrtc::JSessionDescription;
#endif


#endif  // org_webrtc_SdpObserver_SHARED_JNI
