// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.SdpObserver

#ifndef org_webrtc_SdpObserver_JNI
#define org_webrtc_SdpObserver_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "SdpObserver_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_SdpObserver()

// Class Accessors
#ifndef org_webrtc_SdpObserver_clazz_defined
#define org_webrtc_SdpObserver_clazz_defined
inline jclass org_webrtc_SdpObserver_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.SdpObserver";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static void Java_SdpObserver_onCreateFailure(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& error) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_SdpObserver_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onCreateFailure",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), error.obj());
}

static void Java_SdpObserver_onCreateSuccess(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& sdp) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_SdpObserver_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onCreateSuccess",
      "(Lorg/webrtc/SessionDescription;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), sdp.obj());
}

static void Java_SdpObserver_onSetFailure(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& error) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_SdpObserver_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onSetFailure",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), error.obj());
}

static void Java_SdpObserver_onSetSuccess(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_SdpObserver_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onSetSuccess",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNatives<::org::webrtc::JSdpObserver> {
  public:
  void onCreateFailure(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& error) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JSdpObserver>*>(this);
    Java_SdpObserver_onCreateFailure(env, *this_obj, error);
  }

  void onCreateSuccess(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JSessionDescription>& sdp) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JSdpObserver>*>(this);
    Java_SdpObserver_onCreateSuccess(env, *this_obj, sdp);
  }

  void onSetFailure(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& error) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JSdpObserver>*>(this);
    Java_SdpObserver_onSetFailure(env, *this_obj, error);
  }

  void onSetSuccess(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JSdpObserver>*>(this);
    Java_SdpObserver_onSetSuccess(env, *this_obj);
  }

};


}  // namespace jni_zero_internal


#pragma clang diagnostic pop
#endif  // org_webrtc_SdpObserver_JNI
