// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.SessionDescription

#ifndef org_webrtc_SessionDescription_SHARED_JNI
#define org_webrtc_SessionDescription_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JSessionDescription_DEFINED
#define _JNI_ZERO_org_webrtc_JSessionDescription_DEFINED
namespace org::webrtc {
class _JSessionDescription : public _jobject {};
using JSessionDescription = _JSessionDescription*;
}
#endif

#ifndef _JNI_ZERO_JSessionDescription_DEFINED
#define _JNI_ZERO_JSessionDescription_DEFINED
using ::org::webrtc::JSessionDescription;
#endif

#ifndef _JNI_ZERO_org_webrtc_JSessionDescription_Type_DEFINED
#define _JNI_ZERO_org_webrtc_JSessionDescription_Type_DEFINED
namespace org::webrtc {
class _JSessionDescription_Type : public _jobject {};
using JSessionDescription_Type = _JSessionDescription_Type*;
}
#endif

#ifndef _JNI_ZERO_JSessionDescription_Type_DEFINED
#define _JNI_ZERO_JSessionDescription_Type_DEFINED
using ::org::webrtc::JSessionDescription_Type;
#endif


#endif  // org_webrtc_SessionDescription_SHARED_JNI
