// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.SSLCertificateVerifier

#ifndef org_webrtc_SSLCertificateVerifier_SHARED_JNI
#define org_webrtc_SSLCertificateVerifier_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JSSLCertificateVerifier_DEFINED
#define _JNI_ZERO_org_webrtc_JSSLCertificateVerifier_DEFINED
namespace org::webrtc {
class _JSSLCertificateVerifier : public _jobject {};
using JSSLCertificateVerifier = _JSSLCertificateVerifier*;
}
#endif

#ifndef _JNI_ZERO_JSSLCertificateVerifier_DEFINED
#define _JNI_ZERO_JSSLCertificateVerifier_DEFINED
using ::org::webrtc::JSSLCertificateVerifier;
#endif


#endif  // org_webrtc_SSLCertificateVerifier_SHARED_JNI
