// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.StatsObserver

#ifndef org_webrtc_StatsObserver_JNI
#define org_webrtc_StatsObserver_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "StatsObserver_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_StatsObserver()

// Class Accessors
#ifndef org_webrtc_StatsObserver_clazz_defined
#define org_webrtc_StatsObserver_clazz_defined
inline jclass org_webrtc_StatsObserver_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.StatsObserver";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_StatsReport_clazz_defined
#define org_webrtc_StatsReport_clazz_defined
inline jclass org_webrtc_StatsReport_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.StatsReport";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static void Java_StatsObserver_onComplete(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobjectArray>& reports) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_StatsObserver_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onComplete",
      "([Lorg/webrtc/StatsReport;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), reports.obj());
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNatives<::org::webrtc::JStatsObserver> {
  public:
  void onComplete(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<::org::webrtc::JStatsReport>>& reports) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JStatsObserver>*>(this);
    Java_StatsObserver_onComplete(env, *this_obj, reports);
  }

};


}  // namespace jni_zero_internal


#pragma clang diagnostic pop
#endif  // org_webrtc_StatsObserver_JNI
