// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.math.BigInteger

#ifndef java_math_BigInteger_SHARED_JNI
#define java_math_BigInteger_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_math_JBigInteger_DEFINED
#define _JNI_ZERO_java_math_JBigInteger_DEFINED
namespace java::math {
class _JBigInteger : public _jobject {};
using JBigInteger = _JBigInteger*;
}
#endif

#ifndef _JNI_ZERO_JBigInteger_DEFINED
#define _JNI_ZERO_JBigInteger_DEFINED
using ::java::math::JBigInteger;
#endif

#ifndef _JNI_ZERO_java_util_JRandom_DEFINED
#define _JNI_ZERO_java_util_JRandom_DEFINED
namespace java::util {
class _JRandom : public _jobject {};
using JRandom = _JRandom*;
}
#endif

#ifndef _JNI_ZERO_JRandom_DEFINED
#define _JNI_ZERO_JRandom_DEFINED
using ::java::util::JRandom;
#endif


#endif  // java_math_BigInteger_SHARED_JNI
