// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Iterable

#ifndef java_lang_Iterable_JNI
#define java_lang_Iterable_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Iterable_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_lang_Iterable_clazz_defined
#define java_lang_Iterable_clazz_defined
inline jclass java_lang_Iterable_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.lang.Iterable";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Iterable {

// Native to Java functions
[[maybe_unused]] static void Java_Iterable_forEach(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Iterable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "forEach",
      "(Ljava/util/function/Consumer;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Iterable_iterator(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Iterable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "iterator",
      "()Ljava/util/Iterator;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Iterable_spliterator(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Iterable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "spliterator",
      "()Ljava/util/Spliterator;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace JNI_Iterable

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Iterable;

template <typename T>
class _CalledByNatives<::java::lang::JIterable<T>> {
  public:
  void forEach(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::function::JConsumer<jobject>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JIterable<T>>*>(this);
    Java_Iterable_forEach(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JIterator<T>> iterator(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JIterable<T>>*>(this);
    return Java_Iterable_iterator(env, *this_obj)
        .template As<::java::util::JIterator<T>>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSpliterator<T>> spliterator(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JIterable<T>>*>(this);
    return Java_Iterable_spliterator(env, *this_obj)
        .template As<::java::util::JSpliterator<T>>();
  }

};


}  // namespace jni_zero_internal


#pragma clang diagnostic pop
#endif  // java_lang_Iterable_JNI
