// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.util.LinkedHashMap

#ifndef java_util_LinkedHashMap_JNI
#define java_util_LinkedHashMap_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "LinkedHashMap_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_util_LinkedHashMap_clazz_defined
#define java_util_LinkedHashMap_clazz_defined
inline jclass java_util_LinkedHashMap_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.util.LinkedHashMap";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_LinkedHashMap {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_Constructor(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "()V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_Constructor__int(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(I)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_Constructor(
    JNIEnv* env,
    JniIntWrapper p0,
    float p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(IF)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), as_jint(p0), p1);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_Constructor(
    JNIEnv* env,
    JniIntWrapper p0,
    float p1,
    bool p2) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(IFZ)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), as_jint(p0), p1, p2);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_Constructor__Map(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/util/Map;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static void Java_LinkedHashMap_clear(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "clear",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static bool Java_LinkedHashMap_containsValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "containsValue",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_entrySet(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "entrySet",
      "()Ljava/util/Set;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static void Java_LinkedHashMap_forEach(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "forEach",
      "(Ljava/util/function/BiConsumer;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_get(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "get",
      "(Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_getOrDefault(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getOrDefault",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_keySet(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "keySet",
      "()Ljava/util/Set;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_putFirst(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putFirst",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_putLast(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putLast",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_LinkedHashMap_removeEldestEntry(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "removeEldestEntry",
      "(Ljava/util/Map$Entry;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static void Java_LinkedHashMap_replaceAll(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "replaceAll",
      "(Ljava/util/function/BiFunction;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_reversed(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "reversed",
      "()Ljava/util/SequencedMap;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_sequencedEntrySet(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "sequencedEntrySet",
      "()Ljava/util/SequencedSet;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_sequencedKeySet(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "sequencedKeySet",
      "()Ljava/util/SequencedSet;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_sequencedValues(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "sequencedValues",
      "()Ljava/util/SequencedCollection;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_values(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "values",
      "()Ljava/util/Collection;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_LinkedHashMap_newLinkedHashMap(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_LinkedHashMap_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "newLinkedHashMap",
      "(I)Ljava/util/LinkedHashMap;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace JNI_LinkedHashMap

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_LinkedHashMap;

template<>
class _CalledByNativesStatics<::java::util::JLinkedHashMap<jobject, jobject>> {
  public:
  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JLinkedHashMap<K, V>> New(JNIEnv* env) {
    return Java_LinkedHashMap_Constructor(env)
        .template As<::java::util::JLinkedHashMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JLinkedHashMap<K, V>> New(
      JNIEnv* env,
      JniIntWrapper p0) {
    return Java_LinkedHashMap_Constructor__int(env, p0)
        .template As<::java::util::JLinkedHashMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JLinkedHashMap<K, V>> New(
      JNIEnv* env,
      JniIntWrapper p0,
      float p1) {
    return Java_LinkedHashMap_Constructor(env, p0, p1)
        .template As<::java::util::JLinkedHashMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JLinkedHashMap<K, V>> New(
      JNIEnv* env,
      JniIntWrapper p0,
      float p1,
      bool p2) {
    return Java_LinkedHashMap_Constructor(env, p0, p1, p2)
        .template As<::java::util::JLinkedHashMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JLinkedHashMap<K, V>> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::JMap<K, V>>& p0) {
    return Java_LinkedHashMap_Constructor__Map(env, p0)
        .template As<::java::util::JLinkedHashMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JLinkedHashMap<K, V>> newLinkedHashMap(
      JNIEnv* env,
      JniIntWrapper p0) {
    return Java_LinkedHashMap_newLinkedHashMap(env, p0)
        .template As<::java::util::JLinkedHashMap<K, V>>();
  }

};

template <typename K, typename V>
class _CalledByNatives<::java::util::JLinkedHashMap<K, V>> {
  public:
  void clear(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    Java_LinkedHashMap_clear(env, *this_obj);
  }

  bool containsValue(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_containsValue(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSet<::java::util::JMap_Entry<K, V>>> entrySet(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_entrySet(env, *this_obj)
        .template As<::java::util::JSet<::java::util::JMap_Entry<K, V>>>();
  }

  void forEach(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::function::JBiConsumer<jobject, jobject>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    Java_LinkedHashMap_forEach(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<V> get(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_get(env, *this_obj, p0)
        .template As<V>();
  }

  ::jni_zero::ScopedJavaLocalRef<V> getOrDefault(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jobject>& p0,
      const ::jni_zero::JavaRef<V>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_getOrDefault(env, *this_obj, p0, p1)
        .template As<V>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSet<K>> keySet(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_keySet(env, *this_obj)
        .template As<::java::util::JSet<K>>();
  }

  ::jni_zero::ScopedJavaLocalRef<V> putFirst(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_putFirst(env, *this_obj, p0, p1)
        .template As<V>();
  }

  ::jni_zero::ScopedJavaLocalRef<V> putLast(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_putLast(env, *this_obj, p0, p1)
        .template As<V>();
  }

  bool removeEldestEntry(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::JMap_Entry<K, V>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_removeEldestEntry(env, *this_obj, p0);
  }

  void replaceAll(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::function::JBiFunction<jobject, jobject, V>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    Java_LinkedHashMap_replaceAll(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSequencedMap<K, V>> reversed(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_reversed(env, *this_obj)
        .template As<::java::util::JSequencedMap<K, V>>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSequencedSet<::java::util::JMap_Entry<K, V>>> sequencedEntrySet(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_sequencedEntrySet(env, *this_obj)
        .template As<::java::util::JSequencedSet<::java::util::JMap_Entry<K, V>>>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSequencedSet<K>> sequencedKeySet(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_sequencedKeySet(env, *this_obj)
        .template As<::java::util::JSequencedSet<K>>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSequencedCollection<V>> sequencedValues(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_sequencedValues(env, *this_obj)
        .template As<::java::util::JSequencedCollection<V>>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JCollection<V>> values(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JLinkedHashMap<K, V>>*>(this);
    return Java_LinkedHashMap_values(env, *this_obj)
        .template As<::java::util::JCollection<V>>();
  }

};


}  // namespace jni_zero_internal

namespace java::util {
using LinkedHashMapJni = ::jni_zero_internal::_CalledByNativesStatics<::java::util::JLinkedHashMap<jobject, jobject>>;
}
#ifndef _JNI_ZERO_LinkedHashMapJni_DEFINED
#define _JNI_ZERO_LinkedHashMapJni_DEFINED
using ::java::util::LinkedHashMapJni;
#endif


#pragma clang diagnostic pop
#endif  // java_util_LinkedHashMap_JNI
