# The rtc_base/ sources of the gn targets libjingle_peerconnection_so
# depends on.
add_library(webrtc_rtc_base ${WEBRTC_LIBRARY_TYPE}
  async_dns_resolver.cc
  async_packet_socket.cc
  async_socket.cc
  async_tcp_socket.cc
  async_udp_socket.cc
  base64.cc
  bit_buffer.cc
  bitrate_tracker.cc
  bitstream_reader.cc
  boringssl_certificate.cc
  boringssl_identity.cc
  buffer_queue.cc
  byte_buffer.cc
  callback_list.cc
  checks.cc
  clock_aligner.cc
  containers/flat_tree.cc
  copy_on_write_buffer.cc
  cpu_info.cc
  crc32.cc
  crypto_random.cc
  denormal_disabler.cc
  deprecated/recursive_critical_section.cc
  event.cc
  event_tracer.cc
  experiments/alr_experiment.cc
  experiments/balanced_degradation_settings.cc
  experiments/corruption_detection_frame_selector_settings.cc
  experiments/encoder_info_settings.cc
  experiments/encoder_speed_experiment.cc
  experiments/field_trial_list.cc
  experiments/field_trial_parser.cc
  experiments/field_trial_units.cc
  experiments/keyframe_interval_settings.cc
  experiments/min_video_bitrate_experiment.cc
  experiments/normalize_simulcast_size_experiment.cc
  experiments/quality_scaler_settings.cc
  experiments/quality_scaling_experiment.cc
  experiments/rate_control_settings.cc
  experiments/retransmit_flushed_packets_settings.cc
  experiments/struct_parameters_parser.cc
  file_rotating_stream.cc
  frequency_tracker.cc
  ifaddrs_converter.cc
  internal/default_socket_server.cc
  ip_address.cc
  log_sinks.cc
  logging.cc
  memory/aligned_malloc.cc
  message_digest.cc
  net_helper.cc
  net_helpers.cc
  network.cc
  network/received_packet.cc
  network/sent_packet.cc
  network_constants.cc
  network_monitor.cc
  network_monitor_factory.cc
  network_route.cc
  null_socket_server.cc
  numerics/event_based_exponential_moving_average.cc
  numerics/exp_filter.cc
  numerics/histogram_percentile_counter.cc
  numerics/moving_average.cc
  numerics/sample_counter.cc
  openssl_adapter.cc
  openssl_digest.cc
  openssl_key_pair.cc
  openssl_session_cache.cc
  openssl_stream_adapter.cc
  openssl_utility.cc
  operations_chain.cc
  physical_socket_server.cc
  platform_thread.cc
  platform_thread_types.cc
  race_checker.cc
  random.cc
  rate_limiter.cc
  rate_statistics.cc
  rate_tracker.cc
  ref_counter.cc
  rtc_certificate.cc
  rtc_certificate_generator.cc
  rtp_to_ntp_estimator.cc
  socket.cc
  socket_adapters.cc
  socket_address.cc
  ssl_adapter.cc
  ssl_certificate.cc
  ssl_fingerprint.cc
  ssl_identity.cc
  ssl_stream_adapter.cc
  stream.cc
  string_encode.cc
  string_to_number.cc
  string_utils.cc
  strings/string_builder.cc
  strings/string_format.cc
  synchronization/sequence_checker_internal.cc
  synchronization/yield_policy.cc
  system/file_wrapper.cc
  system/system_time.cc
  system_time.cc
  task_utils/repeating_task.cc
  text2pcap.cc
  thread.cc
  time_utils.cc
  timestamp_aligner.cc
  trace_categories.cc
  unique_id_generator.cc
  weak_ptr.cc
  zero_memory.cc
)
target_link_libraries(webrtc_rtc_base PRIVATE webrtc_config boringssl)
if(ANDROID)
  target_link_libraries(webrtc_rtc_base PRIVATE ndk_compat)
endif()

if(ANDROID)
  target_sources(webrtc_rtc_base PRIVATE
    ifaddrs_android.cc
    system/warn_current_thread_is_deadlocked.cc
    task_queue_stdlib.cc
  )
endif()

if(APPLE)
  target_sources(webrtc_rtc_base PRIVATE
    mac_ifaddrs_converter.cc
    system/cocoa_threading.mm
    system/gcd_helpers.m
    task_queue_gcd.cc
  )
endif()
