// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.EncodedImage

#ifndef org_webrtc_EncodedImage_JNI
#define org_webrtc_EncodedImage_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "EncodedImage_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_EncodedImage()

// Class Accessors
#ifndef org_webrtc_EncodedImage_clazz_defined
#define org_webrtc_EncodedImage_clazz_defined
inline jclass org_webrtc_EncodedImage_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.EncodedImage";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_EncodedImage_00024FrameType_clazz_defined
#define org_webrtc_EncodedImage_00024FrameType_clazz_defined
inline jclass org_webrtc_EncodedImage_00024FrameType_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.EncodedImage$FrameType";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_EncodedImage_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& buffer,
    const ::jni_zero::JavaRef<jobject>& releaseCallback,
    JniIntWrapper encodedWidth,
    JniIntWrapper encodedHeight,
    int64_t captureTimeNs,
    const ::jni_zero::JavaRef<jobject>& frameType,
    JniIntWrapper rotation,
    const ::jni_zero::JavaRef<jobject>& qp) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/nio/ByteBuffer;Ljava/lang/Runnable;IIJLorg/webrtc/EncodedImage$FrameType;ILjava/lang/Integer;)V",
      &cached_method_id);
  auto _ret = env->NewObject(
      clazz,
      call_context.method_id(),
      buffer.obj(),
      releaseCallback.obj(),
      as_jint(encodedWidth),
      as_jint(encodedHeight),
      captureTimeNs,
      frameType.obj(),
      as_jint(rotation),
      qp.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_EncodedImage_getBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getBuffer",
      "()Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static int64_t Java_EncodedImage_getCaptureTimeNs(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getCaptureTimeNs",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_EncodedImage_getEncodedHeight(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getEncodedHeight",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_EncodedImage_getEncodedWidth(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getEncodedWidth",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_EncodedImage_getFrameType(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getFrameType",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_EncodedImage_getQp(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getQp",
      "()Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static int32_t Java_EncodedImage_getRotation(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getRotation",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_FrameType_fromNativeIndex(
    JNIEnv* env,
    JniIntWrapper nativeIndex) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_EncodedImage_00024FrameType_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "fromNativeIndex",
      "(I)Lorg/webrtc/EncodedImage$FrameType;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(nativeIndex));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JEncodedImage> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JEncodedImage> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::nio::JByteBuffer>& buffer,
      const ::jni_zero::JavaRef<::java::lang::JRunnable>& releaseCallback,
      JniIntWrapper encodedWidth,
      JniIntWrapper encodedHeight,
      int64_t captureTimeNs,
      const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage_FrameType>& frameType,
      JniIntWrapper rotation,
      const ::jni_zero::JavaRef<::java::lang::JInteger>& qp) {
    return Java_EncodedImage_Constructor(
        env,
        buffer,
        releaseCallback,
        encodedWidth,
        encodedHeight,
        captureTimeNs,
        frameType,
        rotation,
        qp)
        .As<::org::webrtc::JEncodedImage>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JEncodedImage> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> getBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage>*>(this);
    return Java_EncodedImage_getBuffer(env, *this_obj)
        .As<::java::nio::JByteBuffer>();
  }

  int64_t getCaptureTimeNs(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage>*>(this);
    return Java_EncodedImage_getCaptureTimeNs(env, *this_obj);
  }

  int32_t getEncodedHeight(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage>*>(this);
    return Java_EncodedImage_getEncodedHeight(env, *this_obj);
  }

  int32_t getEncodedWidth(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage>*>(this);
    return Java_EncodedImage_getEncodedWidth(env, *this_obj);
  }

  int32_t getFrameType(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage>*>(this);
    return Java_EncodedImage_getFrameType(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> getQp(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage>*>(this);
    return Java_EncodedImage_getQp(env, *this_obj)
        .As<::java::lang::JInteger>();
  }

  int32_t getRotation(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage>*>(this);
    return Java_EncodedImage_getRotation(env, *this_obj);
  }

};

template<>
class _CalledByNativesStatics<::org::webrtc::JEncodedImage_FrameType> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JEncodedImage_FrameType> fromNativeIndex(
      JNIEnv* env,
      JniIntWrapper nativeIndex) {
    return Java_FrameType_fromNativeIndex(env, nativeIndex)
        .As<::org::webrtc::JEncodedImage_FrameType>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using EncodedImageJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JEncodedImage>;
}
#ifndef _JNI_ZERO_EncodedImageJni_DEFINED
#define _JNI_ZERO_EncodedImageJni_DEFINED
using ::org::webrtc::EncodedImageJni;
#endif

namespace org::webrtc {
using EncodedImage_FrameTypeJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JEncodedImage_FrameType>;
}
#ifndef _JNI_ZERO_EncodedImage_FrameTypeJni_DEFINED
#define _JNI_ZERO_EncodedImage_FrameTypeJni_DEFINED
using ::org::webrtc::EncodedImage_FrameTypeJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_EncodedImage_JNI
