// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.H264Utils

#ifndef org_webrtc_H264Utils_JNI
#define org_webrtc_H264Utils_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "H264Utils_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static bool JNI_H264Utils_IsSameH264Profile(
//     JNIEnv* env,
//     const jni_zero::JavaRef<::java::util::JMap<jstring, jstring>>& params1,
//     const jni_zero::JavaRef<::java::util::JMap<jstring, jstring>>& params2);
//

// Triggers a compiler warning if DEFINE_JNI(H264Utils) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_H264Utils() {}

// Java to native functions
#define DEFINE_JNI_FOR_H264Utils()                                                                 \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT bool Java_J_N_MX3uy8Fu(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      jobject params1,                                                                             \
      jobject params2) {                                                                           \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_H264Utils();                                                   \
                                                                                                   \
    auto params1_ref = jni_zero::JavaRef<::java::util::JMap<jstring, jstring>>::CreateLeaky(env,   \
        static_cast<::java::util::JMap<jstring, jstring>>(params1));                               \
    auto params2_ref = jni_zero::JavaRef<::java::util::JMap<jstring, jstring>>::CreateLeaky(env,   \
        static_cast<::java::util::JMap<jstring, jstring>>(params2));                               \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_H264Utils_IsSameH264Profile(std::forward<decltype(args)>(args)...)) {           \
        return JNI_H264Utils_IsSameH264Profile(std::forward<decltype(args)>(args)...);             \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, params1_ref, params2_ref); }) {                   \
        return func_wrapper(env, params1_ref, params2_ref);                                        \
      } else if constexpr (requires { func_wrapper(params1_ref, params2_ref); }) {                 \
        return func_wrapper(params1_ref, params2_ref);                                             \
      } else {                                                                                     \
        static_assert(false, "JNI_H264Utils_IsSameH264Profile() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (const jni_zero::JavaRef<JMap<jstring, jstring>>&, const jni_zero::JavaRef<JMap<jstring, jstring>>&)\nSee gen/jni_headers/sdk/android/generated_video_jni/H264Utils_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

namespace webrtc::jni {


}  // namespace webrtc::jni
#pragma clang diagnostic pop
#endif  // org_webrtc_H264Utils_JNI
