// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.JavaI420Buffer

#ifndef org_webrtc_JavaI420Buffer_JNI
#define org_webrtc_JavaI420Buffer_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "JavaI420Buffer_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static void JNI_JavaI420Buffer_CropAndScaleI420(
//     JNIEnv* env,
//     const jni_zero::JavaRef<::java::nio::JByteBuffer>& srcY,
//     int32_t srcStrideY,
//     const jni_zero::JavaRef<::java::nio::JByteBuffer>& srcU,
//     int32_t srcStrideU,
//     const jni_zero::JavaRef<::java::nio::JByteBuffer>& srcV,
//     int32_t srcStrideV,
//     int32_t cropX,
//     int32_t cropY,
//     int32_t cropWidth,
//     int32_t cropHeight,
//     const jni_zero::JavaRef<::java::nio::JByteBuffer>& dstY,
//     int32_t dstStrideY,
//     const jni_zero::JavaRef<::java::nio::JByteBuffer>& dstU,
//     int32_t dstStrideU,
//     const jni_zero::JavaRef<::java::nio::JByteBuffer>& dstV,
//     int32_t dstStrideV,
//     int32_t scaleWidth,
//     int32_t scaleHeight);
//

// Triggers a compiler warning if DEFINE_JNI(JavaI420Buffer) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_JavaI420Buffer() {}

// Java to native functions
#define DEFINE_JNI_FOR_JavaI420Buffer()                                                            \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_MigXbzvS(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      jobject srcY,                                                                                \
      int32_t srcStrideY,                                                                          \
      jobject srcU,                                                                                \
      int32_t srcStrideU,                                                                          \
      jobject srcV,                                                                                \
      int32_t srcStrideV,                                                                          \
      int32_t cropX,                                                                               \
      int32_t cropY,                                                                               \
      int32_t cropWidth,                                                                           \
      int32_t cropHeight,                                                                          \
      jobject dstY,                                                                                \
      int32_t dstStrideY,                                                                          \
      jobject dstU,                                                                                \
      int32_t dstStrideU,                                                                          \
      jobject dstV,                                                                                \
      int32_t dstStrideV,                                                                          \
      int32_t scaleWidth,                                                                          \
      int32_t scaleHeight) {                                                                       \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_JavaI420Buffer();                                              \
                                                                                                   \
    auto srcY_ref = jni_zero::JavaRef<::java::nio::JByteBuffer>::CreateLeaky(env,                  \
        static_cast<::java::nio::JByteBuffer>(srcY));                                              \
    auto srcU_ref = jni_zero::JavaRef<::java::nio::JByteBuffer>::CreateLeaky(env,                  \
        static_cast<::java::nio::JByteBuffer>(srcU));                                              \
    auto srcV_ref = jni_zero::JavaRef<::java::nio::JByteBuffer>::CreateLeaky(env,                  \
        static_cast<::java::nio::JByteBuffer>(srcV));                                              \
    auto dstY_ref = jni_zero::JavaRef<::java::nio::JByteBuffer>::CreateLeaky(env,                  \
        static_cast<::java::nio::JByteBuffer>(dstY));                                              \
    auto dstU_ref = jni_zero::JavaRef<::java::nio::JByteBuffer>::CreateLeaky(env,                  \
        static_cast<::java::nio::JByteBuffer>(dstU));                                              \
    auto dstV_ref = jni_zero::JavaRef<::java::nio::JByteBuffer>::CreateLeaky(env,                  \
        static_cast<::java::nio::JByteBuffer>(dstV));                                              \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_JavaI420Buffer_CropAndScaleI420(std::forward<decltype(args)>(args)...)) {       \
        return JNI_JavaI420Buffer_CropAndScaleI420(std::forward<decltype(args)>(args)...);         \
      };                                                                                           \
      if constexpr (requires { func_wrapper(                                                       \
          env,                                                                                     \
          srcY_ref,                                                                                \
          srcStrideY,                                                                              \
          srcU_ref,                                                                                \
          srcStrideU,                                                                              \
          srcV_ref,                                                                                \
          srcStrideV,                                                                              \
          cropX,                                                                                   \
          cropY,                                                                                   \
          cropWidth,                                                                               \
          cropHeight,                                                                              \
          dstY_ref,                                                                                \
          dstStrideY,                                                                              \
          dstU_ref,                                                                                \
          dstStrideU,                                                                              \
          dstV_ref,                                                                                \
          dstStrideV,                                                                              \
          scaleWidth,                                                                              \
          scaleHeight); }) {                                                                       \
        return func_wrapper(                                                                       \
            env,                                                                                   \
            srcY_ref,                                                                              \
            srcStrideY,                                                                            \
            srcU_ref,                                                                              \
            srcStrideU,                                                                            \
            srcV_ref,                                                                              \
            srcStrideV,                                                                            \
            cropX,                                                                                 \
            cropY,                                                                                 \
            cropWidth,                                                                             \
            cropHeight,                                                                            \
            dstY_ref,                                                                              \
            dstStrideY,                                                                            \
            dstU_ref,                                                                              \
            dstStrideU,                                                                            \
            dstV_ref,                                                                              \
            dstStrideV,                                                                            \
            scaleWidth,                                                                            \
            scaleHeight);                                                                          \
      } else if constexpr (requires { func_wrapper(                                                \
          srcY_ref,                                                                                \
          srcStrideY,                                                                              \
          srcU_ref,                                                                                \
          srcStrideU,                                                                              \
          srcV_ref,                                                                                \
          srcStrideV,                                                                              \
          cropX,                                                                                   \
          cropY,                                                                                   \
          cropWidth,                                                                               \
          cropHeight,                                                                              \
          dstY_ref,                                                                                \
          dstStrideY,                                                                              \
          dstU_ref,                                                                                \
          dstStrideU,                                                                              \
          dstV_ref,                                                                                \
          dstStrideV,                                                                              \
          scaleWidth,                                                                              \
          scaleHeight); }) {                                                                       \
        return func_wrapper(                                                                       \
            srcY_ref,                                                                              \
            srcStrideY,                                                                            \
            srcU_ref,                                                                              \
            srcStrideU,                                                                            \
            srcV_ref,                                                                              \
            srcStrideV,                                                                            \
            cropX,                                                                                 \
            cropY,                                                                                 \
            cropWidth,                                                                             \
            cropHeight,                                                                            \
            dstY_ref,                                                                              \
            dstStrideY,                                                                            \
            dstU_ref,                                                                              \
            dstStrideU,                                                                            \
            dstV_ref,                                                                              \
            dstStrideV,                                                                            \
            scaleWidth,                                                                            \
            scaleHeight);                                                                          \
      } else {                                                                                     \
        static_assert(false, "JNI_JavaI420Buffer_CropAndScaleI420() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (const jni_zero::JavaRef<JByteBuffer>&, int32_t, const jni_zero::JavaRef<JByteBuffer>&, int32_t, const jni_zero::JavaRef<JByteBuffer>&, int32_t, int32_t, int32_t, int32_t, int32_t, const jni_zero::JavaRef<JByteBuffer>&, int32_t, const jni_zero::JavaRef<JByteBuffer>&, int32_t, const jni_zero::JavaRef<JByteBuffer>&, int32_t, int32_t, int32_t)\nSee gen/jni_headers/sdk/android/generated_video_jni/JavaI420Buffer_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

namespace webrtc::jni {


}  // namespace webrtc::jni
#pragma clang diagnostic pop
#endif  // org_webrtc_JavaI420Buffer_JNI
