// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.NativeCapturerObserver

#ifndef org_webrtc_NativeCapturerObserver_JNI
#define org_webrtc_NativeCapturerObserver_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "NativeCapturerObserver_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_NativeCapturerObserver()

// Class Accessors
#ifndef org_webrtc_NativeCapturerObserver_clazz_defined
#define org_webrtc_NativeCapturerObserver_clazz_defined
inline jclass org_webrtc_NativeCapturerObserver_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.NativeCapturerObserver";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_NativeCapturerObserver_Constructor(
    JNIEnv* env,
    int64_t nativeSource) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_NativeCapturerObserver_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(J)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), nativeSource);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JNativeCapturerObserver> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JNativeCapturerObserver> New(
      JNIEnv* env,
      int64_t nativeSource) {
    return Java_NativeCapturerObserver_Constructor(env, nativeSource)
        .As<::org::webrtc::JNativeCapturerObserver>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using NativeCapturerObserverJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JNativeCapturerObserver>;
}
#ifndef _JNI_ZERO_NativeCapturerObserverJni_DEFINED
#define _JNI_ZERO_NativeCapturerObserverJni_DEFINED
using ::org::webrtc::NativeCapturerObserverJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_NativeCapturerObserver_JNI
