// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.NativeCapturerObserver

#ifndef org_webrtc_NativeCapturerObserver_SHARED_JNI
#define org_webrtc_NativeCapturerObserver_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JNativeCapturerObserver_DEFINED
#define _JNI_ZERO_org_webrtc_JNativeCapturerObserver_DEFINED
namespace org::webrtc {
class _JNativeCapturerObserver : public _jobject {};
using JNativeCapturerObserver = _JNativeCapturerObserver*;
}
#endif

#ifndef _JNI_ZERO_JNativeCapturerObserver_DEFINED
#define _JNI_ZERO_JNativeCapturerObserver_DEFINED
using ::org::webrtc::JNativeCapturerObserver;
#endif


#endif  // org_webrtc_NativeCapturerObserver_SHARED_JNI
