// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.TimestampAligner

#ifndef org_webrtc_TimestampAligner_JNI
#define org_webrtc_TimestampAligner_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "TimestampAligner_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static int64_t JNI_TimestampAligner_CreateTimestampAligner(JNIEnv* env, int64_t webrtcEnvRef);
//
// static void JNI_TimestampAligner_ReleaseTimestampAligner(JNIEnv* env, int64_t timestampAligner);
//
// static int64_t JNI_TimestampAligner_TranslateTimestamp(
//     JNIEnv* env,
//     int64_t timestampAligner,
//     int64_t cameraTimeNs);
//

// Triggers a compiler warning if DEFINE_JNI(TimestampAligner) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_TimestampAligner() {}

// Java to native functions
#define DEFINE_JNI_FOR_TimestampAligner()                                                          \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT int64_t Java_J_N_MS_1C30sr(                                             \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t webrtcEnvRef) {                                                                      \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_TimestampAligner();                                            \
                                                                                                   \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_TimestampAligner_CreateTimestampAligner(std::forward<decltype(args)>(args)...)) { \
        return JNI_TimestampAligner_CreateTimestampAligner(std::forward<decltype(args)>(args)...); \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, webrtcEnvRef); }) {                               \
        return func_wrapper(env, webrtcEnvRef);                                                    \
      } else if constexpr (requires { func_wrapper(webrtcEnvRef); }) {                             \
        return func_wrapper(webrtcEnvRef);                                                         \
      } else {                                                                                     \
        static_assert(false, "JNI_TimestampAligner_CreateTimestampAligner() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_video_jni/TimestampAligner_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_MfA3r5_00024J(                                            \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t timestampAligner) {                                                                  \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_TimestampAligner_ReleaseTimestampAligner(std::forward<decltype(args)>(args)...)) { \
        return JNI_TimestampAligner_ReleaseTimestampAligner(std::forward<decltype(args)>(args)...); \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, timestampAligner); }) {                           \
        return func_wrapper(env, timestampAligner);                                                \
      } else if constexpr (requires { func_wrapper(timestampAligner); }) {                         \
        return func_wrapper(timestampAligner);                                                     \
      } else {                                                                                     \
        static_assert(false, "JNI_TimestampAligner_ReleaseTimestampAligner() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t)\nSee gen/jni_headers/sdk/android/generated_video_jni/TimestampAligner_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
  JNI_ZERO_BOUNDARY_EXPORT int64_t Java_J_N_MDRjNN1y(                                              \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t timestampAligner,                                                                    \
      int64_t cameraTimeNs) {                                                                      \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_TimestampAligner_TranslateTimestamp(std::forward<decltype(args)>(args)...)) {   \
        return JNI_TimestampAligner_TranslateTimestamp(std::forward<decltype(args)>(args)...);     \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, timestampAligner, cameraTimeNs); }) {             \
        return func_wrapper(env, timestampAligner, cameraTimeNs);                                  \
      } else if constexpr (requires { func_wrapper(timestampAligner, cameraTimeNs); }) {           \
        return func_wrapper(timestampAligner, cameraTimeNs);                                       \
      } else {                                                                                     \
        static_assert(false, "JNI_TimestampAligner_TranslateTimestamp() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (int64_t, int64_t)\nSee gen/jni_headers/sdk/android/generated_video_jni/TimestampAligner_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    auto return_value = dependent_context(0);                                                      \
    return return_value;                                                                           \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

namespace webrtc::jni {


}  // namespace webrtc::jni
#pragma clang diagnostic pop
#endif  // org_webrtc_TimestampAligner_JNI
