// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoEncoderFactory

#ifndef org_webrtc_VideoEncoderFactory_JNI
#define org_webrtc_VideoEncoderFactory_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "VideoEncoderFactory_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_VideoEncoderFactory()

// Class Accessors
#ifndef org_webrtc_VideoEncoderFactory_clazz_defined
#define org_webrtc_VideoEncoderFactory_clazz_defined
inline jclass org_webrtc_VideoEncoderFactory_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoEncoderFactory";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_VideoEncoderFactory_00024VideoEncoderSelector_clazz_defined
#define org_webrtc_VideoEncoderFactory_00024VideoEncoderSelector_clazz_defined
inline jclass org_webrtc_VideoEncoderFactory_00024VideoEncoderSelector_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoEncoderFactory$VideoEncoderSelector";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoEncoderFactory_createEncoder(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& info) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderFactory_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "createEncoder",
      "(Lorg/webrtc/VideoCodecInfo;)Lorg/webrtc/VideoEncoder;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), info.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoEncoderFactory_getEncoderSelector(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderFactory_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getEncoderSelector",
      "()Lorg/webrtc/VideoEncoderFactory$VideoEncoderSelector;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobjectArray> Java_VideoEncoderFactory_getImplementations(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderFactory_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getImplementations",
      "()[Lorg/webrtc/VideoCodecInfo;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jobjectArray _ret2 = static_cast<jobjectArray>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jobjectArray>::Adopt(env, _ret2);
}

static ::jni_zero::ScopedJavaLocalRef<jobjectArray> Java_VideoEncoderFactory_getSupportedCodecs(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderFactory_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getSupportedCodecs",
      "()[Lorg/webrtc/VideoCodecInfo;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jobjectArray _ret2 = static_cast<jobjectArray>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jobjectArray>::Adopt(env, _ret2);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoEncoderSelector_onAvailableBitrate(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper kbps) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderFactory_00024VideoEncoderSelector_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onAvailableBitrate",
      "(I)Lorg/webrtc/VideoCodecInfo;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(kbps));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static void Java_VideoEncoderSelector_onCurrentEncoder(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& info) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderFactory_00024VideoEncoderSelector_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onCurrentEncoder",
      "(Lorg/webrtc/VideoCodecInfo;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), info.obj());
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoEncoderSelector_onEncoderBroken(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderFactory_00024VideoEncoderSelector_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onEncoderBroken",
      "()Lorg/webrtc/VideoCodecInfo;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoEncoderSelector_onResolutionChange(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper widht,
    JniIntWrapper height) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderFactory_00024VideoEncoderSelector_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "onResolutionChange",
      "(II)Lorg/webrtc/VideoCodecInfo;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      as_jint(widht),
      as_jint(height));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNatives<::org::webrtc::JVideoEncoderFactory> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoEncoder> createEncoder(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoCodecInfo>& info) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderFactory>*>(this);
    return Java_VideoEncoderFactory_createEncoder(env, *this_obj, info)
        .As<::org::webrtc::JVideoEncoder>();
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoEncoderFactory_VideoEncoderSelector> getEncoderSelector(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderFactory>*>(this);
    return Java_VideoEncoderFactory_getEncoderSelector(env, *this_obj)
        .As<::org::webrtc::JVideoEncoderFactory_VideoEncoderSelector>();
  }

  ::jni_zero::ScopedJavaLocalRef<JArray<::org::webrtc::JVideoCodecInfo>> getImplementations(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderFactory>*>(this);
    return Java_VideoEncoderFactory_getImplementations(env, *this_obj)
        .As<JArray<::org::webrtc::JVideoCodecInfo>>();
  }

  ::jni_zero::ScopedJavaLocalRef<JArray<::org::webrtc::JVideoCodecInfo>> getSupportedCodecs(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderFactory>*>(this);
    return Java_VideoEncoderFactory_getSupportedCodecs(env, *this_obj)
        .As<JArray<::org::webrtc::JVideoCodecInfo>>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JVideoEncoderFactory_VideoEncoderSelector> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoCodecInfo> onAvailableBitrate(
      JNIEnv* env,
      JniIntWrapper kbps) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderFactory_VideoEncoderSelector>*>(this);
    return Java_VideoEncoderSelector_onAvailableBitrate(env, *this_obj, kbps)
        .As<::org::webrtc::JVideoCodecInfo>();
  }

  void onCurrentEncoder(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoCodecInfo>& info) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderFactory_VideoEncoderSelector>*>(this);
    Java_VideoEncoderSelector_onCurrentEncoder(env, *this_obj, info);
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoCodecInfo> onEncoderBroken(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderFactory_VideoEncoderSelector>*>(this);
    return Java_VideoEncoderSelector_onEncoderBroken(env, *this_obj)
        .As<::org::webrtc::JVideoCodecInfo>();
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoCodecInfo> onResolutionChange(
      JNIEnv* env,
      JniIntWrapper widht,
      JniIntWrapper height) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderFactory_VideoEncoderSelector>*>(this);
    return Java_VideoEncoderSelector_onResolutionChange(env, *this_obj, widht, height)
        .As<::org::webrtc::JVideoCodecInfo>();
  }

};


}  // namespace jni_zero_internal


#pragma clang diagnostic pop
#endif  // org_webrtc_VideoEncoderFactory_JNI
