// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoSink

#ifndef org_webrtc_VideoSink_SHARED_JNI
#define org_webrtc_VideoSink_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JVideoFrame_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoFrame_DEFINED
namespace org::webrtc {
class _JVideoFrame : public _jobject {};
using JVideoFrame = _JVideoFrame*;
}
#endif

#ifndef _JNI_ZERO_JVideoFrame_DEFINED
#define _JNI_ZERO_JVideoFrame_DEFINED
using ::org::webrtc::JVideoFrame;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoSink_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoSink_DEFINED
namespace org::webrtc {
class _JVideoSink : public _jobject {};
using JVideoSink = _JVideoSink*;
}
#endif

#ifndef _JNI_ZERO_JVideoSink_DEFINED
#define _JNI_ZERO_JVideoSink_DEFINED
using ::org::webrtc::JVideoSink;
#endif


#endif  // org_webrtc_VideoSink_SHARED_JNI
