// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoDecoder

#ifndef org_webrtc_VideoDecoder_JNI
#define org_webrtc_VideoDecoder_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "VideoDecoder_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_VideoDecoder()

// Class Accessors
#ifndef org_webrtc_VideoDecoder_clazz_defined
#define org_webrtc_VideoDecoder_clazz_defined
inline jclass org_webrtc_VideoDecoder_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoDecoder";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_VideoDecoder_00024Settings_clazz_defined
#define org_webrtc_VideoDecoder_00024Settings_clazz_defined
inline jclass org_webrtc_VideoDecoder_00024Settings_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoDecoder$Settings";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static int64_t Java_VideoDecoder_createNative(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t webrtcEnvRef) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoDecoder_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "createNative",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id(), webrtcEnvRef);
  return _ret;
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoDecoder_decode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& frame,
    const ::jni_zero::JavaRef<jobject>& info) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoDecoder_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "decode",
      "(Lorg/webrtc/EncodedImage;Lorg/webrtc/VideoDecoder$DecodeInfo;)Lorg/webrtc/VideoCodecStatus;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), frame.obj(), info.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jstring> Java_VideoDecoder_getImplementationName(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoDecoder_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getImplementationName",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoDecoder_initDecode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& settings,
    const ::jni_zero::JavaRef<jobject>& decodeCallback) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoDecoder_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "initDecode",
      "(Lorg/webrtc/VideoDecoder$Settings;Lorg/webrtc/VideoDecoder$Callback;)Lorg/webrtc/VideoCodecStatus;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      settings.obj(),
      decodeCallback.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoDecoder_release(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoDecoder_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "release",
      "()Lorg/webrtc/VideoCodecStatus;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Settings_Constructor(
    JNIEnv* env,
    JniIntWrapper numberOfCores,
    JniIntWrapper width,
    JniIntWrapper height) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoDecoder_00024Settings_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(III)V",
      &cached_method_id);
  auto _ret = env->NewObject(
      clazz,
      call_context.method_id(),
      as_jint(numberOfCores),
      as_jint(width),
      as_jint(height));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNatives<::org::webrtc::JVideoDecoder> {
  public:
  int64_t createNative(JNIEnv* env, int64_t webrtcEnvRef) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoDecoder>*>(this);
    return Java_VideoDecoder_createNative(env, *this_obj, webrtcEnvRef);
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoCodecStatus> decode(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JEncodedImage>& frame,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoDecoder_DecodeInfo>& info) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoDecoder>*>(this);
    return Java_VideoDecoder_decode(env, *this_obj, frame, info)
        .As<::org::webrtc::JVideoCodecStatus>();
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> getImplementationName(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoDecoder>*>(this);
    return Java_VideoDecoder_getImplementationName(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoCodecStatus> initDecode(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoDecoder_Settings>& settings,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoDecoder_Callback>& decodeCallback) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoDecoder>*>(this);
    return Java_VideoDecoder_initDecode(env, *this_obj, settings, decodeCallback)
        .As<::org::webrtc::JVideoCodecStatus>();
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoCodecStatus> release(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoDecoder>*>(this);
    return Java_VideoDecoder_release(env, *this_obj)
        .As<::org::webrtc::JVideoCodecStatus>();
  }

};

template<>
class _CalledByNativesStatics<::org::webrtc::JVideoDecoder_Settings> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoDecoder_Settings> New(
      JNIEnv* env,
      JniIntWrapper numberOfCores,
      JniIntWrapper width,
      JniIntWrapper height) {
    return Java_Settings_Constructor(env, numberOfCores, width, height)
        .As<::org::webrtc::JVideoDecoder_Settings>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using VideoDecoder_SettingsJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JVideoDecoder_Settings>;
}
#ifndef _JNI_ZERO_VideoDecoder_SettingsJni_DEFINED
#define _JNI_ZERO_VideoDecoder_SettingsJni_DEFINED
using ::org::webrtc::VideoDecoder_SettingsJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_VideoDecoder_JNI
