// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoEncoderWrapper

#ifndef org_webrtc_VideoEncoderWrapper_SHARED_JNI
#define org_webrtc_VideoEncoderWrapper_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JInteger_DEFINED
#define _JNI_ZERO_java_lang_JInteger_DEFINED
namespace java::lang {
class _JInteger : public _jobject {};
using JInteger = _JInteger*;
}
#endif

#ifndef _JNI_ZERO_JInteger_DEFINED
#define _JNI_ZERO_JInteger_DEFINED
using ::java::lang::JInteger;
#endif

#ifndef _JNI_ZERO_org_webrtc_JEncodedImage_DEFINED
#define _JNI_ZERO_org_webrtc_JEncodedImage_DEFINED
namespace org::webrtc {
class _JEncodedImage : public _jobject {};
using JEncodedImage = _JEncodedImage*;
}
#endif

#ifndef _JNI_ZERO_JEncodedImage_DEFINED
#define _JNI_ZERO_JEncodedImage_DEFINED
using ::org::webrtc::JEncodedImage;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoEncoder_ScalingSettings_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoEncoder_ScalingSettings_DEFINED
namespace org::webrtc {
class _JVideoEncoder_ScalingSettings : public _jobject {};
using JVideoEncoder_ScalingSettings = _JVideoEncoder_ScalingSettings*;
}
#endif

#ifndef _JNI_ZERO_JVideoEncoder_ScalingSettings_DEFINED
#define _JNI_ZERO_JVideoEncoder_ScalingSettings_DEFINED
using ::org::webrtc::JVideoEncoder_ScalingSettings;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoEncoderWrapper_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoEncoderWrapper_DEFINED
namespace org::webrtc {
class _JVideoEncoderWrapper : public _jobject {};
using JVideoEncoderWrapper = _JVideoEncoderWrapper*;
}
#endif

#ifndef _JNI_ZERO_JVideoEncoderWrapper_DEFINED
#define _JNI_ZERO_JVideoEncoderWrapper_DEFINED
using ::org::webrtc::JVideoEncoderWrapper;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoEncoderWrapper_NativeEncoderCallback_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoEncoderWrapper_NativeEncoderCallback_DEFINED
namespace org::webrtc {
class _JVideoEncoderWrapper_NativeEncoderCallback : public _jobject {};
using JVideoEncoderWrapper_NativeEncoderCallback = _JVideoEncoderWrapper_NativeEncoderCallback*;
}
#endif

#ifndef _JNI_ZERO_JVideoEncoderWrapper_NativeEncoderCallback_DEFINED
#define _JNI_ZERO_JVideoEncoderWrapper_NativeEncoderCallback_DEFINED
using ::org::webrtc::JVideoEncoderWrapper_NativeEncoderCallback;
#endif


#endif  // org_webrtc_VideoEncoderWrapper_SHARED_JNI
