// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoCodecInfo

#ifndef org_webrtc_VideoCodecInfo_SHARED_JNI
#define org_webrtc_VideoCodecInfo_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_util_JMap_DEFINED
#define _JNI_ZERO_java_util_JMap_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2>
class _JMap : public _jobject {};
template <typename T1, typename T2>
using JMap = _JMap<T1, T2>*;
}
#endif

#ifndef _JNI_ZERO_JMap_DEFINED
#define _JNI_ZERO_JMap_DEFINED
using ::java::util::JMap;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoCodecInfo_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoCodecInfo_DEFINED
namespace org::webrtc {
class _JVideoCodecInfo : public _jobject {};
using JVideoCodecInfo = _JVideoCodecInfo*;
}
#endif

#ifndef _JNI_ZERO_JVideoCodecInfo_DEFINED
#define _JNI_ZERO_JVideoCodecInfo_DEFINED
using ::org::webrtc::JVideoCodecInfo;
#endif


#endif  // org_webrtc_VideoCodecInfo_SHARED_JNI
