// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoDecoderWrapper

#ifndef org_webrtc_VideoDecoderWrapper_SHARED_JNI
#define org_webrtc_VideoDecoderWrapper_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JInteger_DEFINED
#define _JNI_ZERO_java_lang_JInteger_DEFINED
namespace java::lang {
class _JInteger : public _jobject {};
using JInteger = _JInteger*;
}
#endif

#ifndef _JNI_ZERO_JInteger_DEFINED
#define _JNI_ZERO_JInteger_DEFINED
using ::java::lang::JInteger;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoDecoderWrapper_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoDecoderWrapper_DEFINED
namespace org::webrtc {
class _JVideoDecoderWrapper : public _jobject {};
using JVideoDecoderWrapper = _JVideoDecoderWrapper*;
}
#endif

#ifndef _JNI_ZERO_JVideoDecoderWrapper_DEFINED
#define _JNI_ZERO_JVideoDecoderWrapper_DEFINED
using ::org::webrtc::JVideoDecoderWrapper;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoDecoderWrapper_NativeDecoderCallback_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoDecoderWrapper_NativeDecoderCallback_DEFINED
namespace org::webrtc {
class _JVideoDecoderWrapper_NativeDecoderCallback : public _jobject {};
using JVideoDecoderWrapper_NativeDecoderCallback = _JVideoDecoderWrapper_NativeDecoderCallback*;
}
#endif

#ifndef _JNI_ZERO_JVideoDecoderWrapper_NativeDecoderCallback_DEFINED
#define _JNI_ZERO_JVideoDecoderWrapper_NativeDecoderCallback_DEFINED
using ::org::webrtc::JVideoDecoderWrapper_NativeDecoderCallback;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoFrame_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoFrame_DEFINED
namespace org::webrtc {
class _JVideoFrame : public _jobject {};
using JVideoFrame = _JVideoFrame*;
}
#endif

#ifndef _JNI_ZERO_JVideoFrame_DEFINED
#define _JNI_ZERO_JVideoFrame_DEFINED
using ::org::webrtc::JVideoFrame;
#endif


#endif  // org_webrtc_VideoDecoderWrapper_SHARED_JNI
