// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoFrame

#ifndef org_webrtc_VideoFrame_JNI
#define org_webrtc_VideoFrame_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "VideoFrame_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_VideoFrame()

// Class Accessors
#ifndef org_webrtc_VideoFrame_clazz_defined
#define org_webrtc_VideoFrame_clazz_defined
inline jclass org_webrtc_VideoFrame_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoFrame";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_VideoFrame_00024Buffer_clazz_defined
#define org_webrtc_VideoFrame_00024Buffer_clazz_defined
inline jclass org_webrtc_VideoFrame_00024Buffer_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoFrame$Buffer";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_VideoFrame_00024I420Buffer_clazz_defined
#define org_webrtc_VideoFrame_00024I420Buffer_clazz_defined
inline jclass org_webrtc_VideoFrame_00024I420Buffer_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoFrame$I420Buffer";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoFrame_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& buffer,
    JniIntWrapper rotation,
    int64_t timestampNs) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Lorg/webrtc/VideoFrame$Buffer;IJ)V",
      &cached_method_id);
  auto _ret = env->NewObject(
      clazz,
      call_context.method_id(),
      buffer.obj(),
      as_jint(rotation),
      timestampNs);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoFrame_getBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getBuffer",
      "()Lorg/webrtc/VideoFrame$Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static int32_t Java_VideoFrame_getRotation(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getRotation",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int64_t Java_VideoFrame_getTimestampNs(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getTimestampNs",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static void Java_VideoFrame_release(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "release",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Buffer_cropAndScale(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper cropX,
    JniIntWrapper cropY,
    JniIntWrapper cropWidth,
    JniIntWrapper cropHeight,
    JniIntWrapper scaleWidth,
    JniIntWrapper scaleHeight) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "cropAndScale",
      "(IIIIII)Lorg/webrtc/VideoFrame$Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      as_jint(cropX),
      as_jint(cropY),
      as_jint(cropWidth),
      as_jint(cropHeight),
      as_jint(scaleWidth),
      as_jint(scaleHeight));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static int32_t Java_Buffer_getBufferType(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getBufferType",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_Buffer_getHeight(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getHeight",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_Buffer_getWidth(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getWidth",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static void Java_Buffer_release(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "release",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

static void Java_Buffer_retain(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "retain",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Buffer_toI420(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toI420",
      "()Lorg/webrtc/VideoFrame$I420Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_I420Buffer_getDataU(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024I420Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getDataU",
      "()Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_I420Buffer_getDataV(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024I420Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getDataV",
      "()Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_I420Buffer_getDataY(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024I420Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getDataY",
      "()Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static int32_t Java_I420Buffer_getStrideU(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024I420Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getStrideU",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_I420Buffer_getStrideV(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024I420Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getStrideV",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static int32_t Java_I420Buffer_getStrideY(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoFrame_00024I420Buffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getStrideY",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JVideoFrame> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoFrame> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_Buffer>& buffer,
      JniIntWrapper rotation,
      int64_t timestampNs) {
    return Java_VideoFrame_Constructor(env, buffer, rotation, timestampNs)
        .As<::org::webrtc::JVideoFrame>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JVideoFrame> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoFrame_Buffer> getBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame>*>(this);
    return Java_VideoFrame_getBuffer(env, *this_obj)
        .As<::org::webrtc::JVideoFrame_Buffer>();
  }

  int32_t getRotation(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame>*>(this);
    return Java_VideoFrame_getRotation(env, *this_obj);
  }

  int64_t getTimestampNs(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame>*>(this);
    return Java_VideoFrame_getTimestampNs(env, *this_obj);
  }

  void release(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame>*>(this);
    Java_VideoFrame_release(env, *this_obj);
  }

};

template<>
class _CalledByNatives<::org::webrtc::JVideoFrame_Buffer> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoFrame_Buffer> cropAndScale(
      JNIEnv* env,
      JniIntWrapper cropX,
      JniIntWrapper cropY,
      JniIntWrapper cropWidth,
      JniIntWrapper cropHeight,
      JniIntWrapper scaleWidth,
      JniIntWrapper scaleHeight) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_Buffer>*>(this);
    return Java_Buffer_cropAndScale(
        env,
        *this_obj,
        cropX,
        cropY,
        cropWidth,
        cropHeight,
        scaleWidth,
        scaleHeight)
        .As<::org::webrtc::JVideoFrame_Buffer>();
  }

  int32_t getBufferType(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_Buffer>*>(this);
    return Java_Buffer_getBufferType(env, *this_obj);
  }

  int32_t getHeight(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_Buffer>*>(this);
    return Java_Buffer_getHeight(env, *this_obj);
  }

  int32_t getWidth(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_Buffer>*>(this);
    return Java_Buffer_getWidth(env, *this_obj);
  }

  void release(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_Buffer>*>(this);
    Java_Buffer_release(env, *this_obj);
  }

  void retain(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_Buffer>*>(this);
    Java_Buffer_retain(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoFrame_I420Buffer> toI420(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_Buffer>*>(this);
    return Java_Buffer_toI420(env, *this_obj)
        .As<::org::webrtc::JVideoFrame_I420Buffer>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JVideoFrame_I420Buffer> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> getDataU(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_I420Buffer>*>(this);
    return Java_I420Buffer_getDataU(env, *this_obj)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> getDataV(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_I420Buffer>*>(this);
    return Java_I420Buffer_getDataV(env, *this_obj)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> getDataY(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_I420Buffer>*>(this);
    return Java_I420Buffer_getDataY(env, *this_obj)
        .As<::java::nio::JByteBuffer>();
  }

  int32_t getStrideU(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_I420Buffer>*>(this);
    return Java_I420Buffer_getStrideU(env, *this_obj);
  }

  int32_t getStrideV(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_I420Buffer>*>(this);
    return Java_I420Buffer_getStrideV(env, *this_obj);
  }

  int32_t getStrideY(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoFrame_I420Buffer>*>(this);
    return Java_I420Buffer_getStrideY(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using VideoFrameJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JVideoFrame>;
}
#ifndef _JNI_ZERO_VideoFrameJni_DEFINED
#define _JNI_ZERO_VideoFrameJni_DEFINED
using ::org::webrtc::VideoFrameJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_VideoFrame_JNI
