// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoDecoderFactory

#ifndef org_webrtc_VideoDecoderFactory_SHARED_JNI
#define org_webrtc_VideoDecoderFactory_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_webrtc_JVideoCodecInfo_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoCodecInfo_DEFINED
namespace org::webrtc {
class _JVideoCodecInfo : public _jobject {};
using JVideoCodecInfo = _JVideoCodecInfo*;
}
#endif

#ifndef _JNI_ZERO_JVideoCodecInfo_DEFINED
#define _JNI_ZERO_JVideoCodecInfo_DEFINED
using ::org::webrtc::JVideoCodecInfo;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoDecoder_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoDecoder_DEFINED
namespace org::webrtc {
class _JVideoDecoder : public _jobject {};
using JVideoDecoder = _JVideoDecoder*;
}
#endif

#ifndef _JNI_ZERO_JVideoDecoder_DEFINED
#define _JNI_ZERO_JVideoDecoder_DEFINED
using ::org::webrtc::JVideoDecoder;
#endif

#ifndef _JNI_ZERO_org_webrtc_JVideoDecoderFactory_DEFINED
#define _JNI_ZERO_org_webrtc_JVideoDecoderFactory_DEFINED
namespace org::webrtc {
class _JVideoDecoderFactory : public _jobject {};
using JVideoDecoderFactory = _JVideoDecoderFactory*;
}
#endif

#ifndef _JNI_ZERO_JVideoDecoderFactory_DEFINED
#define _JNI_ZERO_JVideoDecoderFactory_DEFINED
using ::org::webrtc::JVideoDecoderFactory;
#endif


#endif  // org_webrtc_VideoDecoderFactory_SHARED_JNI
