// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoCodecInfo

#ifndef org_webrtc_VideoCodecInfo_JNI
#define org_webrtc_VideoCodecInfo_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "VideoCodecInfo_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_VideoCodecInfo()

// Class Accessors
#ifndef org_webrtc_VideoCodecInfo_clazz_defined
#define org_webrtc_VideoCodecInfo_clazz_defined
inline jclass org_webrtc_VideoCodecInfo_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoCodecInfo";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoCodecInfo_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& name,
    const ::jni_zero::JavaRef<jobject>& params) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoCodecInfo_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;Ljava/util/Map;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), name.obj(), params.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jstring> Java_VideoCodecInfo_getName(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoCodecInfo_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getName",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoCodecInfo_getParams(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoCodecInfo_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getParams",
      "()Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JVideoCodecInfo> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoCodecInfo> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& name,
      const ::jni_zero::JavaRef<::java::util::JMap<jstring, jstring>>& params) {
    return Java_VideoCodecInfo_Constructor(env, name, params)
        .As<::org::webrtc::JVideoCodecInfo>();
  }

};

template<>
class _CalledByNatives<::org::webrtc::JVideoCodecInfo> {
  public:
  ::jni_zero::ScopedJavaLocalRef<jstring> getName(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoCodecInfo>*>(this);
    return Java_VideoCodecInfo_getName(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<jstring, jstring>> getParams(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoCodecInfo>*>(this);
    return Java_VideoCodecInfo_getParams(env, *this_obj)
        .As<::java::util::JMap<jstring, jstring>>();
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using VideoCodecInfoJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JVideoCodecInfo>;
}
#ifndef _JNI_ZERO_VideoCodecInfoJni_DEFINED
#define _JNI_ZERO_VideoCodecInfoJni_DEFINED
using ::org::webrtc::VideoCodecInfoJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_VideoCodecInfo_JNI
