// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.webrtc.VideoEncoderWrapper

#ifndef org_webrtc_VideoEncoderWrapper_JNI
#define org_webrtc_VideoEncoderWrapper_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "VideoEncoderWrapper_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// void VideoEncoderWrapper::OnEncodedFrame(
//     JNIEnv* env,
//     const jni_zero::JavaRef<::org::webrtc::JEncodedImage>& frame);
//

// Triggers a compiler warning if DEFINE_JNI(VideoEncoderWrapper) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_VideoEncoderWrapper() {}

// Java to native functions
#define DEFINE_JNI_FOR_VideoEncoderWrapper()                                                       \
  namespace {                                                                                      \
                                                                                                   \
  using namespace webrtc::jni;                                                                     \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_MgpJuQUh(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      int64_t nativeVideoEncoderWrapper,                                                           \
      jobject frame) {                                                                             \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_VideoEncoderWrapper();                                         \
                                                                                                   \
    auto frame_ref = jni_zero::JavaRef<::org::webrtc::JEncodedImage>::CreateLeaky(env,             \
        static_cast<::org::webrtc::JEncodedImage>(frame));                                         \
    VideoEncoderWrapper* _ptr = reinterpret_cast<VideoEncoderWrapper*>(nativeVideoEncoderWrapper); \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(_ptr->OnEncodedFrame(std::forward<decltype(args)>(args)...)) {                      \
        return _ptr->OnEncodedFrame(std::forward<decltype(args)>(args)...);                        \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, frame_ref); }) {                                  \
        return func_wrapper(env, frame_ref);                                                       \
      } else if constexpr (requires { func_wrapper(frame_ref); }) {                                \
        return func_wrapper(frame_ref);                                                            \
      } else {                                                                                     \
        static_assert(false, "VideoEncoderWrapper::OnEncodedFrame() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (const jni_zero::JavaRef<JEncodedImage>&)\nSee gen/jni_headers/sdk/android/generated_video_jni/VideoEncoderWrapper_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

// Class Accessors
#ifndef org_webrtc_VideoEncoderWrapper_clazz_defined
#define org_webrtc_VideoEncoderWrapper_clazz_defined
inline jclass org_webrtc_VideoEncoderWrapper_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoEncoderWrapper";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef org_webrtc_VideoEncoderWrapper_00024NativeEncoderCallback_clazz_defined
#define org_webrtc_VideoEncoderWrapper_00024NativeEncoderCallback_clazz_defined
inline jclass org_webrtc_VideoEncoderWrapper_00024NativeEncoderCallback_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.webrtc.VideoEncoderWrapper$NativeEncoderCallback";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoEncoderWrapper_createEncoderCallback(
    JNIEnv* env,
    int64_t nativeEncoder) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderWrapper_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "createEncoderCallback",
      "(J)Lorg/webrtc/VideoEncoderWrapper$NativeEncoderCallback;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), nativeEncoder);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoEncoderWrapper_getScalingSettingsHigh(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& scalingSettings) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderWrapper_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getScalingSettingsHigh",
      "(Lorg/webrtc/VideoEncoder$ScalingSettings;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), scalingSettings.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static ::jni_zero::ScopedJavaLocalRef<jobject> Java_VideoEncoderWrapper_getScalingSettingsLow(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& scalingSettings) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderWrapper_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getScalingSettingsLow",
      "(Lorg/webrtc/VideoEncoder$ScalingSettings;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), scalingSettings.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static bool Java_VideoEncoderWrapper_getScalingSettingsOn(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& scalingSettings) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderWrapper_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getScalingSettingsOn",
      "(Lorg/webrtc/VideoEncoder$ScalingSettings;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), scalingSettings.obj());
  return _ret;
}

static void Java_NativeEncoderCallback_invalidate(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_VideoEncoderWrapper_00024NativeEncoderCallback_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "invalidate",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}



}  // namespace webrtc::jni

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::webrtc::jni;

template<>
class _CalledByNativesStatics<::org::webrtc::JVideoEncoderWrapper> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::org::webrtc::JVideoEncoderWrapper_NativeEncoderCallback> createEncoderCallback(
      JNIEnv* env,
      int64_t nativeEncoder) {
    return Java_VideoEncoderWrapper_createEncoderCallback(env, nativeEncoder)
        .As<::org::webrtc::JVideoEncoderWrapper_NativeEncoderCallback>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> getScalingSettingsHigh(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoder_ScalingSettings>& scalingSettings) {
    return Java_VideoEncoderWrapper_getScalingSettingsHigh(env, scalingSettings)
        .As<::java::lang::JInteger>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> getScalingSettingsLow(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoder_ScalingSettings>& scalingSettings) {
    return Java_VideoEncoderWrapper_getScalingSettingsLow(env, scalingSettings)
        .As<::java::lang::JInteger>();
  }

  static bool getScalingSettingsOn(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoder_ScalingSettings>& scalingSettings) {
    return Java_VideoEncoderWrapper_getScalingSettingsOn(env, scalingSettings);
  }

};

template<>
class _CalledByNatives<::org::webrtc::JVideoEncoderWrapper_NativeEncoderCallback> {
  public:
  void invalidate(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::webrtc::JVideoEncoderWrapper_NativeEncoderCallback>*>(this);
    Java_NativeEncoderCallback_invalidate(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace org::webrtc {
using VideoEncoderWrapperJni = ::jni_zero_internal::_CalledByNativesStatics<::org::webrtc::JVideoEncoderWrapper>;
}
#ifndef _JNI_ZERO_VideoEncoderWrapperJni_DEFINED
#define _JNI_ZERO_VideoEncoderWrapperJni_DEFINED
using ::org::webrtc::VideoEncoderWrapperJni;
#endif


#pragma clang diagnostic pop
#endif  // org_webrtc_VideoEncoderWrapper_JNI
